### ISSUE TITLE
RDS IOPS validation incorrect (should be 50:1 not 10:1)

### ISSUE THREAD

**Issue by coopernurse** [cloudtools/troposphere#1004]
Hello folks.  I was updating some out of date CF templates generated via troposphere to match what I'd (manually) configured in RDS.  In one case I have a database with this config:

```
AllocatedStorage = 100GB
PIOPS = 3000
```

When I run troposphere with these options I get this error:

```
ValueError: AllocatedStorage must be no less than 1/10th the provisioned Iops
```

Maybe AWS changed this ratio.  I see 50:1 documented as the upper limit here:

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html

**Comment by markpeek** [comment]
Thanks! Fixed via https://github.com/cloudtools/troposphere/commit/db4e11018584bfb7dae40d1124c6334ca5137060

**Comment by coopernurse** [comment]
Wow, that was quick.  Thanks!
