### ISSUE TITLE
Add "BatchParameters" to the Target options of CloudWatch Events

### ISSUE THREAD

**Issue by GaboP87** [cloudtools/troposphere#1008]
Hi,

It would be nice iff you guys update the code to support the "BatchParameters" option for the CloudWatch Targets.
I would need to trigger a batch Job from CloudFormation and it is not available there yet.

Can you help me with this?

Thanks,
Gabriel

**Comment by markpeek** [comment]
I believe you are referring to [this](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_Target.html) which according to the CloudFormation docs [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html) has not been implemented (in CloudFormation) yet.

**Comment by skydread1** [comment]
Hi,

Do you know when that will be implemented ?
Do you know a way around to schedule batch job submissions to the batch queue ?

Thanks,

**Comment by kylemurphycambia** [comment]
@skydread1 - you can add add lambda as an intermediary for this, event -> lambda -> batch, you can pass the job definition and queue info within the input field in the event.

**Comment by posac** [comment]
Hi,
See that its developed on your side. When can I expect release with this change ??

**Comment by PatMyron** [comment]
picked up in https://github.com/cloudtools/troposphere/commit/326002606209cdcb92e4134af2e0cf50d2f838f0 and released in [`2.5.3`](https://github.com/cloudtools/troposphere/releases/tag/2.5.3)
