### ISSUE TITLE
GetCidr() is incorrect

### ISSUE THREAD

**Issue by urluba** [cloudtools/troposphere#1013]
Hi guys,

The [GetCidr() function](https://github.com/cloudtools/troposphere/blob/24ab9d4fd6ea044992e6df3deb4987a67036442d/troposphere/__init__.py#L415) is retranscribed as Fn::GetCidr which results in an error. According to the doc, it should be [Fn::Cidr](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-cidr.html)

Thanks for your work

**Comment by markpeek** [comment]
Sometimes I think I'm going crazy on why I would use GetCidr instead of Cidr. But this was likely due to the original [docs](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/intrinsic-function-reference-getcidr.md) changing online. We'll get it updated.

**Comment by markpeek** [comment]
Thanks for the issue, fixed now.

**Comment by urluba** [comment]
Thanks ! FYI, I've contacted AWS support:

> The documentation is not 100% accurate, the third parameter "sizeMask" seems to be required and not optional, I'm going to reach out the documentation team asking them to take a look at it.
> 
> In order to use the "Fn::Cidr" function to create 6 subnets with mask "/27" inside a "/24" mask VPC, you should use the below values:
> 
> VpcCidr: "192.168.0.0/24"
> CidrCount: "6" 
> sizeMask: "5" (i.e. 32-27=5)

**Comment by webratz** [comment]
Is there already a date when the next release will be, so that could be used directly from the python package?

**Comment by markpeek** [comment]
I'm traveling and need to incorporate a few more changes. I'll create a new release over the weekend.
