### ISSUE TITLE
Cloudfront for S3 website hosting - Global name "CustomOriginConfig" not defined

### ISSUE THREAD

**Issue by rajashreebaradur** [cloudtools/troposphere#1021]
I am trying to create Cloudfront distribution using the template similar to troposphere/examples/CloudFront_S3.py. 
Instead of using S3OriginConfig=S3Origin(), I am using CustomOriginConfig() and I get the following error:

NameError: global name "CustomOriginConfig" is not defined

I did not find any classes for CustomOriginConfig in your documents. Is it still being worked on?

**Comment by rajashreebaradur** [comment]
Tried that too.

Here is the error:
    CustomOriginConfig=CustomOrigin(
NameError: global name 'CustomOrigin' is not defined

Do I need to import any other libraries?

**Comment by ikben** [comment]
Yes, you need to import it the same way as `S3Origin` is imported at the top of the example.

`from troposphere.cloudfront import CustomOrigin`

or if you need both, you can put them on the same line

`from troposphere.cloudfront import S3Origin, CustomOrigin`

**Comment by markpeek** [comment]
Here's an [example](https://github.com/cloudtools/troposphere/blob/master/examples/CloudFront_S3.py) usage for S3Origin.

**Comment by rajashreebaradur** [comment]
@ikben : Thanks. It works perfectly now.

@markpeek : Yes I am referring to the same example. 

Thanks for the help.
