### ISSUE TITLE
codepipeline.ActionTypeId has the wrong case

### ISSUE THREAD

**Issue by chizou** [cloudtools/troposphere#1027]
https://github.com/cloudtools/troposphere/blob/master/troposphere/codepipeline.py#L10

As referenced from the CloudFormation documentation, the D in ID should be lowercase:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html#cfn-codepipeline-pipeline-stages-actions-actiontypeid

**Comment by markpeek** [comment]
Fixed via rename.
