### ISSUE TITLE
WAF - Creating a XSS HEADER filter seems missing the Header data field

### ISSUE THREAD

**Issue by legiscope** [cloudtools/troposphere#1032]
Maybe i'm wrong but i'm trying to find out how to create a XSS rule using the HEADER field and it seems there's one field missing. 

Look when creating it on the console - using the HEADER field we have to add another sub-field  : 

<img width="1477" alt="capture d ecran 2018-04-28 a 23 44 51" src="https://user-images.githubusercontent.com/34229706/39400703-5d90fc7e-4b3e-11e8-9db5-90d63a06b0af.png">

Now when i try to add this field i'm left without the possibility to do it :

```
class XssMatchTuple(AWSProperty):
    props = {
        'FieldToMatch': (FieldToMatch, True),
        'TextTransformation': (basestring, True),
    }

```
Not sure if that's possible or the right way to do it

**Comment by legiscope** [comment]
Actually i was wrong it's completely doable !

FieldToMatch=FieldToMatch(
                Type="HEADER",
                Data="cookie"
                )

**Comment by noon1234** [comment]
class XssMatchTuple(AWSProperty):
    props = {
        'FieldToMatch': (FieldToMatch, True),
        'TextTransformation': (basestring, True),
    }
