### ISSUE TITLE
Cant's use RegexMatchTuple on WAF

### ISSUE THREAD

**Issue by legiscope** [cloudtools/troposphere#1034]
There's a few ressource missing to create Regex rules on the WAF ; here are the docs :  
https://docs.aws.amazon.com/waf/latest/APIReference/API_RegexMatchSet.html
https://docs.aws.amazon.com/waf/latest/APIReference/API_RegexPatternSet.html

And here's what missing : 
RegexMatchTuple
RegexMatchSet
RegexPatternSet

Implementation would be very appreciated !
Cheers

**Comment by phobologic** [comment]
Hey @legiscope - are you sure those resources are available in Cloudformation (the docs you linked are in the API)?  Can you point me at the Cloudformation resources that you believe need to be updated?  Thanks!

**Comment by PatMyron** [comment]
Troposphere cannot support features CloudFormation itself does not yet support. CloudFormation support can being tracked through the [`AWS::WAF` resource type reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_WAF.html), [Coverage Roadmap](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/), and [Release History documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
