### ISSUE TITLE
TemplateGenerator emits TypeError when importing bools that should be strings

### ISSUE THREAD

**Issue by ThatGerber** [cloudtools/troposphere#1044]
Gist: https://gist.github.com/ThatGerber/1fdb34ca4d293f8c34c1fbca09c5252f

This same error affects other resources like `troposphere.ecs.Environment` https://github.com/cloudtools/troposphere/blob/master/troposphere/ecs.py#L105 where the value being imported can be any type, but should be cast as String. The Json/Yaml marshaller attempts to determine the type of each object when creating the object, and the TemplateGenerator requires them to be passed in a certain way.

**Comment by markpeek** [comment]
@ThatGerber I just created a PR that seems to resolve your gist. Please check it out.

**Comment by ThatGerber** [comment]
I’ll try to install and take a look tonight.

**Comment by ThatGerber** [comment]
Still getting an error. https://gist.github.com/ThatGerber/68ce6a34a7939dc50545037f98432528
