### ISSUE TITLE
Cloudformation error on tags type validation when provisioning dax resource

### ISSUE THREAD

**Issue by jswoods** [cloudtools/troposphere#1045]
When provisioning a dax resource, cloudformation shows the error:

```
Property validation failure: [Value of property {/Tags} does not match type {Map}]
```

The dax object should use a dict instead of the Tags object for the Tags property.

**Comment by ARMAAN7139** [comment]
I am getting similar error when provisioning AWS PinPoint App using CFN.

**Comment by markpeek** [comment]
@ARMAAN7139 since this issue is closed, can you open a new issue and include a small test case with the error you are getting?
