### ISSUE TITLE
Issue with rds.troposphere 

### ISSUE THREAD

**Issue by Pradhebaa** [cloudtools/troposphere#1061]
Hi,
Today I found out that, AWS RDS for oracle is now supporting Transport layer Security (released May 30, 2018). I was trying to use the OptionSettings parameter in the OptionGroup resource, but I was thrown an error, even though I imported  troposphere.rds 
`TypeError: <class 'troposphere.rds.OptionConfiguration'>: None.OptionSettings is <class 'set'>, expected [<class `'troposphere.rds.OptionSetting'>]`

My code:
`resource_refs['RdsOracleOptionGroup'] = template.add_resource(
    rds.OptionGroup(
        'RdsOracleOptionGroup',
        EngineName=config.get('Engine', 'oracle-se1'),
        MajorEngineVersion=str(config.get('MajorEngineVersion', '11.2')),
        OptionGroupDescription='Option group for %s' % config['project'],
        OptionConfigurations=[
            rds.OptionConfiguration(
                VpcSecurityGroupMemberships=[Ref(resource_refs['RdsSecGrp'])],
                OptionName='SSL',
                OptionSettings = [
                 'SQLNET.SSL_VERSION',
                '1.0'
            ],
                Port=2484
            )
        ]`

Please advise me , if the troposphere library is not updated for this new feature or my usage is wrong?

![screenshot from 2018-06-05 14-29-48](https://user-images.githubusercontent.com/26472298/40995382-ec1b92b4-68cc-11e8-88a5-f6fdd752f4bd.png)

**Comment by Pradhebaa** [comment]
Update:

I edited my code to use rds.OptionSetting, now the error clearly shows that 
`AttributeError: OptionSetting object does not support attribute SQLNET.SSL_VERSION`

code:
`OptionConfigurations=[
            rds.OptionConfiguration(
                VpcSecurityGroupMemberships=[Ref(resource_refs['RdsSecGrp'])],
                OptionName='SSL',
                OptionSettings = [rds.OptionSetting(**option_setting)
            ],
                Port=2484
            )
        ]`

`option_setting = {
    'SQLNET.SSL_VERSION': '1.0'
}`

**Comment by markpeek** [comment]
Likely you should try something like:
```
OptionSettings=[
    OptionSetting(Name='SQLNET.SSL_VERSION', Value='1.0'),
]
```
