### ISSUE TITLE
Support for EKS (Managed Kubernetes)?

### ISSUE THREAD

**Issue by matt-dalton** [cloudtools/troposphere#1064]
AWS launched EKS in some regions in the last week. I suspect this is going to be a pretty in-demand service, and I heard they are launching with CloudFormation support. Is there a plan/timeline for adding this to the library?

Great lib btw 👍

**Comment by markpeek** [comment]
EKS support was added the day of the announcement with this commit 5d2f369d7a189467cad9bb3a0c0152d0e750c76f. I was hoping to get a few more items into master before cutting a new release. I am wondering whether to include a troposphere translation of the EKS CloudFormation script. Thoughts?

**Comment by matt-dalton** [comment]
Oh amazing! Sorry for not spotting - I searched through existing issues instead. I haven't yet familiarised myself with the CloudFormation implementation beyond what's [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html). What is the script you are referring to?

**Comment by markpeek** [comment]
This [Getting Started guide](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html) has a step that brings up the EKS Cluster VPC. The CloudFormation yaml script is [here](https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/amazon-eks-vpc-sample.yaml
) which I'm wondering whether people would want as a troposphere example.

**Comment by matt-dalton** [comment]
Ahh got it - yeah I think definitely useful for beginners. My particular use-case would be adding to an existing VPC, but including a standard example would be handy.

**Comment by markpeek** [comment]
This was released in 2.3.1 on 2018-07-01.

**Comment by markpeek** [comment]
Closing. Note: opened #1096 to track the addition of an EKS cluster example.
