### ISSUE TITLE
Sagemaker support

### ISSUE THREAD

**Issue by nadlerjessie** [cloudtools/troposphere#1073]
Now that there is [cloudformation support](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstance.html) for Sagemaker, it would be nice to have Sagemaker (and [notebook instance lifecycle configs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstancelifecycleconfig.html)) included in troposphere.

**Comment by markpeek** [comment]
Yes, I had hoped to add support for SageMaker. However, the current way of adding these resources is through the CloudFormation resource specification and SageMaker hasn't been updated yet. @cmmeyer was looking into the issue.

**Comment by cmmeyer** [comment]
There was a hiccup with the merge process for self-service resources into the master spec.  I've been told this has been corrected and we should get the new resources (SageMaker, MQ) soon.  Sorry for the delay!  We're waiting for 'em too on the linter side...

**Comment by markpeek** [comment]
Thanks @cmmeyer for the update and getting it corrected!

**Comment by markpeek** [comment]
This was released in 2.3.1 on 2018-07-01. Note: I had to manually add it since the resource spec hasn't been updated lately.
