### ISSUE TITLE
Add new params to AWS::EC2::VPCEndpoint type

### ISSUE THREAD

**Issue by TheRealBenForce** [cloudtools/troposphere#1080]
On June 21st, 2018, AWS added CloudFormation support for the following params:
- Use the PrivateDnsEnabled property to indicate whether to associate a private hosted zone with the specified VPC.
- Use the SecurityGroupIds property to specify the ID of one or more security groups to associate with the endpoint network interface.
- Use the SubnetIds property to specify the ID of one or more subnets in which to create an endpoint network interface.
- Use the VpcEndpointType property to specify the type of endpoint.

[CloudFormation Release History](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
[AWS::EC2::VPCEndpoint CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html)

**Comment by cigan1** [comment]
@TheRealBenForce this issue is addresses by this pull request https://github.com/cloudtools/troposphere/pull/1085

**Comment by hese1** [comment]
@cigan1 did you check my reference above? #1084

**Comment by cigan1** [comment]
@hese1 yes sir I see it. Looks like we need to consolidate. How do we do this?

**Comment by hese1** [comment]
@cigan1 Added you as a collaborator in my fork, care to add the validator stuff there? Branch name 'update-vpcendpoint-properties'

**Comment by markpeek** [comment]
This was released in 2.3.1 on 2018-07-01.
