### ISSUE TITLE
Add Support for PrivateLink.

### ISSUE THREAD

**Issue by mik373** [cloudtools/troposphere#1081]
AWS released CF support for the service endpoint: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html.

**Comment by hese1** [comment]
Hey, just submitted a PR for this.

#1084 AWS PrivateLink support

**Comment by markpeek** [comment]
This was released in 2.3.1 on 2018-07-01.
