### ISSUE TITLE
Unsupported property CpuCredits used for EC2 Instances.

### ISSUE THREAD

**Issue by johnctitus** [cloudtools/troposphere#1099]
It looks like #1068 caused a breaking change to EC2 instances using `CreditSpecification` property, resulting in the following error when trying to deploy the generated templates:

```
unsupported property CpuCredits
```

It appears the change was implemented to correct an error when deploying LaunchTemplates, however the object type for [LaunchTemplate CreditSpecification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-creditspecification.html) uses a different case than for [EC2 Instance CreditSpecification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-creditspecification.html).  Looks like separate classes will need to be defined for each use.

**Comment by markpeek** [comment]
Having multiple cases for CpuCredits in what should be the same object seems silly and unintended by the CloudFormation team. @cmmeyer is it possible to DM a contact on the team to me in order to discuss directly?

**Comment by cmmeyer** [comment]
This could be a self-service growing pain, since EC2 is now split between CloudFormation coverage for older features and the EC2 team for LaunchTemplates.  Cutting an internal ticket to see if we can get this normalized.  I'll see if I can get you someone to talk to, @markpeek

**Comment by cmmeyer** [comment]
Spoke with the teams involved.  CpuCredits will be accurate going forward -- AWS::EC2::Instance should be the only reference to the legacy CPUCredits.  They're investigating if it will be possible to allow AWS::EC2::Instance to align to the other cases, but regardless, you'll want the new class to handle all new resources that reference CpuCredits.  Sorry for the discrepancy!

**Comment by johnctitus** [comment]
@markpeek  @cmmeyer  Any traction on this?  If there is a change to the PR that would make it more acceptable, I am happy to implement.  

I am looking at using the new EKS and VPC Endpoint types, but can't until a new troposphere version with this issue fixed is released.
