### ISSUE TITLE
Elastic Load Balancing Action::FixedResponseActionConfig missing

### ISSUE THREAD

**Issue by johnosterlund** [cloudtools/troposphere#1127]
The Elastic Load Balancing Action::FixedResponseActionConfig property is missing.

https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Action.html
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_FixedResponseActionConfig.html

**Comment by flou** [comment]
It seems that CloudFormation does not support those properties yet.

**Comment by lanwen** [comment]
see https://github.com/cloudtools/troposphere/pull/1140 for possible addition

**Comment by markpeek** [comment]
Fixed via #1140
