### ISSUE TITLE
Missing support for VPCEndpointServicePermissions

### ISSUE THREAD

**Issue by jcook793** [cloudtools/troposphere#1128]
We only allow certain roles to approve VPC endpoint requests, so I'd need to specify those ARNs.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservicepermissions.html

**Comment by oussemos** [comment]
Hey @jcook793 

This issue can be closed as VPCEndpointServicePermissions was added with #1130

**Comment by jcook793** [comment]
Yep, I am happily using it now, thanks!
