### ISSUE TITLE
DBInstance does not take to account DBParameterGroup

### ISSUE THREAD

**Issue by hajdukd** [cloudtools/troposphere#1144]
I've just created a simple RDS config based on this example:
https://github.com/cloudtools/troposphere/blob/master/examples/RDS_with_DBParameterGroup.py

`        dbparamgroup = template.add_resource(DBParameterGroup(
            "myparamgroupname",
            Family="postgres9.5",
            Description="Configuration with overwritten max_prepared_transactions parameter",
            Parameters={
                "max_prepared_transactions": "300"
            }
        ))

...
template.add_resource(DBInstance(
            DBParameterGroupName=Ref(dbparamgroup),
...
`
Database created has:
Option Group
   default:postgres-9-5
Parameter group
   default.postgres9.5 (in-sync)

---
That's using troposphere 2.3.3.

Is this regression ? Cant tell, i've never used this feature before.

**Comment by markpeek** [comment]
Not sure what the exact issue is with this bug report. Is this still a problem? If so, please add more details on the error.

**Comment by hajdukd** [comment]
Fyi: had to manually change the configuration of the database because troposphere failed to apply it automatically ( max_prepared_connections )

**Comment by markpeek** [comment]
Here is a simple example that worked fine for me based on this [example](https://github.com/cloudtools/troposphere/blob/master/examples/RDS_with_DBParameterGroup.py) (note: obviously insecure user/pass):
```
from troposphere import Parameter, Ref, Template
from troposphere.rds import DBInstance, DBParameterGroup


t = Template()

dbuser = "dbuser"
dbpassword = "dbpassword"

myrdsparamgroup = t.add_resource(DBParameterGroup(
    "MyRDSParamGroup",
    Family="postgres9.6",
    Description="Sample postgres Database Parameter Group",
    Parameters={
        "max_prepared_transactions": 300,
    }
))

mydb = t.add_resource(DBInstance(
    "MyDB",
    AllocatedStorage="5",
    DBInstanceClass="db.t2.micro",
    Engine="postgres",
    EngineVersion="9.6.5",
    MasterUsername=dbuser,
    MasterUserPassword=dbpassword,
    DBParameterGroupName=Ref(myrdsparamgroup),
))

print(t.to_json())
```

**Comment by hajdukd** [comment]
It's the same sample that i gave in an opener. And like i said it did not work in 2.3.3.
RDS instance configuration parameter group didn't change at the time.

Mby it was fixed in the newer version - my only guess.
