### ISSUE TITLE
Extra backslashes (character escaping) happening in certain strings

### ISSUE THREAD

**Issue by DoNotMicrowave** [cloudtools/troposphere#1159]
The following command string in one of my CloudFormation configs is changed in the resources JSON:

```
'config':
    cloudformation.InitConfig(
        packages={'yum': {}},
        commands={
            'customize_prompt': {
                'command': 'sed -i \'s/PS1="\[\\u@\\h \\W\]\\\\\$ "/PS1="\[\\u@\\H \\W\]\\\\\$ "/\' /etc/bashrc'
            }
```

In the generated resources JSON, the resource definition looks like so:
```
    "customize_prompt": {
        "command": "sed -i 's/PS1=\"\\[\\u@\\h \\W\\]\\\\\\$ \"/PS1=\"\\[\\u@\\H \\W\\]\\\\\\$ \"/' /etc/bashrc"
    }
```

Notice how there is an extra slash added in front of the regular expression characters ([, $, ]) in the resource JSON? What could be doing this? The command won't run on the instance properly with the added backslashes. Thanks in advance!

**Comment by DoNotMicrowave** [comment]
Maybe this code in encode_to_dict (base class AWSProperty) is trying to help (by adding the extra escaping when printing):

```
    # This is useful when dealing with external libs using
    # this format. Specifically awacs.
    elif hasattr(obj, 'JSONrepr'):
        return encode_to_dict(obj.JSONrepr())
```

**Comment by markpeek** [comment]
The mangling likely has more to do with the backslashes and trying to escape them through json encode/decode. Try using r"string" and assume that the json should escape (backslash) any backslashes in the string effectively doubling them but will be decoded later. I think this is what you want.

**Comment by DoNotMicrowave** [comment]
I don't think raw strings helped, possible because they are non-raw when processed later -- not sure. I just know that when I tried to use them, nothing changed with the string on the cfn instance metadata side. Perhaps I did something wrong. I have concluded just now through more manual keyboard pounding in the Python interpreter that I don't think my string is correct with respect to escaping that needs to be "doubled-up", as you mentioned. Thank you for the fast reply.

**Comment by DoNotMicrowave** [comment]
You are right. I was way deep into a terrible string with many escaped characters, some having to be double-escaped for sed on the other end (note that when added to JSON, they are even more escaped, as you also said). At first I thought raw strings weren't helping, but I think I had escaped an inner string. The final command (which replaces the hostname in the bash prompt to have a full-qualified domain name) in troposphere looks like so (I doubt it will help anyone, but wanted to put it here just in case):

```
'005_customize_prompt': {
    'command': r"sed -i 's/PS1=\"\[\\u@\\h \\W\]\\\\\$ \"/PS1=\"\[\\u@\\H \\W\]\\\\\$ \"/' /etc/bashrc"
}
```

Thanks for your prompt response and all of your work markpeek!

**Comment by markpeek** [comment]
Nice! Thanks for following up with your solution.
