### ISSUE TITLE
Set Password Policy for AWS Account?

### ISSUE THREAD

**Issue by LewisYates** [cloudtools/troposphere#1162]
Are you able to create a password policy for an AWS account in Troposphere? 

I can see creating policies for groups, users, roles etc.

But I want to know if this is possible for the entire Account?

Cheers!

**Comment by axelpavageau** [comment]
As far as I know you can't, as it's not part of the resources available in cloudformation (currently:  

- AWS::IAM::AccessKey
- AWS::IAM::Group
- AWS::IAM::InstanceProfile
- AWS::IAM::ManagedPolicy
- AWS::IAM::Policy
- AWS::IAM::Role
- AWS::IAM::ServiceLinkedRole
- AWS::IAM::User
- AWS::IAM::UserToGroupAddition

)

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/107
