### ISSUE TITLE
DBCluster Enginemode

### ISSUE THREAD

**Issue by ayk33** [cloudtools/troposphere#1184]
Trying to create a `DBcluster` and setting EngineMode to `serverless`. 
I get the following error:
`AttributeError: AWS::RDS::DBCluster object does not support attribute EngineMode`

Is that attribute supported?

**Comment by seddarj** [comment]
It's not part of any release yet but the functionality has already been added and merged to master (see #1166)

So now it's just a matter of a new version being released with those changes.

**Comment by seddarj** [comment]
Duplicate of #1155

**Comment by ayk33** [comment]
Closing issue.
