### ISSUE TITLE
sagemaker.Model.VpcConfig should be a type

### ISSUE THREAD

**Issue by jonporterjones** [cloudtools/troposphere#1191]
This is defined in troposphere as a string.  The AWS documentation shows VpcConfig as a property of AWS::SageMaker::Model resource defined like this:

{
  "Subnets" : [String, ... ],
  "SecurityGroupIds: [String, ... ]
}

I am new to troposphere but I don't believe this can be created in troposphere from the current definition of sagemaker.Model.VpcConfig

**Comment by markpeek** [comment]
Fixed via #1214
