### ISSUE TITLE
EC2 SpotFleet unable to create

### ISSUE THREAD

**Issue by maikelpenz** [cloudtools/troposphere#1195]
The release 2.3.4 introduced a bug in the file `troposphere/ec2.py`, class `SpotFleetRequestConfigData`:
- Both `LaunchTemplateConfigs` and `LaunchSpecifications` are set as required, but as per the cloudformation documentation they are conditional (you can only set one of them)

The `validate` function is correctly implementing the conditional logic but in the properties they should be set to false, not true.

**Comment by travisemichael** [comment]
Is there any workaround for this?

**Comment by maikelpenz** [comment]
> Is there any workaround for this?

I got this [pull request](https://github.com/cloudtools/troposphere/pull/1198) waiting to be accepted. In the meantime you can point your code to use version 2.3.3 instead

**Comment by stanb** [comment]
> Is there any workaround for this?

somewhere in your code...
```
SpotFleetRequestConfigData.props['LaunchSpecifications'] = ([LaunchSpecifications], False)
SpotFleetRequestConfigData.props['LaunchTemplateConfigs'] = ([LaunchTemplateConfigs], False)

```
