### ISSUE TITLE
Cloudformation Drift and Security Group Ports

### ISSUE THREAD

**Issue by daugustus** [cloudtools/troposphere#1208]
I appreciate the hard work that has gone into Troposphere- I really like it and use it in my daily work.

It appears that with the latest offering of Drift Detection deals with the port numbers. In my case, I see that when the ip protocol is specified as '-1', CF does NOT want port numbers specified. However, Troposphere requires the ports. The result of this difference appears in the drift detection console in AWS. :(

Thanks,
Dave

**Comment by orenmazor** [comment]
Ha. just got nailed by this.

**Comment by markpeek** [comment]
Fixed via #1277
