### ISSUE TITLE
S3 Tagging inconsitency

### ISSUE THREAD

**Issue by psummers678** [cloudtools/troposphere#1211]
Noticed that Tags for S3 do not accept a list, where as it seems that most other resources accept both Tags and list.
Although Issue #350 said this was intended and that the fault was against RDS and not S3, Issue #845 seems to have changed that, with intent to make both compatible. 
Could the #845 fix be implemented on S3, or is there underlying problems I am missing?

**Comment by markpeek** [comment]
The intent here was to migrate usage to Tags and eventually deprecate the list form. In other words, you likely will see ```(Tags, list)``` for older implementations of objects while ```Tags``` for newer ones.
