### ISSUE TITLE
Sagemaker NotebookInstanceLifecycleConfig is broken

### ISSUE THREAD

**Issue by hese1** [cloudtools/troposphere#1213]
https://github.com/cloudtools/troposphere/blob/master/troposphere/sagemaker.py

Class 'NotebookInstanceLifecycleConfig' has been implemented twice, both as AWSProperty and AWSObject. The one stated as AWSProperty should instead be labeled 'NotebookInstanceLifecycleHook' (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-notebookinstancelifecycleconfig-notebookinstancelifecyclehook.html).

Additionally, several definitions and types are just wrong:
- 'InitialVariantLength' missing from 'ProductionVariant' class
- 'ModelName' boolean in 'ProductionVariant' class (lol)
- 'DirectInternetAccess' string when should be boolean in 'NotebookInstance'

**Comment by markpeek** [comment]
Fixed via your change #1214
