### ISSUE TITLE
Wrong property name for RDS Cloudwatch Logs

### ISSUE THREAD

**Issue by sid137** [cloudtools/troposphere#1248]
I think the property here is missing an `s`

https://github.com/cloudtools/troposphere/blob/master/troposphere/rds.py#L179

The [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-enablecloudwatchlogsexports) says that it should be `EnableCloudwatchLogsExports`,  not `EnableCloudwatchLogExports` as is in [the code](https://github.com/cloudtools/troposphere/blob/master/troposphere/rds.py#L179
)

**Comment by markpeek** [comment]
Fixed via #1253
