### ISSUE TITLE
Add support for Metrics attribute in AWS::CloudWatch::Alarm

### ISSUE THREAD

**Issue by seddarj** [cloudtools/troposphere#1250]
Feature was released in CloudFormation on November 20th

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html

**Comment by oussemos** [comment]
@seddarj it's already in pull request (see #1227)

**Comment by axelpavageau** [comment]
Hello. I believe this is resolved by #1227

**Comment by seddarj** [comment]
Hi, indeed, I did a search for `Metrics` and couldn't find anything, closing... Thanks!

**Comment by girishkhadke** [comment]
Is this available as part of 2.3.4 troposphere version ?

I have following installed in my python virtualenvironment: 

(ebansible) M117553F2G8WP:ansible girish_khadke$ pip freeze | grep boto
boto==2.49.0
boto3==1.9.71
botocore==1.12.71
(ebansible) M117553F2G8WP:ansible girish_khadke$ pip freeze | grep awscli
awscli==1.16.81
(ebansible) M117553F2G8WP:ansible girish_khadke$ pip freeze | grep troposphere
troposphere==2.3.4

But still I get following error when I try to generate CFN template (yaml) using troposphere:
[
        "Traceback (most recent call last):", 
        "  File \"./vip_oidc_dynamo_alarms_cfn.py\", line 8, in <module>", 
        "    def run(description=\"DynamoDB Regional Alarms Stack for tables related to VIP OIDC Application\"):", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/main.py\", line 115, in _start", 
        "    prog.start()", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/main.py\", line 54, in start", 
        "    collector=self._collector)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/cmdline.py\", line 253, in apply_options", 
        "    return_value = call_function(func, signature(ext), opts)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/cmdline.py\", line 236, in call_function", 
        "    return func(*pargs, **kwargs)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/convert.py\", line 92, in wrapper", 
        "    return func(*args, **kwargs)", 
        "  File \"./vip_oidc_dynamo_alarms_cfn.py\", line 9, in run", 
        "    dynamo_alarms.run(description=description)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/wrappable.py\", line 20, in __call__", 
        "    return self.__wrapped__(*args, **kwargs)", 
        "  File \"/Users/girish_khadke/.virtualenvs/ebansible/lib/python2.7/site-packages/begin/convert.py\", line 92, in wrapper", 
        "    return func(*args, **kwargs)", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 213, in run", 
        "    template = VipOidcDynamoDbAlarmsTemplate(Description=description)", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 21, in __init__", 
        "    self.build()", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 208, in build", 
        "    self.build_resources();", 
        "  File \"/Users/girish_khadke/vip-oidc/vip-oidc-deploy/ansible/cft/vip_oidc_dynamo_alarms.py\", line 146, in build_resources", 
        "    cloudwatch.MetricDataQuery(", 
        "AttributeError: 'module' object has no attribute 'MetricDataQuery'"
    ],
