### ISSUE TITLE
DynamoDB On Demand support

### ISSUE THREAD

**Issue by asyschikov** [cloudtools/troposphere#1257]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-billingmode

You can now specify BillingMode on demand and there is no need to specify capacity. Could you add it please?

**Comment by oussemos** [comment]
@asyschikov it's already in pull request (see #1243)

**Comment by markpeek** [comment]
Fixed via #1243
