### ISSUE TITLE
Support secrets in ECS containerDefinitions

### ISSUE THREAD

**Issue by g00ds0n** [cloudtools/troposphere#1259]
Please look into adding the `secrets` property to the containerDefinition.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

**Comment by oussemos** [comment]
Hi @g00ds0n it's not supported in Cloudformation 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

**Comment by g00ds0n** [comment]
Yes, I did notice that after I made the ticket. Can this be left open until it is supported?

**Comment by oussemos** [comment]
@g00ds0n you can close it, and create a new one when it's supported.

**Comment by g00ds0n** [comment]
Will do.
