### ISSUE TITLE
Wrong use of json_checker in ssm.py causing errors

### ISSUE THREAD

**Issue by seddarj** [cloudtools/troposphere#1260]
I think there's an issue with the way the `json_checker` is being used in https://github.com/cloudtools/troposphere/blob/master/troposphere/ssm.py#L38

This validator is supposed to take 2 arguments as input but if used as an attribute type, it will only get one thus spitting the following error:
```
TypeError: json_checker() takes exactly 2 arguments (1 given)
```

I think it is supposed to be used as part of another validator that can be used as an attribute type, see here for an example: https://github.com/cloudtools/troposphere/blob/d4682854dfd39957891857d17db082e7970997f7/troposphere/apigateway.py#L304

**Comment by markpeek** [comment]
Nice catch! Surprised more people weren't seeing issues. I just pushed a change to resolve it.
