### ISSUE TITLE
Need full properties in AWS::Serverless::Api

### ISSUE THREAD

**Issue by blian7432** [cloudtools/troposphere#1278]
Tropsphere serverless api supports : 
"props = {
        'StageName': (basestring, True),
        'Name': (basestring, False),
        'DefinitionBody': (dict, False),
        'DefinitionUri': (basestring, False),
        'CacheClusterEnabled': (bool, False),
        'CacheClusterSize': (basestring, False),
        'Variables': (dict, False),
    }"

The aws official doc supports more properties: 
MethodSettings, EndpointConfiguration,BinaryMediaTypes,Cors,Auth,AccessLogSetting,CanarySetting,TracingEnabled

Could you please add these properties in serverless api?

Thank you

**Comment by markpeek** [comment]
I added the additional parameters but I'm not promising this is strictly correct (the docs aren't great) and likely will need follow up changes. The Auth settings are a bit wonky. Give it a try and file Issues/PRs on it.
