### ISSUE TITLE
Sagemaker - ProductionVariant object does not support attribute InitialVariantWeight

### ISSUE THREAD

**Issue by pr334** [cloudtools/troposphere#1281]
Hi,

I'm trying to write a troposphere code to create an Endpoint config. Below is the syntax i used to add Endpoint config resource to my template. On execution I was getting this error - **"ProductionVariant object does not support attribute InitialVariantWeight"** 

Code Snippet:
---------------
self.template.add_resource(sagemaker.EndpointConfig(
            "SagemakerEndpointConfig",
            EndpointConfigName = Ref(self.endpointConfigName),
            ProductionVariants = [ sagemaker.ProductionVariant(
                         ModelName = GetAtt("SagemakerModel","ModelName"),
                         VariantName = Ref(self.variantName),
                         InitialInstanceCount = Ref(self.initialInstanceCount),
                         InstanceType = Ref(self.instanceType),
                         InitialVariantWeight = 2.0) ]

Could anyone please help me in this ?

**Comment by markpeek** [comment]
I ran a quick test and it worked for me. Likely you have not upgraded to troposphere 2.4.0 where that attribute was added (0e7d6532).
```
$ python
Python 2.7.14 (default, Mar 22 2018, 14:43:05)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import troposphere; import troposphere.sagemaker as s; import pprint
>>> print troposphere.__version__
2.4.0
>>> pprint.pprint(s.ProductionVariant("test").props)
{'InitialInstanceCount': (<function integer at 0x10cc94de8>, True),
 'InitialVariantWeight': (<type 'float'>, True),
 'InstanceType': (<type 'basestring'>, True),
 'ModelName': (<type 'basestring'>, True),
 'VariantName': (<type 'basestring'>, True)}
>>>
```

I did note that Tags() shows as required in the docs while it likely should be optional.

**Comment by pr334** [comment]
oh my bad. Thanks a lot :)
