### ISSUE TITLE
troposphere.cloudfront.CustomOrigin changed to CustomOriginConfig?

### ISSUE THREAD

**Issue by marty-sullivan** [cloudtools/troposphere#1284]
It seems like this breaking change was added in one of the recent versions. It would be good to have kept the CustomOrigin object available in addition to adding CustomOriginConfig instead of removing it. I have updated my code to reflect this change, but I imagine others will also have breaking changes with the latest release.

**Comment by markpeek** [comment]
My apologies for the breaking change. As a project we try to reduce the number of these breaking changes and can sometimes mitigate with deprecation of objects. However, we also try to mirror the AWS documentation which changes over time when bugs are detected in the documentation. We find it is better to maintain documentation compatibility for our users and ensure there is a 1:1 correspondence in resource/property naming. I understand this puts a burden on existing scripts when names change and I will think how we could do a better job with deprecation warnings especially as the project looks to rely more heavily on autogenerated code via the resource specification files. Thank you for being a troposphere user and letting me know the impact of this breaking change.

**Comment by lsh-0** [comment]
Just been bit by this. 

If troposphere is using semver then API-breaking changes should have seen a [major version bump](https://semver.org).
