### ISSUE TITLE
Template add_mapping method converting a string to a float

### ISSUE THREAD

**Issue by syassen** [cloudtools/troposphere#1290]
When I call add_mapping where the key is a string starting with 0 - the key is being converted to a float.  This looks to have been introduced recently as it used to work.
See sample code:
def add_mappings(self):
    self.add_mapping(
        'AccountMap',
            {
                # data sandbox
                '218': {
                    'VPCId': 'testvpc',  # Data-VPC
                    'SubnetIds': ['subnet-a', 'subnet-b'],  
                },
                # production
                '0653': {
                    'VPCId': 'vpc-test',  # ProdVPC
                    'SubnetIds': ['subnet-1', 'subnet-2'], 
                }
            }
    )

When I then try to call CreateChangeSet on the template I now get the error:
Template format error: [/Mappings/AccountMap] map keys must be strings; received numeric [6.53] instead

-- The 0 is required as our production AWS account id starts with a 0!

This looks to be a bug introduced in a recent version of troposphere as this worked fine last year.

**Comment by syassen** [comment]
This looks to be an issue with AWS templates not troposphere.  Will close issue

**Comment by markpeek** [comment]
There was this [issue](https://github.com/cloudtools/troposphere/issues/994) with yaml in the past but yes, I suspect this is an AWS issue.
