### ISSUE TITLE
Layers doesn't exists for AWS::Serverless::Function 

### ISSUE THREAD

**Issue by not-macbox** [cloudtools/troposphere#1294]
Getting `AttributeError: AWS::Serverless::Function object does not support attribute Layers`.
The official documentation shows that the support should be present [here](https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#awsserverlessfunction).

**Comment by markpeek** [comment]
Fixed on master. Thanks for the issue.
