### ISSUE TITLE
Support UpdateReplacePolicy

### ISSUE THREAD

**Issue by rtkmhart** [cloudtools/troposphere#1304]
AWS just added the [UpdateReplacePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html) feature for all resources on January 23, 2019, please add support for it. I will try get a PR together in the next week or so if time permits.

**Comment by markpeek** [comment]
Implemented the same day via c981776de1ad5f2130eb8c0861a0fac46170c97a. Please try it out on the master branch. I'm hoping to resolve a few outstanding changes and then get a release out soon.

**Comment by rtkmhart** [comment]
That's fantastic @markpeek I searched issues and PR's but couldn't find any reference to it. I'll try it out later this week.

**Comment by markpeek** [comment]
Release in 2.4.2 just now.
