### ISSUE TITLE
Support for AWS::Serverless::LayerVersion

### ISSUE THREAD

**Issue by Anheurystics** [cloudtools/troposphere#1305]
There exists support for AWS::Lambda::LayerVersion, but not [AWS::Serverless::LayerVersion](https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md#awsserverlesslayerversion) (though it's almost the same, save for Content vs ContentUri. A Layers property would also have to be added to the Function resource.

I can create the pull request myself once I get around to setting up a local dev repo.

**Comment by markpeek** [comment]
Too bad they didn't use the same names to make it easier for us to reuse. Oh well! Let me know if you can make the PR or else I can add it in. BTW, I added the Layers property with this [commit[(334c14be214684fa802670f389e7d7658e469d39).

**Comment by markpeek** [comment]
Added it into serverless.py. Thanks for the issue.
