### ISSUE TITLE
TemplateGenerator replaces some class type by their openstack counterpart

### ISSUE THREAD

**Issue by christianbeland** [cloudtools/troposphere#1319]
The template_generator.py _import_all_troposphere_modules function load all modules and then sometime overwrites cloudformation class definitions (due to ordering) by their openstack counterparts.

I stumble on this problem while loading a template with an AutoScalingGroup and received

> AttributeError: AWS::AutoScaling::AutoScalingGroup object does not support attribute AutoScalingGroupName

I did a bit and found that the resource type AWS::AutoScaling::AutoScalingGroup was sometime being translated to <class 'troposphere.openstack.heat.AWSAutoScalingGroup'>.

I will probably fail with a lot of other resources.

**Comment by markpeek** [comment]
Resolved by excluding the OpenStack modules within the template generator.
