### ISSUE TITLE
aws cdk vs troposphere

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#1327]
Hi there, general question. I'm reading the documentation for aws cdk and it looks like it generates CloudFormation template just like troposphere. My question is what is the benefit of using Troposphere vs AWS CDK? I see in AWS CDK you can build assets for docker (https://awslabs.github.io/aws-cdk/refs/_aws-cdk_assets-docker.html#dockerimageasset), not sure if this is supported via Troposphere. Maybe that's one thing that's different. Any comments here and opinions from experience would be helpful.

**Comment by Caprowni** [comment]
If you look at it from this perspective, CDK is trying to compete with Terraform - at least in my opinion - it has similar functionality as terraform with the outputs/creating etc. etc. that Cloudformation doesn't natively support out of the box.  The only reason I see to use Troposphere currently is that CDK doesn't support Python yet AND it's still early release - in their documentation they specifically highlight that they will be introducing breaking changes.  Based on those two factors alone for me I would steer clear of using for anything important for the foreseeable future until there is a proper stable version out there.

**Comment by kapilt** [comment]
cdk feels closer to troposphere then terraform, its just adding abstractions on top per se, under the hood its still just a cfn pre-render and execute setup.
