### ISSUE TITLE
add support for blue green deployment configuration for ECS services

### ISSUE THREAD

**Issue by dmore** [cloudtools/troposphere#1336]
latest ecs service blue green deployment requires a new element on ecs service called DeploymentController that is settable on ecs service creation to  CODE_DEPLOY. This is mandatory for ecs blue green deployment configuration.

Also DeploymentGroup 'blueGreenDeploymentConfiguration' is missing on the latest DeploymentGroup from troposphere

**Comment by markpeek** [comment]
Will address after this feature is added to CloudFormation.

**Comment by ronancunningham72** [comment]
I believe this is now  supported in cloudformation :https://docs.aws.amazon.com/en_pv/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentcontroller.html

**Comment by markpeek** [comment]
Thanks for the reminder. Added via cef0530d83c859be2093610d0fc35b25889eaa34 commit.
