### ISSUE TITLE
PatchBaseline properties missing

### ISSUE THREAD

**Issue by Tyler-R** [cloudtools/troposphere#1339]
Currently PatchBaseline does not support:

* Sources
* RejectedPatchesAction
* ApprovedPatchesEnableNonSecurity

despite there being support for those properties in [CloudFormation.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-patchbaseline.html) 

Would someone be able to add support for these properties?

**Comment by markpeek** [comment]
Thanks for the issue. Added to master.
