### ISSUE TITLE
Template to_yaml with long_form=True broken since 2.3.1+

### ISSUE THREAD

**Issue by shatil** [cloudtools/troposphere#1345]
I learned in #976 that Troposphere's `to_yaml(long_form=True`) function could render multi-line strings nicely using YAML's pipe convention, like this:

```yaml
UserData:
  Base64:
    Fn::Sub: |
      This is
      some
      user data
```

However, since `troposphere==2.3.1`, it's been doing this, instead:

```yaml
UserData: !Base64
  Fn::Sub: "\nThis is\nsome\nuser data\n"
```

Take a gander using `pip3 install troposphere==2.3.0` and this:

```python
import troposphere
t = troposphere.Template()
t.add_description("This\nis\ndescriptive")
print(t.to_yaml(long_form=True))
```

Then compare to anything newer than 2.3.1, e.g., `pip3 install troposphere==2.4.5`.

**Comment by markpeek** [comment]
The change between 2.3.0 and 2.3.1 that you are seeing is #1055 where the parameters passed to to_yaml were incorrect. You need to use `to_yaml(clean_up=True)` to get the behavior you are looking for in later versions of troposphere.

**Comment by shatil** [comment]
@markpeek, ah, thank you. Closing.
