### ISSUE TITLE
Missing Ref objects for new pseudo-parameters (AWS::Partition, AWS::URLSuffix)

### ISSUE THREAD

**Issue by danielkza** [cloudtools/troposphere#1347]
Older pseudo-parameters (AccountId, NoValue, Region, StackId,  StackName) have objects corresponding to their `Ref`s in the root of the `troposphere` module, but newer ones (Partition, URLSuffix) do not.

**Comment by markpeek** [comment]
Thanks! I added URLSuffix. Partition was already there.

**Comment by danielkza** [comment]
Awesome, thank you!
