### ISSUE TITLE
CodeBuild.Project.Name shouldn't be required

### ISSUE THREAD

**Issue by chizou** [cloudtools/troposphere#1348]
The Name parameter of [CodeBuild.Project](https://github.com/cloudtools/troposphere/blob/master/troposphere/codebuild.py#L285) currently is `(basestring, True)` but according to the documentation, it should be false: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-name

**Comment by markpeek** [comment]
Fixed. Thanks!
