### ISSUE TITLE
update emr.StepConfig ActionOnFailure validation

### ISSUE THREAD

**Issue by travisemichael** [cloudtools/troposphere#1349]
`ActionOnFailure` validation fails for value "CONTINUE".

According to CloudFormation docs: "Currently, AWS CloudFormation supports CONTINUE and CANCEL_AND_WAIT."

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html#cfn-emr-step-actiononfailure

**Comment by markpeek** [comment]
As you mention ActionOnFailure, do you mean [AWS::EMR::Step](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html#cfn-emr-step-actiononfailure) or [AWS::EMR::Cluster StepConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-stepconfig.html#cfn-elasticmapreduce-cluster-stepconfig-actiononfailure)? These have different values and different validators in troposphere.

**Comment by markpeek** [comment]
Merged your fix. Thanks!
