### ISSUE TITLE
EKS - Add support for CloudWatch logging

### ISSUE THREAD

**Issue by rtkgjacobs** [cloudtools/troposphere#1362]
As of EKS 1.12, CloudWatch logging has been added as an optional feature. Cloudformation has support for this but it is not yet available in troposphere.

- Add support for the `logging` parameter as per the following documentation:

See reference docs:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html
* https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

Changes required in `troposphere/troposphere/eks.py`

Add a new AWSProperty class for `logging` and within it resource structre based on above docs e.g.
```python
{'clusterLogging': [{'enabled': True,
                     'types': ['api',
                               'audit',
                               'authenticator',
                               'controllerManager',
                               'scheduler']}]}
```

**Comment by rtkjbillo** [comment]
Looks like this might have been added in https://github.com/cloudtools/troposphere/commit/52121ac4598c8a9919dd9d4c6cc2b1836f93a027#diff-2d64eb87d459eb49493c722f0fb8d6d5 but not yet bundled into a release.

**Comment by PatMyron** [comment]
Troposphere cannot support features CloudFormation itself does not yet support. CloudFormation support is being tracked here:
https://github.com/aws/containers-roadmap/issues/242
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/208

**Comment by ajmal-bash** [comment]
This feature is now available using the EKS cluster CFN resource
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-clusterlogging.html

Ref: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/208#issuecomment-966755117

@PatMyron Do we now have a timeline by when this could be available in troposphere ?

**Comment by crbetts1** [comment]
Would like an update on this as well. I see that changes were pushed on this commit [6a998b7fd7c404a80d46e9f3d796fd71c3e378fd](https://github.com/cloudtools/troposphere/commit/6a998b7fd7c404a80d46e9f3d796fd71c3e378fd)
Is there a timeline on when a tag will be released that includes this change?
Thanks

**Comment by markpeek** [comment]
I have a small handful of services to convert over to auto-generated. Hoping to get it done over the weekend for a release.
