### ISSUE TITLE
ConnectionDrainingPolicy & AccessLoggingPolicy incorrectly identified as elasticloadbalancingv2 instead of elasticloadbalancing

### ISSUE THREAD

**Issue by allyunion** [cloudtools/troposphere#1368]
ConnectionDrainingPolicy & AccessLoggingPolicy incorrectly identified as elasticloadbalancingv2 instead of elasticloadbalancing

**Comment by PatMyron** [comment]
Looks correct now:

https://github.com/cloudtools/troposphere/blob/a28753d7532a5177b85ee0838de2f78bb128d6d0/troposphere/elasticloadbalancing.py#L78-L85

https://github.com/cloudtools/troposphere/blob/a28753d7532a5177b85ee0838de2f78bb128d6d0/troposphere/elasticloadbalancingv2.py#L341-L354

[`AWS::ElasticLoadBalancing::LoadBalancer`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html)
[`AWS::ElasticLoadBalancingV2::LoadBalancer`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html)
