### ISSUE TITLE
DBSubnetGroup - PropagateAtLaunch causes failure. Can it be removed?

### ISSUE THREAD

**Issue by ernievd** [cloudtools/troposphere#1369]
In DBSubnetGroup  - tags you are forced to use true or false in PropagateAtLaunch and it creates the PropagateAtLaunch in the tags area.  AWS throws an error stating that it does not recognize PropagateAtLaunch in DBSubnetGroupand the stack will not come up.
If I manually remove the PropagateAtLaunch  in the DBSubnetGroup in my taml cloudformation file then it comes up.

This is only an issue with DBSubnetGroup tags in troposphere.

Is there a workaround?

**Comment by markpeek** [comment]
The use of PropagateAtLaunch is only in the autoscaling variant. All other Tags do not need or use it. Perhaps you are importing the one from autoscaling and not the generic one [here](https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L528)?

**Comment by ernievd** [comment]
Importing from here -

from troposphere.rds import DBInstance, DBSubnetGroup

Here is my code - 
```
# <editor-fold desc="DB subnet group">
dbsubnetgroup = t.add_resource(DBSubnetGroup(
    "DBSubnetGroup",
    DBSubnetGroupDescription="Subnets available for the RDS DB Instance",
    SubnetIds=[Ref(PrivateSubnet1a), Ref(PrivateSubnet1b)],
    Tags=[
#        Tag("Environment", params.ENVIRONMENT, False),
       Tag("Name", Join(" : ", [Ref("AWS::StackName"), "DB Subnet Group"]), False),
    ],
))
```
If I remove the false from the tag line then i get an error upon creating the yaml (requires three params). 

The Tru/False sets the propagation at launch which AWS does not support with dbsubnetgroup

**Comment by markpeek** [comment]
Right...where are you importing the Tag object from? You should use:
```
from troposphere import Tags
...
Tags=Tags({"Name": Join(" : ", [Ref("AWS::StackName"), "DB Subnet Group"])})
...
```

**Comment by ernievd** [comment]
Mistake on my end (newbie here!) It was the join.

Thanks!
