### ISSUE TITLE
Opsworks EngineAttributes should take list

### ISSUE THREAD

**Issue by wynnsusilo** [cloudtools/troposphere#1371]
EngineAttributes variable in the Server class is currently taking a single EngineAttribute object, but Cloudformation allows for a list of attributes, as is necessary when using puppet R10K. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworkscm-server.html#cfn-opsworkscm-server-engineattributes

**Comment by wynnsusilo** [comment]
I created [pull request 1363](https://github.com/cloudtools/troposphere/pull/1363)

**Comment by markpeek** [comment]
Fixed via #1363.
