### ISSUE TITLE
"AllocatedStorage" parameter in rds.DBInstance is optional

### ISSUE THREAD

**Issue by paro1234** [cloudtools/troposphere#1374]
This parameter is not supported by "Aurora" and hence it is dependent on the engine we choose
[https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html](url)

_AllocatedStorage -> (integer)_

_For all database engines except Amazon Aurora, AllocatedStorage specifies the allocated storage size in gibibytes (GiB). For Aurora, AllocatedStorage always returns 1, because Aurora DB cluster storage size is not fixed, but instead automatically adjusts as needed_

**Comment by paro1234** [comment]
This parameter is not supported by "Aurora" and hence it is dependent on the engine we choose
[https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html](url)

_AllocatedStorage -> (integer)

For all database engines except Amazon Aurora, AllocatedStorage specifies the allocated storage size in gibibytes (GiB). For Aurora, AllocatedStorage always returns 1, because Aurora DB cluster storage size is not fixed, but instead automatically adjusts as needed_

**Comment by PatMyron** [comment]
[Looks like `AWS::RDS::DBInstance.AllocatedStorage` was made optional in this commit](https://github.com/cloudtools/troposphere/commit/36a7b5c10e1ff63ba97a729cf535805c65d09c57)

https://github.com/cloudtools/troposphere/blob/3c1ef2d29fe7a63772cba7b44df5850f05ac5271/troposphere/rds.py#L169

Try upgrading your Troposphere version if you're still experiencing this problem
