### ISSUE TITLE
Add Support for AWS Backup

### ISSUE THREAD

**Issue by dannyleesmith** [cloudtools/troposphere#1411]
Hey folks,

Support for AWS Backup has now been released in CloudFormation: https://aws.amazon.com/about-aws/whats-new/2019/05/aws-backup-now-supports-aws-cloudformation/

Would be good to get this supported.

Thanks,

-- Danny

**Comment by PatMyron** [comment]
https://github.com/cloudtools/troposphere/blob/master/troposphere/backup.py
