### ISSUE TITLE
(Autoscaling group) HeartbeatTimeout has the wrong type

### ISSUE THREAD

**Issue by urluba** [cloudtools/troposphere#1415]
Hi,

A lifecycle hook can be defined either as AWS::AutoScaling::LifecycleHook object or as a property of AWS::AutoScaling::AutoScalingGroup. In the latest, the  HeartbeatTimeout attribute is not an integer but a [basestring ](https://github.com/cloudtools/troposphere/blob/2797fd3198f13a478210a1bf226fa6a4d61e0a51/troposphere/autoscaling.py#L66)

According to [official doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-lifecyclehookspecification.html#cfn-autoscaling-autoscalinggroup-lifecyclehookspecification-heartbeattimeout
), it should also be an integer.

**Comment by PatMyron** [comment]
fixed by https://github.com/cloudtools/troposphere/pull/1432
