### ISSUE TITLE
ApiKey and UsagePlan objects do not support attribute Tags

### ISSUE THREAD

**Issue by pepastach** [cloudtools/troposphere#1416]
Hi,

I'm getting the following errors when trying to tag an ApiKey or a UsagePlan:

`AWS::ApiGateway::ApiKey object does not support attribute Tags`
`AWS::ApiGateway::UsagePlan object does not support attribute Tags`

Here's an example code:
```
self.template.add_resource(
    ApiKey(
        'ApiKey',
        Name='ApiKey',
        Enabled=True,
        GenerateDistinctId=False,
        StageKeys=[
            StageKey(
                RestApiId=api_id,
                StageName=stage_name
            )
        ],
        Tags=Tags(
            Customer='CompanyX',
            Plan='Professional'
        )
    )
)

self.template.add_resource(
    UsagePlan(
        'UsagePlan',
        ApiStages=[
            ApiStage(
                ApiId=api_id,
                Stage=stage_name
            )
        ],
        UsagePlanName='UsagePlan',
        Tags=Tags(
            Customer='CompanyX',
            Plan='Professional'
        )
    )
)
```

According to the AWS documentation, both API keys and usage plans can be tagged: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-tagging-supported-resources.html

Any plans for supporting tags?

Thanks!

Great job BTW! Troposphere saves me a tons of time. 👍

**Comment by flou** [comment]
CloudFormation does not yet support tags for [ApiKey](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html) and [UsagePlan](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplan.html).

We need to wait until CloudFormation adds these properties.

**Comment by lhgomes** [comment]
> CloudFormation does not yet support tags for [ApiKey](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html) and [UsagePlan](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplan.html).
> 
> We need to wait until CloudFormation adds these properties.

Any news on this ?

**Comment by PatMyron** [comment]
[CloudFormation now supports tagging](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/4) for both [`AWS::ApiGateway::ApiKey`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html) and [`AWS::ApiGateway::UsagePlan`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplan.html)
