### ISSUE TITLE
Support "Secrets" in AWS::ECS::TaskDefinition ContainerDefinition

### ISSUE THREAD

**Issue by luyaosuperman** [cloudtools/troposphere#1428]
Hi, 

"Secrets" in AWS::ECS::TaskDefinition ContainerDefinition is supported in CloudFormation by now.
Can we add it to Troposphere?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-secrets

Thanks!
Yao

**Comment by luyaosuperman** [comment]
Pull request created. Hope it is the right way
https://github.com/cloudtools/troposphere/pull/1429

**Comment by markpeek** [comment]
This was added as part of [Release 2.4.8](https://github.com/cloudtools/troposphere/releases/tag/2.4.8).
