### ISSUE TITLE
AWS::CodeBuild::Project::ProjectCache LOCAL

### ISSUE THREAD

**Issue by darrenlewis1985** [cloudtools/troposphere#1434]
I have seen that PR #1413 has recently been merged into `master` to add the `LOCAL` option into the valid values for `Type` in AWS::CodeBuild::Project::ProjectCache. When will this be released?

**Comment by andreimahu** [comment]
I would also like to know when a new release will be available. I am specifically interested in the transit gateway and resource access manager resources.

**Comment by markpeek** [comment]
Likely sometime over the weekend. I need to do a final round of changes based on the latest release history.

**Comment by markpeek** [comment]
Meant to update this issue. [Release 2.4.8](https://github.com/cloudtools/troposphere/releases/tag/2.4.8) was released yesterday.
