### ISSUE TITLE
Add MSK (kafka) cluster creation support

### ISSUE THREAD

**Issue by stoiev** [cloudtools/troposphere#1435]
Amazon has released Cloudformation support for [MSK](https://aws.amazon.com/about-aws/whats-new/2019/06/amazon_msk_is_now_integrated_with_aws_cloudformation_and_terraform/)

It would be great to have it on troposphere.

**Comment by euler1337** [comment]
Indeed

**Comment by Coada** [comment]
I am not sure if MSK Configurations have been released to CloudFormation, but if this is the case I would also ask this to be added to Troposphere

**Comment by stoiev** [comment]
> I am not sure if MSK Configurations have been released to CloudFormation, but if this is the case I would also ask this to be added to Troposphere

Not completely. It's possible to choose/update configuration of a Cluster, but not create them.

The configuration reference is basically a tuple with an Arn an revision number inside MSK Cluster object. Is it possible/practice to create a Troposphere class that depends _statically_ on references like this? Is this a blocker?

**Comment by markpeek** [comment]
MSK support was added via #1436 and released in 2.4.8 yesterday.

@stoiev not sure I understand your question about troposphere classes that depend statically.

**Comment by stoiev** [comment]
Nevermind, I was wondering if the nonexistence of MSK Configurations management by cloudformation would be a blocker. Obviously it is not. Thanks for the update!
