### ISSUE TITLE
Fix ec2 VPNConnection Tags to support list as well as Tag object

### ISSUE THREAD

**Issue by archercrichton** [cloudtools/troposphere#1442]
Recent update altered the way tags were supplied to the VPNConnection resource which broke pre-exisitng scripts that used a list for adding tags. Adding list to Tags property of VPNConnection

**Comment by archercrichton** [comment]
I don't have access to create a branch. In ec2.py, I propose to change line 699  from "'Tags': (Tags, False)," to "'Tags': ((Tags, list), False),"

**Comment by markpeek** [comment]
Agreed on regression. I just pushed a fix out. Although I would encourage people to migrate from using list to Tags.

**Comment by markpeek** [comment]
@archercrichton just pushed release 2.4.9 with the fix. Thanks for the issue.
