### ISSUE TITLE
Iam Role has invalid property Tags

### ISSUE THREAD

**Issue by pbecotte** [cloudtools/troposphere#1453]
CFN-Lint flagged a template I generated (my code adds tags to any resource that has a `Tags` prop)
`Invalid Property Resources/RedshiftRole/Properties/Tags`

I see that you have Tags on the Role object-
https://github.com/cloudtools/troposphere/blob/master/troposphere/iam.py#L85

but AWS does not-
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html

If this is valid I'd be happy to send in a PR to update it.

**Comment by markpeek** [comment]
This was added via #1441 by @jpvowen where he observed it being supported. But yes, I see the docs and spec files indicate it isn't supported. I just used the below to test and it did show the Tags in the IAM UI.
```
from troposphere import Template, Ref, Tags
from troposphere.iam import Role

from awacs.aws import Allow, Statement, Principal, PolicyDocument
from awacs.sts import AssumeRole

t = Template()
cfnrole = t.add_resource(Role(
    "CFNRole",
    AssumeRolePolicyDocument=PolicyDocument(
        Statement=[
            Statement(
                Effect=Allow,
                Action=[AssumeRole],
                Principal=Principal("Service", ["ec2.amazonaws.com"])
            )
        ]
    ),
    Tags=Tags(foo="bar"),
))

print(t.to_json())
```

**Comment by pbecotte** [comment]
So what is the approach? In general, would we expect Troposphere to follow the published docs, or not? Either way is fine of course!
If this is intended, feel free to close. In that event, should I be making a PR against the cfn-lint repo possibly?

**Comment by markpeek** [comment]
I try to follow the specs/docs as closely as possible. However, these are frequently out of date or incorrect. So I try to balance "doing the right thing" to have what is appropriate for users to get their jobs done. In this case I can see that Tags works for IAM Role and likely is being used. I try to funnel these back to the CloudFormation team in the hope it gets corrected. For cfn-lint, I know there is an override mechanism for the spec files that they implemented. I'd suggest submitting a patch to support this there as well.

**Comment by pbecotte** [comment]
Sounds good
