### ISSUE TITLE
Cognito missing EmailSendingAccount attribute in EmailConfiguration

### ISSUE THREAD

**Issue by bellaxie** [cloudtools/troposphere#1455]
Can we please add this attribute? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-emailconfiguration.html

**Comment by markpeek** [comment]
Fixed via b35acf1e74883d3ba5670dc13d6a5434b691ee49. Thanks for the issue.
