### ISSUE TITLE
Implement EFS FileSystem LifecyclePolicies

### ISSUE THREAD

**Issue by isuftin** [cloudtools/troposphere#1456]
At this time it does not seem as though LifecyclePolicies is implemented.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-elasticfilesystem-filesystem-lifecyclepolicies

This is a feature request to implement the LifecyclePolicies

**Comment by markpeek** [comment]
Added. Thanks!
