### ISSUE TITLE
LicenseSpecifications parameter for AWS::EC2::LaunchTemplate

### ISSUE THREAD

**Issue by jk2l** [cloudtools/troposphere#1457]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-licensespecifications

AWS::EC2::LaunchTemplate have support for LicenseSpecifications, but troposphere is not supporting it yet.  This is required for integration with AutoScaling group as current LicenseSpecifications support by AWS::EC2::Instance only

**Comment by markpeek** [comment]
Merged your PR. Thanks!
