### ISSUE TITLE
No props for SshPublicKey class in transfer

### ISSUE THREAD

**Issue by aprotsik** [cloudtools/troposphere#1459]
There are no props to pass for SshPublicKey class. Maybe I'm just not getting how to use it. Will apreciate help if that's not an issue actually.

**Comment by jt3po** [comment]
@axelpavageau  can you have a look? I think you authored the pull for this. 

We're trying to understand how to create an instance of the User class that has a value for the SshPublicKeys field. 

The AWS CloudFormation [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-transfer-user-sshpublickey.html) is admittedly a bit sparse. 

Through some experimentation through handwriting some json, I discovered that AWS is just expecting a list of RSA public key bodies for this field: 

"Type": "AWS::Transfer::User",
            "Properties": {
                "HomeDirectory": "test",
                "Policy": "test",
                "Role": "test",
                "ServerId": "test",
                "SshPublicKeys": [
                    "ssh-rsa AAAAB.....XR+8j4N4bW30DiPtOQLGUrH1y5X/rpNZNlWW2+jGIxqZtgWg7lTy3mXy5x836Sj/6L"
                ],
                "UserName": "boo"
            }

(I understand some of these dummy values won't pass regex validation when creating a stack. A full public key here did however.)

Any insight is much appreciated!

**Comment by markpeek** [comment]
This might be an issue with the interpretation of the resource specification. It has this property defined:
```
    "AWS::Transfer::User.SshPublicKey": {
      "PrimitiveType": "String"
    },
```
Usually there is not a property defined (in this case SshPublicKey) for a base primitive type. Based on your findings it is likely the change should be:
```
diff --git a/troposphere/transfer.py b/troposphere/transfer.py
index 67ce8da..3f837b4 100644
--- a/troposphere/transfer.py
+++ b/troposphere/transfer.py
@@ -38,11 +38,6 @@ class Server(AWSObject):
     }


-class SshPublicKey(AWSProperty):
-    props = {
-    }
-
-
 class User(AWSObject):
     resource_type = "AWS::Transfer::User"

@@ -51,7 +46,7 @@ class User(AWSObject):
         'Policy': (basestring, False),
         'Role': (basestring, True),
         'ServerId': (basestring, True),
-        'SshPublicKeys': ([SshPublicKey], False),
+        'SshPublicKeys': ([basestring], False),
         'Tags': (Tags, False),
         'UserName': (basestring, True),
     }
```
If you get a second please give this a try. Thanks.

**Comment by jt3po** [comment]
Thanks for the quick response! We'll look into this ASAP and get back to you.

**Comment by jt3po** [comment]
Looks like that worked @markpeek. Would you like us to put together a PR, or would you handle it?

**Comment by markpeek** [comment]
Thanks for the confirmation. I just pushed the change.

**Comment by jt3po** [comment]
Awesome thanks!

**Comment by jt3po** [comment]
@markpeek any idea when you might be cutting another release? Or how we can get this fix in an official build (release candidate, snapshot etc)?
