### ISSUE TITLE
ASK definition is incorrect

### ISSUE THREAD

**Issue by mansdahlstrom1** [cloudtools/troposphere#1466]
This file https://github.com/cloudtools/troposphere/blob/master/troposphere/ask.py does not align with the cloudformation documentation found here:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ask-skill.html#cfn-ask-skill-vendorid

**Comment by mansdahlstrom1** [comment]
This can be closed now that https://github.com/cloudtools/troposphere/pull/1467 is merged

**Comment by markpeek** [comment]
Thanks for corrections.
