### ISSUE TITLE
Join function and GetAtt returning a list of strings

### ISSUE THREAD

**Issue by isuftin** [cloudtools/troposphere#1469]
I need a bit of advice and am wondering if this is possible to do in Troposphere at this point.

My issue is I am trying to create a CloudFormation output resource for a `AWS::ElasticLoadBalancingV2::TargetGroup`. The output should be the load balancer ARNs. What I've done is

```
Join(
  ",", 
  [
    GetAtt("TargetGroup", "LoadBalancerArns")
  ]
)
```

What this gives me is:
```
{
    "Fn::Join": [
        ",",
        [
            {
                "Fn::GetAtt": [
                    "TargetGroup",
                    "LoadBalancerArns"
                ]
            }
        ]
    ]
}
```

The GetAtt function is inside of an array. What I get when trying to launch a CloudFormation stack ends up being the error: `An error occurred (ValidationError) when calling the CreateStack operation: Template error: 
   every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of 
   strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be
   joined.`

What I need is the GetAtt function outside of an array like:

```
{
    "Fn::Join": [
        ",",
            {
                "Fn::GetAtt": [
                    "TargetGroup",
                    "LoadBalancerArns"
                ]
            }
    ]
}
```

Thoughts?

**Comment by markpeek** [comment]
Since LoadBalancerArns returns a list of strings, have you tried:
```
Join(",", GetAtt("TargetGroup", "LoadBalancerArns"))
```

**Comment by isuftin** [comment]
@markpeek I thought I did try that but I guess I didn't 🤷‍♂ 

This solution does work for me, so thank you!
