### ISSUE TITLE
add PreTokenGeneration to cognito.LambdaConfig

### ISSUE THREAD

**Issue by BradMclain** [cloudtools/troposphere#1475]
Is now listed as a supported option in cloud formation docs
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-pretokengeneration

**Comment by markpeek** [comment]
Thanks! Added along with other new properties in UserPool and UserPoolClient.
