### ISSUE TITLE
EC2 LaunchTemplateData ImageId should not be required

### ISSUE THREAD

**Issue by nkrumm** [cloudtools/troposphere#1487]
The [AWS CloudFormation specification suggests](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html) this parameter is no longer required:

> ImageId
> The ID of the AMI.
> Required: No
> Type: String
> Update requires: No interruption

Relevant line in `troposphere/ec2.py`: https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py#L962

**Comment by markpeek** [comment]
Fixed. Thanks!
