### ISSUE TITLE
Add support for 3AZ elasticsearch

### ISSUE THREAD

**Issue by man7a** [cloudtools/troposphere#1492]
A troposphere mapping for ZoneAwarenessConfig seems to be missing. 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-zoneawarenessconfig.html

I believe this was a recently added feature as part of this announcement.
https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-elasticsearch-service-now-supports-three-availability-zone-deployments/

**Comment by PatMyron** [comment]
[Looks like support was added in this commit](https://github.com/cloudtools/troposphere/commit/692bde5702898fa303535d80a59f5bf956c6ca97)

https://github.com/cloudtools/troposphere/blob/fb41b29e06e2018dc1447a41bc2acb82e28ec133/troposphere/elasticsearch.py#L45-L60
