### ISSUE TITLE
IsOrganizationalTrail supported?

### ISSUE THREAD

**Issue by LewisYates** [cloudtools/troposphere#1505]
Hello. 

I get the following when trying to automated the creation of  an Organization Trail:

AttributeError: AWS::CloudTrail::Trail object does not support attribute IsOrganizationalTrail

Is this supported?
```
org_trail = t.add_resource(Trail(
    "OrganizationTrail",
    IsOrganizationalTrail=True,
```
Thanks!

**Comment by markpeek** [comment]
Not currently defined in the CloudFormation docs or resource spec files. Need to await implementation by the CF team.

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/45

**Comment by marinpurgar** [comment]
One can simply check by comparing the API documentation and CloudFormation documentation:

https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_CreateTrail.html#awscloudtrail-CreateTrail-request-IsOrganizationTrail
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html

@LewisYates BTW the property name (when it is implemented in CFN) will be `IsOrganizationTrail` not `IsOrganizationalTrail`.
