### ISSUE TITLE
Add support for AWS::Cognito::UserPoolIdentityProvider

### ISSUE THREAD

**Issue by crburke** [cloudtools/troposphere#1508]
Add a troposphere mapping for [AWS::Cognito::UserPoolIdentityProvider](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolidentityprovider.html).

**Comment by PatMyron** [comment]
[Looks like `AWS::Cognito::UserPoolIdentityProvider` got added in this commit](https://github.com/cloudtools/troposphere/commit/b0ec44a651d438b141c9fc2509c53377c9bfa956)

https://github.com/cloudtools/troposphere/blob/fb41b29e06e2018dc1447a41bc2acb82e28ec133/troposphere/cognito.py#L285-L295
