### ISSUE TITLE
module 'troposphere' has no attribute 'sagemaker'

### ISSUE THREAD

**Issue by HugoCornu** [cloudtools/troposphere#1519]
Hi, 

I tried this : 

`pip install troposphere`

```
import troposphere as tp 

t = tp.Template()

t.set_description("Example to show adding a Metadata section to the template")
t.add_metadata({
    "Comments": "Initial Draft",
    "LastUpdated": "Jan 1st 2015",
    "UpdatedBy": "First Last",
    "Version": "V1.0",
})
```
it works fine 

but 

when I add 

`tp.sagemaker.ContainerDefinition`

I get the error 

> module 'troposphere' has no attribute 'sagemaker'

`pip show troposphere`

> Name: troposphere
> Version: 2.5.2
> Summary: AWS CloudFormation creation library
> Home-page: https://github.com/cloudtools/troposphere
> Author: Mark Peek
> Author-email: mark@peek.org
> License: New BSD license
> Location: /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages
> Requires: cfn-flip
> Required-by:

Is it a bug or am I missing something ?

**Comment by HugoCornu** [comment]
It is definitely me missing something since it works with 

```
import troposphere as tp 
from troposphere import sagemaker
tp.sagemaker.ContainerDefinition
```

**Comment by markpeek** [comment]
Yes, your latest update is the intended way to import sagemaker. At the time of writing troposphere it seemed more natural to have explicit imports of each AWS service as opposed to pulling in all of the services into the troposphere namespace.

**Comment by HugoCornu** [comment]
Thanks for the info !
