### ISSUE TITLE
Add ca certificate identity to RDS

### ISSUE THREAD

**Issue by kirkhansen** [cloudtools/troposphere#1520]
AWS has announced that the CA cert will expire in 2020 forcing us to update our stacks. As far as I can tell, this option doesn't exist in the troposphere API.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

**Comment by garrettklatte** [comment]
+1

additional information can be found [here](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/211#issuecomment-570726064).

At the moment, the [DBInstance](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-cacertificateidentifier) documentation has not been updated to include the new property.

**Comment by PatMyron** [comment]
`CACertificateIdentifier` is now present in [CloudFormation Resource Specification Version 10.3.0](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json)
