### ISSUE TITLE
Volume module AvailabilityZone issue

### ISSUE THREAD

**Issue by tnielsen2** [cloudtools/troposphere#1528]
When attempting to create a volume for use in another resource, the Volume `AvailabilityZone` attribute does not accept a string. It will only accept the returned datatype/value of the `GetAtt` function. I am unable to use the GettAtt function due to some order of operations and would like to pass a string. 

Troposphere version is `2.5.2`.

Working code is below.
```
RestoredVolume = t.add_resource(ec2.Volume(
    "{}{}Ec2Instance{}RootVolume".format(lab_main.env_sl, app_group_ansi, nodeLabel),
    SnapshotId=snapshot_id,
    VolumeType='gp2',
    Encrypted=True,
    Tags=DefaultTags + Tags(Name="{}-root".format(lab_main.lab_env)),
    GetAtt(Ec2Instance, "AvailabilityZone"))
)
```

The function does not like the string type that I am passing, and I am unable to figure out why. 

```
RestoredVolume = t.add_resource(ec2.Volume(
    "{}{}Ec2Instance{}RootVolume".format(lab_main.env_sl, app_group_ansi, nodeLabel),
    SnapshotId=snapshot_id,
    VolumeType='gp2',
    Encrypted=True,
    Tags=DefaultTags + Tags(Name="{}-root".format(lab_main.lab_env)),
    AvailabilityZone='usw2-az1'
)
```

**Comment by markpeek** [comment]
I'm not sure how that first one is working since you're not assigning to a kwarg. Looking at the [code](https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py#L588), it should work fine with a string. Such as this example:
```
>>> import troposphere.ec2 as ec2
>>> ec2.Volume('RootVolume', AvailabilityZone='usw2-az1')
<troposphere.ec2.Volume object at 0x10a3af090>
```
 I suspect something else going on. Any chance to narrow a smaller test case to share along with the error you are receiving?

**Comment by tnielsen2** [comment]
Yeah, this is a syntax issue on my end. I apologize for wasting your time and appreciate your quick response. :facepalm:
