### ISSUE TITLE
Unit Test for TargetGroup Target Type seems to prevent using a parameter to specify the value

### ISSUE THREAD

**Issue by ronancunningham72** [cloudtools/troposphere#1539]
TargetGroup(AWSObject)

    def validate(self):
        one_of(self.__class__.__name__,
               self.properties,
               'TargetType',
               [
                   None,
                   TARGET_TYPE_INSTANCE,
                   TARGET_TYPE_IP,
                   TARGET_TYPE_LAMBDA
               ])

I have to hardcode the value of instance, ip, or lambda into my code. Any reason why this is forced particularly? I'd like to reuse the same template and in some environments I want a different target type.

**Comment by alexeyts** [comment]
Adding to the issue, you can also not use `Ref('AWS::NoValue')` which should clearly be possible, since this value is optional.
