### ISSUE TITLE
Unable to use CreationPolicy on supported types

### ISSUE THREAD

**Issue by llinder** [cloudtools/troposphere#154]
According to CFN documentation http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html the CreationPolicy attribute is supported on AutoScalingGroup, Instance and WaitCondition.  Currently none of these types include CreationPolicy in their attributes.

Additionally both CreationPolicy and UpdatePolicy currently inherit from BaseAWSObject but based on the AWS documentation they are intended to be used as attributes.  To make things work correctly I believe these should inherit from AWSProperty instead.

**Comment by phobologic** [comment]
Closing!
