### ISSUE TITLE
Add QueuedTimeoutInMinutes parameter to CodeBuild Project

### ISSUE THREAD

**Issue by matmertz25** [cloudtools/troposphere#1540]
**Description:** 
A QueuedTimeoutInMinutes parameter should be added to the CodeBuild Project Class. QueuedTimeoutInMinutes specifies the number of minutes a build is allowed to be queued before it times out. It is similar to TimeoutInMinutes but is for queued builds.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-queuedtimeoutinminutes

**Comment by PatMyron** [comment]
This has been in the [CloudFormation Resource Specifications](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) for a while. This should get updated next time the Resource Specifications are used to update resource types:

https://github.com/cloudtools/troposphere/blob/a28753d7532a5177b85ee0838de2f78bb128d6d0/troposphere/codebuild.py#L312-L334

**Comment by markpeek** [comment]
Added to Project. Thanks.
