### ISSUE TITLE
ECR image scanning feature

### ISSUE THREAD

**Issue by gionniboy** [cloudtools/troposphere#1544]
There is a way to add this feature in troposphere?
Or maybe is just there but i can't find it?
Thanks.

https://aws.amazon.com/about-aws/whats-new/2019/10/announcing-image-scanning-for-amazon-ecr/

**Comment by rtkmhart** [comment]
I don't see it in CloudFormation yet over at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html.

**Comment by gionniboy** [comment]
Right, sorry. my fault! I didn't check it.
Thanks for your reply :)

**Comment by PatMyron** [comment]
[CloudFormation roadmap issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/245)

**Comment by abhishekgetsb** [comment]
Is now a good time to revisit this? The property is now available in CF but not in Troposphere.

**Comment by markpeek** [comment]
Added. Thank you for the reminder.
