### ISSUE TITLE
Add support for AWS Global Accelerator

### ISSUE THREAD

**Issue by zdmytriv** [cloudtools/troposphere#1552]
Add support for AWS Global Accelerator

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/255

**Comment by ume-daniel** [comment]
Global Accelerator works with Cloudformation. https://aws.amazon.com/about-aws/whats-new/2020/05/aws-global-accelerator-supports-aws-cloudformation/
