### ISSUE TITLE
ForwardConfig not supported in ELBv2 while creating Listeners

### ISSUE THREAD

**Issue by yks0000** [cloudtools/troposphere#1554]
ALB (ELBv2) has started [supporting weighted target groups](https://aws.amazon.com/about-aws/whats-new/2019/11/application-load-balancer-simplifies-deployments-support-for-weighted-target-groups/)

More details https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#forward-actions

However, troposphere still not supporting it. Any plan to have it.

**Comment by yks0000** [comment]
Opened a PR for this. Please review https://github.com/cloudtools/troposphere/pull/1555

**Comment by PatMyron** [comment]
[another case of the CloudFormation Resource Specification lagging](https://github.com/aws-cloudformation/cfn-python-lint/issues/1251#issuecomment-565744604)

**Comment by aaronkvanmeerten** [comment]
I have tested #1555 from yks0000 and it works exactly as advertised.  The spec has also been updated so it'd be excellent to get this merged!

**Comment by markpeek** [comment]
This was fixed with #1555. Closing.
