### ISSUE TITLE
Add support for WeightedCapacity in AWS::AutoScaling::AutoScalingGroup (2020, Jan 16 update)

### ISSUE THREAD

**Issue by axelpavageau** [cloudtools/troposphere#1565]
waiting for documentation update

**Comment by PatMyron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-launchtemplateoverrides.html#cfn-autoscaling-autoscalinggroup-launchtemplateoverrides-weightedcapacity

https://github.com/cloudtools/troposphere/blob/0fd55530d6030c071749408d81be726cf2d329a0/troposphere/autoscaling.py#L145-L148

**Comment by markpeek** [comment]
Added per documentation. Thanks.
