### ISSUE TITLE
AutoScalingGroup LaunchConfigurationName requirement

### ISSUE THREAD

**Issue by dmccaffrey** [cloudtools/troposphere#158]
AWS::AutoScaling::AutoScalingGroup<sup>1</sup>  specifies that the LaunchConfigurationName and InstanceId fields are conditionally required (one must be present, and they are mutually exclusive) but the Troposphere class 'AutoScalingGroup' requires the LaunchConfigurationName parameter unconditionally. The result of this is that an autoscaling group requiring an InstanceId can not be provisioned through the 'AutoScalingGroup' class.

<sup>1</sup> (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-instanceid)

**Comment by mechastorm** [comment]
Just to put this out, but is there a workaround meanwhile until the proper fix gets merged in? It does stop us from using InstanceId property in the 'AutoScalingGroup' class. Thanks

**Comment by phobologic** [comment]
Hey guys - @markpeek & I both jumped on this and submitted fixes about 1 minute apart.  Anyway, we've merged our work into master.  I'm going to wait for #173 before releasing 0.7.1, but I hope that'll be dealt with ASAP.

**Comment by mechastorm** [comment]
Awesome - thanks!

**Comment by phobologic** [comment]
Just a heads up - I just pushed 0.7.1 to pypi, it should include this fix.  Let me know if you see any issues, and sorry for the delay!
