### ISSUE TITLE
Kinesis Analytics V2 Runtime validation is wrong

### ISSUE THREAD

**Issue by MacHu-GWU** [cloudtools/troposphere#1583]
please change `SQL-1.0` to `SQL-1_0`. 

Base on this official document https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisanalyticsv2-application.html#cfn-kinesisanalyticsv2-application-runtimeenvironment, it should be `SQL-1_0`

To fix it, you can just change this code https://github.com/cloudtools/troposphere/blob/master/troposphere/kinesisanalyticsv2.py#L10

**Comment by PatMyron** [comment]
```
1 validation error detected: Value 'SQL-1.0' at 'runtimeEnvironment' failed to satisfy constraint: Member must satisfy enum value set: [SQL-1_0, FLINK-1_6, FLINK-1_8] (Service: AmazonKinesisAnalyticsV2; Status Code: 400; Error Code: ValidationException; Request ID: REDACTED)
```
