### ISSUE TITLE
Adding MetadataOptions support for LaunchTemplateData

### ISSUE THREAD

**Issue by jochenhebbrecht** [cloudtools/troposphere#1590]
Hi,

Would it be possible to add the property `MetadataOptions` to the `LaunchTemplateData` class?

* CloudFormation source: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html
* Troposphere impacted code: https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py#L992

Reason why I would like to use it, is to increase the value of the property `HttpPutResponseHopLimit` using CloudFormation/troposphere.

Thanks!
Jochen

**Comment by markpeek** [comment]
Fixed via #1582

**Comment by jochenhebbrecht** [comment]
Thanks @markpeek ! Just perfect! :-)
