### ISSUE TITLE
wafv2.py IPSet - Error with Addresses property

### ISSUE THREAD

**Issue by johnsarg** [cloudtools/troposphere#1592]
First of all, thanks to everyone who maintains this repo - Troposphere is a Great tool!  

In the master branch, I came across a problem with wafv2.py when creating an IPSet.  It generates the Addresses property with the IPAddresses property which includes a list of CIDRs; however, it should produce only the list of CIDRs as values of Addresses (without IPAddresses).

Current (incorrect):
        Addresses:
          IPAddresses:
          - 1.2.3.0/24
          - 2.3.0.0/16

Correct:
        Addresses:
          - 1.2.3.0/24
          - 2.3.0.0/16

**Comment by axelpavageau** [comment]
Hi @johnsarg . To me the documentation contradicts itself. The example shows the Adresses property as a list of strings ( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-ipset.html#aws-resource-wafv2-ipset--examples) , but the object's description describes the IPAddresses property.

Have you had the chance to test the actual cloudformation behavior ?

**Comment by axelpavageau** [comment]
I just ran a quick test and the example works. I'll create a PR tomorrow to fix that.

**Comment by johnsarg** [comment]
Thanks @axelpavageau - that did the trick.  JS
