### ISSUE TITLE
Pre 3.0 release on the roadmap ?

### ISSUE THREAD

**Issue by gdelvalle** [cloudtools/troposphere#1593]
Given  the discussion  about a 3.0  release in #1558,  do you plan to have a pre 3.0 release version inline with your normal release schedule?

I only ask as we are eager to use a few enhancements you've added since your last release and we would prefer using an actual release versus using a commit directly from master.

Any info/guidance is greatly appreciated.

**Comment by markpeek** [comment]
My apologies, been slammed at work and in the middle of a house move. Yes, I need to get a 2.x release out with all the new changes so I'll get to merging over the weekend (thanks @axelpavageau for the PRs!) to get a release out before I move next week. Appreciate the reminder and again, apologies to the community for the delay.

**Comment by markpeek** [comment]
Just merged a bunch of changes and [Release 2.6.0](https://github.com/cloudtools/troposphere/releases/tag/2.6.0) is now available.
