### ISSUE TITLE
Properties of type: list of functions (validators), fails to validate

### ISSUE THREAD

**Issue by HendJordan** [cloudtools/troposphere#1673]
Specifically, I'm trying to use the cloudfront.StatusCodes class. 
However, the Items property won't validate properly.

```
 class StatusCodes(AWSProperty):
    props = {
        'Items': ([integer], True),
        'Quantity': (integer, True),
    }
```

Digging into the code, it appears the issue is that once it's determined the expected value is a list, then each value in the list is expected to be a type; which fails because integer is a function, not a type.

```
            # If it's a list of types, check against those types...
            elif isinstance(expected_type, list):
                # If we're expecting a list, then make sure it is a list
                if not isinstance(value, list):
                    self._raise_type(name, value, expected_type)

                # Iterate over the list and make sure it matches our
                # type checks (as above accept AWSHelperFn because
                # we can't do the validation ourselves)
                for v in value:
                    if not isinstance(v, tuple(expected_type)) \
                       and not isinstance(v, AWSHelperFn):
                        self._raise_type(name, v, expected_type)
                # Validated so assign it
                return self.properties.__setitem__(name, value)

```

Relevant part of stack trace:
```
  File /usr/local/lib/python3.7/site-packages/troposphere/__init__.py, line 354, in __init__
    super(AWSProperty, self).__init__(title, **kwargs)
  File /usr/local/lib/python3.7/site-packages/troposphere/__init__.py, line 127, in __init__
    self.__setattr__(k, v)
  File /usr/local/lib/python3.7/site-packages/troposphere/__init__.py, line 202, in __setattr__
    if not isinstance(v, tuple(expected_type)) \
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by HendJordan** [comment]
I would be happy to submit a PR myself if granted access.

**Comment by arnaudgay-cr** [comment]
I have the same issue, and was not able to make it work for now.
The same pb should be also meet in appmesh with ClientPolicyTls.
Both are defined as  :   ([integer],

**Comment by markpeek** [comment]
This is a good issue. Let me see about working up a fix and adding the tests to prevent regressions.

**Comment by markpeek** [comment]
Let me know if [this patch](https://github.com/cloudtools/troposphere/commit/55a9c4fd970f07b77a333505c6bc6abde7132b6e) fixes the issue.

**Comment by arnaudgay-cr** [comment]
Hi Mark,
It looks OK at first sight as I am able to set the variable. 
But the to_dict() function output a map() that I cannot serialize (for instance with json.dumps)

`from troposphere.cloudfront import StatusCodes`
`a = StatusCodes(Quantity=1, Items=[11])`
Great it works !!!
`a.to_dict()`
`{'Quantity': 1, 'Items': <map object at 0x101737278>}`
I cannot serialize the map object
`import json`
`json.dumps(a.to_dict())`
Failed
`from troposphere.cloudfront import TrustedSigners`
`b = TrustedSigners(AwsAccountNumbers = ["toto", "titi"], Enabled=True)`
`b.to_dict()`
`{'AwsAccountNumbers': ['toto', 'titi'], 'Enabled': 'true'}`
to_dict() works with a list of basestr
`json.dumps(b.to_dict())`
`'{"AwsAccountNumbers": ["toto", "titi"], "Enabled": "true"}'`

**Comment by markpeek** [comment]
Ahhh...you're using python3 and that patch is to python2. When troposphere is installed for python3 it will run 2to3 which puts a list() call around the map() and converts the iterator into a list. From the patch, use this instead (and it will work once I release a new version):
```
...
      new_value = list(map(expected_type[0], value))
...
```

**Comment by arnaudgay-cr** [comment]
The proposed fix worked for me. Brilliant Mark. 👍 
Thanks

**Comment by markpeek** [comment]
Excellent, thank you for validating the fix. It's now pushed onto master.
