### ISSUE TITLE
AWS::ImageBuilder::* some wrong data types and attribut missing

### ISSUE THREAD

**Issue by arnaudgay-cr** [cloudtools/troposphere#1700]
In imagebuilder.py (2.6.1 release).

* In AWS::ImageBuilder::*
"Tags" are "json_checker" but should be dict
When encoded in the structure it becomes a string (validator.py, ligne 258,` json.dumps(prop)`) which is creating an issue with CloudFormation that expect a struct like : `"Tags" : {Key : Value, ...}`
* AWS::ImageBuilder::DistributionConfiguration::Distribution
"AmiDistributionConfiguration" is "json_checker" but should be dict.
For the same as above "Tags" 
* In AWS::ImageBuilder::Component
"Data" is missing. And should be "json_checker" in that case.
* In AWS::ImageBuilder::ImageRecipe::InstanceBlockDeviceMapping
"NoDevice" is boolean but should be a string

**Comment by axelpavageau** [comment]
Hello,

I've implemented the fixes, with one exception : I believe `AWS::ImageBuilder::Component` Data should be a string, not a json_checker

**Comment by arnaudgay-cr** [comment]
Hi @axelpavageau,

Many thanks for the update.
Regarding `AWS::ImageBuilder::Component Data`, 
Agreed to say that internal storage is a string. But I think that json_checker (in that case) is a better choice because : 
* if input is a string -> verify that string is a valid json string
* if input is a dict -> convert the dict to a basestring

So in any case the output is a string.
And there is a "pre-check" in the json structure.

Thanks and regards.

```
def json_checker(prop):
    from . import AWSHelperFn

    if isinstance(prop, str):
        # Verify it is a valid json string
        json.loads(prop)
        return prop
    elif isinstance(prop, dict):
        # Convert the dict to a basestring
        return json.dumps(prop)
    elif isinstance(prop, AWSHelperFn):
        return prop
    else:
        raise ValueError("json object must be a str or dict")


```
