### ISSUE TITLE
Support for EFS in ECS fargate and EC2

### ISSUE THREAD

**Issue by matdrapeau** [cloudtools/troposphere#1710]
Since April 8, fargate now supports ECS
https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/

Is it planned to be integrated?

**Comment by techman83** [comment]
It's not supported in CloudFormation yet, so that might be difficult. See -> aws/containers-roadmap#825

**Comment by jeffcarrico** [comment]
FYI - it is now

**Comment by JohnPreston** [comment]
i created a PR for this already

**Comment by JohnPreston** [comment]
I would imagine this is good to be closed @markpeek
