### ISSUE TITLE
Add support for AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by jeffcarrico** [cloudtools/troposphere#1714]
Here's the (very recent) announcement
https://aws.amazon.com/about-aws/whats-new/2020/05/aws-sam-adds-support-for-aws-step-functions/

And the resource documentation
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html

**Comment by PatMyron** [comment]
merging into https://github.com/cloudtools/troposphere/issues/617#issuecomment-576064669
