### ISSUE TITLE
SageMaker Model PrimaryContainer Definition Required

### ISSUE THREAD

**Issue by mneil** [cloudtools/troposphere#1729]
According to the cloudformation docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-model.html#cfn-sagemaker-model-primarycontainer the "PrimaryContainer" attribute is not required.

However, troposphere is marking it as required. https://github.com/cloudtools/troposphere/blob/master/troposphere/sagemaker.py#L79

I'm unable to launch a stack without a container definition.

I can open up a PR to resolve this but I know a lot of the code is autogenerated. I was going to simply flip True to False in the Model definition. I can do that if it's the correct location to change the requirements for the future. Otherwise, I'll hold off.

Thanks!

**Comment by markpeek** [comment]
Pushed a quick fix for this one. Thanks!
