### ISSUE TITLE
Support ErrorOutputPrefix on AWS::KinesisFirehose::DeliveryStream.S3DestinationConfiguration

### ISSUE THREAD

**Issue by grvhi** [cloudtools/troposphere#1742]
Per AWS documentation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-s3destinationconfiguration.html#cfn-kinesisfirehose-deliverystream-s3destinationconfiguration-erroroutputprefix

**Comment by PatMyron** [comment]
Added a year ago: https://github.com/cloudtools/troposphere/pull/1439

Upgrading should pick this up:

`pip install troposphere --upgrade`
