### ISSUE TITLE
Use dynamically generated strings for AWS Resource Titles

### ISSUE THREAD

**Issue by dvpatel-git** [cloudtools/troposphere#1756]
We use troposphere/boto3 to author our templates. For our Aurora template, we support a primary and up-to 2 additional replicas along with alarms. When you add a resource to the template, the resource title needs to be unique. Since we add 3 identical alarms, we need 3 functions today because the title string cannot be dynamically generated and needs to be a static string. We support 11 alarms and 3 instances. So there are 43 functions to support all the alarms. If the troposphere validator did not look only for static strings and supported names which were dynamically generated, we could reduce our code to a 5th of its current state.

Current Sample code:
    cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
            "CPUUsageAlertAlarm",

Future Sample code:
    alarmTitle=Join("",[Ref(db_name),"CPUUsageAlertAlarm"])
    cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
            alarmTitle,

Is this possible to enhance? If not, is there a better way to use a dynamically generated string as a title for cloudwatch Alarms and other resources?

**Comment by markpeek** [comment]
I'm guessing you really just need more static strings for title and you want to use the Join for specifying the AlarmName.

**Comment by dvpatel-git** [comment]
It is the other way around Mark. We do generate the AlarmName with joins just fine. But the static title string is what is tripping the validations. We need to generate the alarm title string dynamically and let the validations pass. I can post the full function code tomorrow as I can't VPN to my work computer from my personal laptop.

**Comment by ronancunningham72** [comment]
Not sure If fully understand the issue but would have thought the CloudFormation Logical resource and variable to add it to the template need to be unique in order to use Ref or GetAtt elsewhere in a template?
Can you not reduce your code iterating over a range or a map?

**Comment by dvpatel-git** [comment]
Here is one function.
==================
def setCPUAlarmAlertResource(template, db_name):

    cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
            "CPUUsageAlertAlarm",
            AlarmDescription=Join("", ["%c", Ref("AlarmCustomer"), "c%%s",alert_level,"s%%dDd%%m", Ref("AWSAccountName"), "|", Ref(db_name), " | CPU Utilization Alarm 85% for 20 minutes.m%"]),
            AlarmActions=[Join("", ["arn:aws:sns:", Ref("AWS::Region"), ":", Ref("AWS::AccountId"), ":CloudOpsSns"])],
            MetricName="CPUUtilization",
            Namespace="AWS/RDS",
            Statistic="Average",
            Period="300",
            EvaluationPeriods="4",
            Threshold="85",
            ComparisonOperator="GreaterThanOrEqualToThreshold",
            Dimensions=[cloudwatch.MetricDimension(Name="DBInstanceIdentifier", Value=Ref(db_name))]
    ))

    return cpu_alarm_critical
==================

For Aurora, we have to have 3 more functions for the same thing as our naming convention for Aurora has p for Primary and r00 and r01 for each one of the replicas in the db_name.

==================
def setAuroraCPUAlarmAlertResource(template, db_name):

    aurora_cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
            "CPUUsageAlertAlarm",
            AlarmDescription=Join("", ["%c", Ref("AlarmCustomer"), "c%%s",alert_level,"s%%dDd%%m", Ref("AWSAccountName"), "|", Ref(db_name),"p", " | CPU Utilization Alarm 85% for 20 minutes.m%"]),
            AlarmActions=[Join("", ["arn:aws:sns:", Ref("AWS::Region"), ":", Ref("AWS::AccountId"), ":OpsSns"])],
            MetricName="CPUUtilization",
            Namespace="AWS/RDS",
            Statistic="Average",
            Period="300",
            EvaluationPeriods="4",
            Threshold="85",
            ComparisonOperator="GreaterThanOrEqualToThreshold",
            Dimensions=[cloudwatch.MetricDimension(Name="DBInstanceIdentifier", Value=Join("",[Ref(db_name),"p"]))]
    ))

    return aurora_cpu_alarm_critical
==================
==================
def setAuroraReplica1CPUAlertResource(template, db_name):

    aurora_replica1_cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
            "AuroraReplica1CPUUsageAlertAlarm",
            AlarmDescription=Join("", ["%c", Ref("AlarmCustomer"), "c%%s",alert_level,"s%%dDd%%m", Ref("AWSAccountName"), "|", Ref(db_name),"r00", " | CPU Utilization Alarm 85% for 20 minutes.m%"]),
            AlarmActions=[Join("", ["arn:aws:sns:", Ref("AWS::Region"), ":", Ref("AWS::AccountId"), ":OpsSns"])],
            MetricName="CPUUtilization",
            Namespace="AWS/RDS",
            Statistic="Average",
            Period="300",
            EvaluationPeriods="4",
            Threshold="85",
            ComparisonOperator="GreaterThanOrEqualToThreshold",
            Dimensions=[cloudwatch.MetricDimension(Name="DBInstanceIdentifier", Value=Join("",[Ref(db_name),"r00"]))]
    ))

    return aurora_replica1_cpu_alarm_critical
==================

We have 11 such monitors we use. For each monitor just due to the static text requirement, we cannot chang ethe code and pass in the correct db_name (regular for RDS, db_name+p for primary, db_name+r00 for replica1 so on and so forth).

Thank you for your assistance.

**Comment by dvpatel-git** [comment]
> Not sure If fully understand the issue but would have thought the CloudFormation Logical resource and variable to add it to the template need to be unique in order to use Ref or GetAtt elsewhere in a template?
> Can you not reduce your code iterating over a range or a map?

That is what we're trying to do but you cannot parameterize or dynamically generate the text of the "title" in BOLD above in my additional code reply above.

**Comment by ronancunningham72** [comment]
Are you referring to the Cloudformation Logical Id?

**Comment by dvpatel-git** [comment]
> Are you referring to the Cloudformation Logical Id?
> 
> Where "AuroraReplica1CPUUsageAlertAlarm" is the Logical Id:
> 
> aurora_replica1_cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
> "AuroraReplica1CPUUsageAlertAlarm",

Yes. Apparently, its called a title. We get a failure for validation for Title if I try to change that.

**Comment by dvpatel-git** [comment]
If we change the Logical Id (aka title) like so:
    alarmTitle=Join("",[Ref(db_name),"CPUUsageAlertAlarm"])
    cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
            alarmTitle,


I get the error:
Traceback (most recent call last):
  File "rds_postgres.py", line 105, in <module>
    cpu_usage_alert = rds_common.setCPUAlarmAlertResource(template, db_name,sys_level)
  File "C:\projects\XXX\troposphere\rds_common.py", line 846, in setCPUAlarmAlertResource
    Dimensions=[cloudwatch.MetricDimension(Name="DBInstanceIdentifier", Value=Ref(db_name))]
  File "C:\Program Files\Python37\lib\site-packages\troposphere\__init__.py", line 104, in __init__
    self.validate_title()
  File "C:\Program Files\Python37\lib\site-packages\troposphere\__init__.py", line 235, in validate_title
    if not valid_names.match(self.title):
TypeError: expected string or bytes-like object

**Comment by JohnPreston** [comment]
I think the problem is you are trying to assign your Join() to the Logical Resource Title, as opposed to the AlarmName property.
For the logical resource title, you have to give it a name using a string and characters matching `^[a-zA-Z0-9]+$`
I do that all the time in [my program ](https://github.com/lambda-my-aws/ecs_composex) where I generate the title of the resources (LogicalName).

Using your snippet:
```
alarmTitle=Join("",[Ref(db_name),"CPUUsageAlertAlarm"])
cpu_alarm_critical = template.add_resource(cloudwatch.Alarm(
title="CpuUsageAlertAlaram",
AlarmName=alarmTitle,
```
If you wanted a LogicalResource title to follow what you have in the ref,
`alaram_logical_title = f"{db_name.title}CPUUsageAlertAlarm"` 
(assuming db_name is either a troposphere.AWSObject resource or troposphere.Parameter)
Hope this helps,

**Comment by dvpatel-git** [comment]
Thank you. That does indeed help. db_name is a parameter indeed. I will try this a little later today.

**Comment by dvpatel-git** [comment]
Just reporting back. I was able to make this work with a tweak. Since the db_name.title is what the actual parameter name is, not the value, I was still getting the same logical names. I changed it a bit to pass in a string and use that to generate different logical names and it all works now. If there is a way to get the value (tried various things and the docs without luck), please post and I can change my code. Thank you for all the responses so far.
