### ISSUE TITLE
missing required property doesn't produce error

### ISSUE THREAD

**Issue by timurb** [cloudtools/troposphere#1763]
I took an example of error checking from docs from here (https://github.com/cloudtools/troposphere#examples-of-the-error-checking-full-tracebacks-removed-for-clarity) and the one that is supposed to fail on missing required parameter doesn't seem to work (that is doesn't fail with exception). I copied the code from the main README.md:
```
$ cat tropotest2.py
from troposphere import Template
import troposphere.ec2 as ec2
t = Template()
t.add_resource(ec2.Instance("ec2instance", InstanceType="m3.medium"))
print(t.to_yaml())

$ python tropotest2.py
Resources:
  ec2instance:
    Properties:
      InstanceType: m3.medium
    Type: AWS::EC2::Instance

$ pip freeze | grep tropo
troposphere==2.6.2
```

All other described cases (incorrect property and incorrect type) seem to work fine, that is they fail with error as expected.

**Comment by markpeek** [comment]
Thanks for the issue. I've updated with a new example that shows the error.
