### ISSUE TITLE
troposphere.docdb.DBCluster has no "Deletion Protection" parameter

### ISSUE THREAD

**Issue by sergiolopgeh** [cloudtools/troposphere#1771]
The AWS Cloudformation Documentation has the "Deletion Protection" attribute that is not present in the troposphere Module. Is this by design?

**Comment by PatMyron** [comment]
merged this week: https://github.com/cloudtools/troposphere/pull/1748 but hasn't been released to PyPI yet

release cadence discussion: https://github.com/cloudtools/troposphere/issues/816
