### ISSUE TITLE
Support for Globals Section in SAM Templates

### ISSUE THREAD

**Issue by omijh** [cloudtools/troposphere#1787]
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html 

Globals Section from SAM template anatomy is missing in the troposphere.
we need this feature in order to update OpenApiVersion Version & Function timeout for all serverless functions in the template

**Comment by markpeek** [comment]
Fixed via f5851870b26a6eef3f0a6beb0bef1db2deb705e8
