### ISSUE TITLE
CloudFormation rejects AWS::ECR::Repository.ImageScanningConfiguration

### ISSUE THREAD

**Issue by sterwill** [cloudtools/troposphere#1791]
I was happy to see support for [`AWS::ECR::Repository.ImageScanningConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagescanningconfiguration) get committed, but CloudFormation rejects my Repository resource with this error:

    Model validation failed (#/ImageScanningConfiguration: expected type: JSONObject, found: String)

It looks like `json_checker` is converting my Python dict to a JSON string unconditionally, which CloudFormation won't take.

**Comment by markpeek** [comment]
Thank you for the issue.

**Comment by tobiasmcnulty** [comment]
For the next person who finds this and wonders how this should be set:

```
repository = Repository(
    "Repo",
    # ...
    ImageScanningConfiguration={"ScanOnPush": "true"},
)
```

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagescanningconfiguration
