### ISSUE TITLE
Support for Cross Region COPY - DLM

### ISSUE THREAD

**Issue by SrikanthATR** [cloudtools/troposphere#1799]
https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-data-lifecycle-manager-enables-automation-snapshot-copy-via-policies/

**Comment by PatMyron** [comment]
https://github.com/cloudtools/troposphere/blob/0607f3f5bfb75635ee9e2e5cbbaee5ab0d8d639c/troposphere/dlm.py#L62-L69
[`AWS::DLM::LifecyclePolicy`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dlm-lifecyclepolicy.html)
[`AWS::DLM::LifecyclePolicy.Schedule`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dlm-lifecyclepolicy-schedule.html)

**Comment by markpeek** [comment]
Thanks for the issue.
