### ISSUE TITLE
Duplicate elasticache.NodeGroupConfiguration definition causing type check failure

### ISSUE THREAD

**Issue by jjpestacio** [cloudtools/troposphere#1803]
There are two class definitions for `NodeGroupConfiguration`:
https://github.com/cloudtools/troposphere/blob/master/troposphere/elasticache.py#L101
https://github.com/cloudtools/troposphere/blob/master/troposphere/elasticache.py#L162

This causes a type check failure when creating a `ReplicationGroup` with a `NodeGroupConfiguration`:
```
TypeError: <class 'troposphere.elasticache.ReplicationGroup'>: replicationgroupredisclustertest2.NodeGroupConfiguration is <class 'troposphere.elasticache.NodeGroupConfiguration'>, expected [<class 'troposphere.elasticache.NodeGroupConfiguration'>]
```

When importing `NodeGroupConfiguration`, the latter class is used but during validation for `ReplicationGroup` the former class is used. 

The resolution is to remove one of the `NodeGroupConfiguration` class definitions. Note that there is a difference between the types of `NodeGroupId` in the class definitions.

**Comment by markpeek** [comment]
Thank you @jjpestacio. Just pushed a fix if you want to test it.
