### ISSUE TITLE
validators.ecs_efs_encryption_status() method is incomplete

### ISSUE THREAD

**Issue by avosper-intellaegis** [cloudtools/troposphere#1807]
validatorys.ecs_efs_encryption_status needs the value specified in the formatted string passed to the ValueError.

It also needs to return the checked 'status' variable in order to avoid null values being sent when creating an efs.EFSVolumeConfiguration object in a CreateChangeSet operation with CloudFormation.

**Comment by markpeek** [comment]
Thanks for the issues and fixes.
