### ISSUE TITLE
DSL for building stacks off other stacks

### ISSUE THREAD

**Issue by robzienert** [cloudtools/troposphere#182]
Would you guys be interested in a CLI script that would be capable of populating template parameters based on other templates? At my company, we've got a ton of CFN templates (and growing) for a single environment / DC. Needless to say, it can be a little bit of a mindless time suck to stand up a new environment or DC.

I've looked around at tools like [cumulus](https://github.com/cotdsa/cumulus) but don't enjoy that it's neither well-tested, nor plays well with partial "super stack" updates. I'm thinking it could be worthwhile to build something similar, but with an interface more in nature of Troposphere.

I was going to build this as a separate project, but since I'm already using Troposphere heavily, I figured maybe it could live under one roof.

Thoughts? If this is too much scope increase, I'd still be interested in your feedback on the idea itself.

**Comment by markpeek** [comment]
I think it is a good idea and helps ease the complexity (and, as you accurately portrayed, mindless time suck) that can arise with these environments. We haven't had to deal with as many templates in our environments as you have but I definitely see the need to partition and then aggregate sub-stacks. We'd have to see if it makes sense inside of troposphere or even you could host it as another project (stratosphere? :-) ) in cloudtools.

**Comment by robzienert** [comment]
Ha! I was also thinking stratosphere would be a good name for it. Anyway, I'll work on whipping something up over the coming weeks and we'll see where things land. :)
