### ISSUE TITLE
Support AmazonMQ RabbitMQ

### ISSUE THREAD

**Issue by abhishekgetsb** [cloudtools/troposphere#1827]
AmazonMQ now supports RabbitMQ brokers. Just wanted to know if troposphere automatically supports this or it requires changes. It'll be great to add if it's the latter situation.
Refer: https://aws.amazon.com/blogs/aws/amazon-mq-update-new-rabbitmq-message-broker-service/

**Comment by markpeek** [comment]
At this time I don't see that CloudFormation supports RabbitMQ which means troposphere doesn't as well. Will look to see if there are updates today/tomorrow to the spec files/documentation in case updates rollout support for RabbitMQ.

**Comment by abhishekgetsb** [comment]
@markpeek Where do you usually check for these updates? I do see mentions of RabbitMQ in the CloudFormation documentation [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-broker.html).

**Comment by markpeek** [comment]
Interesting. I look at the release history [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) to see what is updated. You might want to try using an EngineType of RabbitMQ to see if that works for you.
