### ISSUE TITLE
AWS Lambda Has Increased Memory Limits

### ISSUE THREAD

**Issue by ewascent** [cloudtools/troposphere#1843]
AWS has announced a new memory limit for AWS Lambda. The Limit is now 10240 MB. 

Line 5 of troposphere/awslambda.py:
https://github.com/cloudtools/troposphere/blob/900757ba97ae3f837cb43f0568590ebbf9ddcebf/troposphere/awslambda.py#L5
could be changed to something like this.

```
MINIMUM_MEMORY = 128
MAXIMUM_MEMORY = 10240
MEMORY_INCREMENT = 64
MEMORY_VALUES = [x for x in range(MINIMUM_MEMORY, MAXIMUM_MEMORY + MEMORY_INCREMENT, MEMORY_INCREMENT)]
```

Console view of new limits (not listed in AWS docs yet).
![Screen Shot 2020-12-03 at 9 44 41 AM](https://user-images.githubusercontent.com/1467662/101080171-4b826700-355d-11eb-8118-95203abe788c.png)

**Comment by markpeek** [comment]
This was release in 2.6.4.
