### ISSUE TITLE
Support MWAA::Environment resource

### ISSUE THREAD

**Issue by ghost** [cloudtools/troposphere#1855]
The AWS::MWAA::Environment resource creates an Amazon MWAA environment with Apache Airflow.  Troposphere doesn't appear to support yet?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html

**Comment by adam133** [comment]
Came here looking to note this issue as well. It's going to slow me down a bit on a project I'm working on.

**Comment by adam133** [comment]
I created a PR for it... My first time contributing here so I'm not 100% sure it's correct, but hopefully speeds up the process for getting support for it.
https://github.com/cloudtools/troposphere/pull/1858/commits/eb61cf59130e4134a947e6466fea870691e3f437

**Comment by markpeek** [comment]
Fixed via above PR.
