### ISSUE TITLE
How to access a Parameter for use in Userdata

### ISSUE THREAD

**Issue by shaunster666** [cloudtools/troposphere#1860]
Hi,

I am a complete newby with Troposphere, and would greatly appreciate your help.

environment = t.add_parameter(Parameter(
    "environment",
    Default="dev",
    ConstraintDescription="Is this going to be in dev, qa or production env?",
    Type="String",
    Description="Environment",
    AllowedValues=["qa", "dev", "prod"],
))

I need to access this in user data but I don't understand how to reference it correctly.

USER_DATA = """
#!/bin/bash
export env=%s
mount /efs$env
"""

def generate_userdata(environment):
    return USER_DATA % (environment)

launch_config = t.add_resource(LaunchConfiguration(
    "EFSLaunchConfiguration",
    ...
     UserData = Base64(generate_userdata(Ref(environment)))
))

Any help would be much appreciated

Shaun

**Comment by markpeek** [comment]
The troposphere python code is run locally to generate the CF template. As such, no python code is run by CF. The examples included with troposphere have a few examples (such as this [one](https://github.com/cloudtools/troposphere/blob/master/examples/Autoscaling.py#L168)) on how to pass variable data into userdata using "join" and "Ref".

**Comment by shaunster666** [comment]
Many thanks, however I realise no python code is run by CF.

In the snippet I have given all I want to do pass the Parameter 'environment' to my docstring so that I can use it in UserData

At the moment I end up with

<troposphere.Ref object at 0x10f4e7130> instead of "dev"

Thanks again

Shaun

**Comment by shaunster666** [comment]
.
