### ISSUE TITLE
Add S3 bucket replication features per 2020-11 changes

### ISSUE THREAD

**Issue by rtkhklepsch** [cloudtools/troposphere#1865]
- Delete marker replication configuration
    - https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-replication-adds-support-for-replicating-delete-markers/
- Replication time control configuration
    - https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-s3-replication-time-control-for-predictable-replication-time-backed-by-sla/
- Metrics/notification configuration for replication progress monitoring
    - https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-replication-adds-support-for-metrics-and-notifications/

**Comment by markpeek** [comment]
Closing as this was likely fixed via 0f7a59c1f329e993c4d9d6aed6905265ca091ff2. Thanks.
