### ISSUE TITLE
AppConfig support for HostedConfigurationVersion

### ISSUE THREAD

**Issue by NikBharrat** [cloudtools/troposphere#1868]
AppConfig should be updated with the HostedConfigurationVersion resource. See more here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-hostedconfigurationversion.html

PR created here: https://github.com/cloudtools/troposphere/pull/1870

The code to be added to AppConfig.py would look something like this:

```
class HostedConfigurationVersion(AWSObject):
    resource_type = "AWS::AppConfig::HostedConfigurationVersion"

    props = {
        'ApplicationId': (basestring, True),
        'ConfigurationProfileId': (basestring, True),
        'Content': (basestring, True),
        'ContentType': (basestring, True),
        'Description': (basestring, False),
        'LatestVersionNumber': (double, False),
    }

**Comment by markpeek** [comment]
Fixed via #1870. Thanks!
