### ISSUE TITLE
Security Group ports required

### ISSUE THREAD

**Issue by msirull** [cloudtools/troposphere#187]
Right now, it looks like the To/From ports are being required in the security group, but this shouldn't be the case if IpProtocol is "-1" (all traffic)

**Comment by k-ong** [comment]
@msirull I think AWS requires ToPort and FromPort to be specified when doing SecurityGroups, even if it's for all ports (-1). 

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html

**Comment by phobologic** [comment]
Thanks @k-ong - yeah, I just ran into this myself. It seems like CloudFormation, at least from the documentation, requires you to include the ports.

If the documentation doesn't match reality, let us know @msirull.  Going to go ahead and close this for now.
