### ISSUE TITLE
How to update the SSL negotiation policy in using the Troposhpere framework for an AWS classic load balancer 443 listener

### ISSUE THREAD

**Issue by ernievd** [cloudtools/troposphere#1872]
Can someone help me figure this out? I can not find any working examples of it.

Here is a link to where I have more details and the code I created :

https://stackoverflow.com/questions/66376888/how-to-update-the-ssl-negotiation-policy-in-using-the-troposhpere-framework-for

**Comment by marinpurgar** [comment]
The Classic Load Balancer Policies should be specified under the Policies property, not the Listeners property. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-policies

Remove the `elb.Policy( ... )` from the `Listerners=[ ...]` property and add the `Policies = [ elb.Policy( ... ), ... ]` property to the LoadBlacncer resource / object.

**Comment by marinpurgar** [comment]
We should add the validator making sure that the `Listeners` property is a list of `loadbalancing.Listener` object.

**Comment by ernievd** [comment]
That was it. Thanks so much!! 
I love Troposphere and hope that it catches on more. 
It seems superior to Terraform for me!
