### ISSUE TITLE
Release & Publish 2.6.4

### ISSUE THREAD

**Issue by JohnPreston** [cloudtools/troposphere#1876]
Hello @markpeek @PatMyron 
Any updates on when we can get 2.6.4 release in pypi ? Seems like a number of projects are waiting for that release to make their own.
Given this is a patch release (unless 2.7.0 or 3.0 is more imminent) can we get this out sooner than later?
Many thanks!

**Comment by markpeek** [comment]
Thanks @JohnPreston for the ping. How does this sound for a plan?
- Release what is there later today as a 2.6.4.
- Get caught up with pending updates and get a 2.7 released (final Python 2.x release).
- Then switch the code to Python 3.x only for a 3.0.0 release.

**Comment by JohnPreston** [comment]
Thanks @markpeek for the prompt feedback. Looking forward to it :rocket:

**Comment by markpeek** [comment]
[Released 2.6.4](https://github.com/cloudtools/troposphere/releases/tag/2.6.4) just now.

**Comment by JohnPreston** [comment]
Woohoo. Thanks @markpeek
