### ISSUE TITLE
Typo on DeploymentCircuitBreaker property

### ISSUE THREAD

**Issue by RebecaAlencar** [cloudtools/troposphere#1877]
Hello, there is a typo on esc.py line 105 for [DeploymentCircuitBreaker ](https://github.com/cloudtools/troposphere/blob/0f882d37142fff6fbd5d24c2ed83782b5910593b/troposphere/ecs.py#L105)definition.
Roll**B**ack should be Roll**b**ack.

See more: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentcircuitbreaker.html#cfn-ecs-service-deploymentcircuitbreaker-rollback

Error message from Cloudformation:
_#/DeploymentConfiguration/DeploymentCircuitBreaker: required key [Rollback] not found_

**Comment by markpeek** [comment]
Thank you for the issue. Fixed per above commit.
