### ISSUE TITLE
Support Fargate compute environment in AWS Batch

### ISSUE THREAD

**Issue by abhishekgetsb** [cloudtools/troposphere#1880]
AWS added support for this late last year: https://aws.amazon.com/blogs/aws/new-fully-serverless-batch-computing-with-aws-batch-support-for-aws-fargate/

However when setting the `Type` to `FARGATE` in `ComputeResources`, we get an error that mandates unsupported options such as `MinvCpus`, `MaxvCpus`, `InstanceRole`, etc. because CloudFormation [advises against the use of those options](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html) for Fargate type Compute Environments.

Sample errors when not mentioning the aforesaid unnecessary options:
`failed (Resource MaxvCpus required in type <unknown type> (title: BatchComputeResources))`
`failed (Resource InstanceRole required in type <unknown type> (title: BatchComputeResources))`
`failed (Resource InstanceTypes required in type <unknown type> (title: BatchComputeResources))`

**Comment by markpeek** [comment]
The resource has been updated with the above commit to reflect some of the properties being not required. Note: MaxvCpus is required according to the documentation.
