### ISSUE TITLE
AWS::DynamoDB::Table object does not support attribute ContributorInsightsSpecification

### ISSUE THREAD

**Issue by austin-engle** [cloudtools/troposphere#1883]
Getting the following error when trying to add to dynamodb

Code:
```
from troposphere import dynamodb
table = dynamodb.Table(clean_table_name)
table.ContributorInsightsSpecification = dynamodb.ContributorInsightsSpecification(Enabled=True)
```

also tried 
```
from troposphere import dynamodb
table = dynamodb.Table(clean_table_name)
table.ContributorInsightsSpecification = ContributorInsightsSpecification(Enabled=True)
```

When looking in DynamoDB I don't see any examples using this but I do see the class.

**Comment by markpeek** [comment]
@austin-engle there wasn't an error specified in your Issue above so it is unclear what is not working.

Here is how I'd implement using ContributorInsightsSpecification in an example which includes some required fields:

``` python
from troposphere import Template
from troposphere import dynamodb
from troposphere.dynamodb import Table, AttributeDefinition
from troposphere.dynamodb import ContributorInsightsSpecification
from troposphere.dynamodb import KeySchema, ProvisionedThroughput

hashkeyname = "Foobar"

t = Template()
t.add_resource(Table(
    "mytable",
    AttributeDefinitions=[
        AttributeDefinition(
            AttributeName=hashkeyname,
            AttributeType="S",
        ),
    ],
    ContributorInsightsSpecification=ContributorInsightsSpecification(
        Enabled=True,
    ),
    KeySchema=[
        KeySchema(
            AttributeName=hashkeyname,
            KeyType="HASH"
        ),
    ],
    ProvisionedThroughput=ProvisionedThroughput(
        ReadCapacityUnits=50,
        WriteCapacityUnits=50,
    )
))

print t.to_json()
```

**Comment by austin-engle** [comment]
Sorry the error message was the title of the issue. 
`AWS::DynamoDB::Table object does not support attribute ContributorInsightsSpecification`

I tried doing what you did but got another error when trying to import

```
from troposphere.dynamodb import ContributorInsightsSpecification
```

error
```
ImportError: cannot import name 'ContributorInsightsSpecification' from 'troposphere.dynamodb' (/usr/local/lib/python3.9/site-packages/troposphere/dynamodb.py)
```

I have troposphere 2.6.4 installed with pip

**Comment by marinpurgar** [comment]
The `ContributorInsightsSpecification` was added 4 days ago in the commit https://github.com/cloudtools/troposphere/commit/bde0d9239ede72e4c34b96dab0b2dad5b759e9d8#diff-0e9214178e2b787b0d336b0903f4fb44e33b980b55a32ba7f5dfc8e164a24c20 after the 2.6.4 was released.
You'll have to use the current `master` branch or wait for a new release.

**Comment by austin-engle** [comment]
I appreciate that information! I will wait until the next release

**Comment by markpeek** [comment]
Thanks @marinpurgar. Forgot that was just put in.
