### ISSUE TITLE
Add ProtocolVersion property to AWS::ElasticLoadBalancingV2::TargetGroup

### ISSUE THREAD

**Issue by OrlovskiyItRex** [cloudtools/troposphere#1888]
Hi,
When I trying to apply my troposphere template with ProtocolVersion specifyed for targetgroup i receive an error:
failed (AWS::ElasticLoadBalancingV2::TargetGroup object does not support attribute ProtocolVersion)
I need it for creating gRPC targetgroups for my infrastructure. Can somebody help me please?

**Comment by markpeek** [comment]
Fixed. Thanks for the issue.
