### ISSUE TITLE
Release 2.7.1

### ISSUE THREAD

**Issue by vasinov** [cloudtools/troposphere#1890]
Would it be possible to release 2.7.1 with [this PR](https://github.com/cloudtools/troposphere/pull/1887) in it?

We have a project that depends on Troposphere and FIS that needs to be pushed to PyPI and not having this fix is blocking a release.

Thanks!

**Comment by markpeek** [comment]
Here you go...[Release 2.7.1](https://github.com/cloudtools/troposphere/releases/tag/2.7.1) and pushed to PyPI.

**Comment by vasinov** [comment]
Awesome. Thanks so much!
