### ISSUE TITLE
some problem for creation of .yml file from .py

### ISSUE THREAD

**Issue by 20FS21** [cloudtools/troposphere#1903]
Hello,
Congratulation to this tools. I start to study this and i think it's powerfull.
I have one question, i try to download script for CloudTrail from :
https://github.com/cloudtools/troposphere/blob/master/examples/CloudTrail.py
and run:
#python3 CloudTrail.py
But unfortunately in the shell show me the file and not crate the .yaml file. I do some wrong in my procedure ?
Thanks a lot.

**Comment by marinpurgar** [comment]
Hi!
When running the `python3 CloudTrail.py` the output should be the JSON representation of the CloudFormation Template. What is it that you want to accomplish? If you want to create the JSON file then just redirect the STDOUT to the JSON file e.g. `python3 CloudTrail.py >cloud_trail.json`.

**Comment by 20FS21** [comment]
Thanks a lot i fix it modify the file .py and using:
print(t.to_yaml())
with open('CloudTrail.yaml', 'w') as f:
    f.write(t.to_yaml())
