### ISSUE TITLE
troposphere 3.0

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#1904]
Another [issue](#1558) was tracking troposphere 3.0 changes but was pretty large in scope. Recent changes to deprecate Python 2 support and have a Python 3 only release have been committed. This issue is to track any additional (minimal) changes to get a 3.0 release made.

@michael-k please commend on any changes you think are necessary to proceed. Likely I'll go with a manual release process for this first release.

@workmanw per your request in #1889

**Comment by workmanw** [comment]
@markpeek Hey thanks! I hope it's not too much work for you. We really appreciate it!

**Comment by michael-k** [comment]
As I've said in #1558, I think dropping support for Python 2 is enough for a 3.0 release and then do everything else later. :shrug: 

Doing more major version bumps but with only a few breaking changes at once should be easier to handle for maintainers and users.  (As long as they aren't on a daily basis. ;) )

**Comment by ITProKyle** [comment]
Nothing to delay the release for but a few maintenance/QoL items that could go well alongside a major release.

- transition from Travis CI to GitHub Actions for running checks 
- implement tooling for virtual environment management (poetry or pipenv) to make setting up a local dev environment easier for contributors
- [adopt a code style](#1760)/auto formatter (e.g. black & isort)
  - enforced with [pre-commit](https://pre-commit.com/)

If these are things that would be considered, I can put in the time to implement them this week/weekend.

**Comment by michael-k** [comment]
`tox.ini` needs an update.  It still uses `basepython = python2.7`

**Comment by michael-k** [comment]
The release of 3.0 might also be a good opportunity to rename `master` to `main`.

**Comment by LokiLaufeyjarson** [comment]
Hmm, and what are we going to do about: `MasterUsername`, `MasterUserPassword`, `DedicatedMasterType`, `DedicatedMasterCount`, `DedicatedMasterEnabled`, `MasterInstanceGroup`, `MasterAutoScalingPolicy`, `KMSMasterKeyID`, `MasterSecretArn`, `MasterSecretKmsKeyArn`, EmrManagedMasterSecurityGroup(s)`, `MasterInstanceFleet`, `MasterInstanceGroup`, `MasterId`, `MasterUserARN`, `MasterUserOptions` and `AdditionalSlaveSecurityGroups`, `EmrManagedSlaveSecurityGroup`, `AwsAccountWhitelist`, `IpRangeWhitelist`, `SourceVpcWhitelist`, `WhitelistRules`, `AwsAccountBlacklist`, `IpRangeBlacklist`, `SourceVpcBlacklist` ... ?

**Comment by michael-k** [comment]
> Hmm, and what are we going to do about: `MasterUsername`, …

Those are the names that CloudFormation uses.  I'd say we keep those names for now to maintain 1:1 compatibility with CloudFormation.  The idea is to move away from manually managed code towards code generated from the spec.  This would be a good opportunity to introduce some kind of mapping (eg. Master ↔ Main/Primary/…).

Renaming `master` to `main` is a simpler change and doesn't affect end users.

**Comment by workmanw** [comment]
Shameful bump. Is there anything that can be done to get this moving forward, or to cut a new 2.7.x release? There is functionality in master we've been waiting on for nearly 2.5 months. We have a project that is at a complete stand still waiting on a new release.

**Comment by markpeek** [comment]
@workmanw just pushed [Release 3.0.0](https://github.com/cloudtools/troposphere/releases/tag/3.0.0).

@michael-k thank you for the help on getting the Python 3 work done.

Also, the default branch has been changed to [main](https://github.com/cloudtools/troposphere/tree/main).

**Comment by workmanw** [comment]
Thanks a lot @markpeek and @michael-k!
