### ISSUE TITLE
imagebuilder.InfrastructureConfiguration does not support `ResourceTags`

### ISSUE THREAD

**Issue by shijin-aws** [cloudtools/troposphere#1909]
`ResourceTags` is a supported property of `AWS::ImageBuilder::InfrastructureConfiguration`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-infrastructureconfiguration.html#cfn-imagebuilder-infrastructureconfiguration-resourcetags

But currently it's not supported in troposphere's `imagebuilder.InfrastructureConfiguration` class: https://github.com/cloudtools/troposphere/blob/master/troposphere/imagebuilder.py#L118-L133.

This property is important to enable adding tags to output resources of the image builder.

**Comment by markpeek** [comment]
Added. Thanks for the issue.
