### ISSUE TITLE
Add support for EngineVersion to AWS::Athena::WorkGroup WorkGroupConfiguration and WorkGroupConfigurationUpdates

### ISSUE THREAD

**Issue by mdsakalu** [cloudtools/troposphere#1915]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-athena-workgroup-workgroupconfiguration.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-athena-workgroup-workgroupconfigurationupdates.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-athena-workgroup-engineversion.html

**Comment by markpeek** [comment]
Added. Thanks for the issue.
