### ISSUE TITLE
Add support for AWS::CloudFront::Function

### ISSUE THREAD

**Issue by cwaldbieser** [cloudtools/troposphere#1916]
The function:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html#cfn-cloudfront-function-functioncode

Distribution CacheBehavior now has `FunctionAssociations`:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-functionassociations

**Comment by cwaldbieser** [comment]
Almost forgot the Function Association def:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-functionassociation.html

**Comment by cwaldbieser** [comment]
And a FunctionConfig
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-function-functionconfig.html

**Comment by cwaldbieser** [comment]
And FunctionMetadata:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-function-functionmetadata.html

**Comment by cwaldbieser** [comment]
Distribution DefaultCacheBehavior also has a `FunctionAssociation`:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html

**Comment by MacHu-GWU** [comment]
@cwaldbieser  do you mean something like this?

- [AWS::CloudFront::Function](https://github.com/MacHu-GWU/cottonformation-project/blob/main/cottonformation/res/cloudfront.py#L2182)
- [AWS::CloudFront::DistributionCacheBehavior.FunctionAssociations](https://github.com/MacHu-GWU/cottonformation-project/blob/main/cottonformation/res/cloudfront.py#L1233)

**Comment by cwaldbieser** [comment]
Yes, exactly.

**Comment by kfowler1337** [comment]
Any movement on this? I would also like to see this added.

**Comment by cwaldbieser** [comment]
I can submit a PR if that would help speed things up.
I think @MacHu-GWU 's library looks pretty slick, but I already have a bunch of Troposphere code that I don't really want to rewrite just to get some CloudFront functions.

**Comment by markpeek** [comment]
I believe both [CloudFront::Function](04a75368bb9f7960dec6c7ae20190740638a6d83) and [FunctionAssociations](90877e36a68bf5b9535992471c6b78c724dc20d5) were committed on 2021-06-12 and are in release v3.0.0 (and above).

**Comment by markpeek** [comment]
Borked links in that last comment. Here are the commits: 04a75368bb9f7960dec6c7ae20190740638a6d83 90877e36a68bf5b9535992471c6b78c724dc20d5
