### ISSUE TITLE
Missing cfn-flip requirement in 3.0.0

### ISSUE THREAD

**Issue by anne-k** [cloudtools/troposphere#1926]
The 3.0.0 release no longer has cfn-flip listed as dependency which leads to an error on startup if installed in a clean environment (ModuleNotFoundError: No module named 'cfn_flip'). 
Looks like it happened with the change to setup.cfg; the old setup.py adds the contents of requirements.txt as dependency but setup.cfg doesn't.

**Comment by jerry153fish** [comment]
hi @anne-k, I had a similar situation, ending up put cfn_flip in the project requirements.txt.

**Comment by povesma** [comment]
Also impacts Zappa: https://github.com/zappa/Zappa/issues/998

**Comment by markpeek** [comment]
Thank you for the issue. Fixed via #1927 and released 3.0.1 to address.
