### ISSUE TITLE
Add Support for AWS::Signer

### ISSUE THREAD

**Issue by mohancheema** [cloudtools/troposphere#1942]
AWSSigner

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Signer.html

Resource Types

- [AWS::Signer::ProfilePermission](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-signer-profilepermission.html)
- [AWS::Signer::SigningProfile](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-signer-signingprofile.html)

This will be helpful to use Code signing profile to be used in Lambda [AWS::Lambda::CodeSigningConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-codesigningconfig.html)

Regards,

**Comment by markpeek** [comment]
Thanks for the issue. Didn't see this new resource in the release notes.
Added via commit 4e1e63ee4838c3d49c31f4209e1ae5292fc0904f
