### ISSUE TITLE
Please support creating AWS::KinesisFirehose::DeliveryStream HttpEndpointDestinationConfiguration 

### ISSUE THREAD

**Issue by makknife** [cloudtools/troposphere#1949]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html#cfn-kinesisfirehose-deliverystream-httpendpointdestinationconfiguration

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-httpendpointdestinationconfiguration.html

this troposphere obj does not exist in
https://github.com/cloudtools/troposphere/blob/main/troposphere/firehose.py

thanks

**Comment by markpeek** [comment]
Added via 0ca9a72ffc11f5f911575aedb4dc68f521de714b

**Comment by makknife** [comment]
ty
