### ISSUE TITLE
Route53 Private Hosted Zone for VPC

### ISSUE THREAD

**Issue by Dumbris** [cloudtools/troposphere#195]
Is it possible to create [Private Hosted Zone](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html) with troposphere? I can't find docs or examples  about this.

**Comment by ikben** [comment]
Private Hosted Zones are not supported in Cloudformation at the moment: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html

(compare with: http://docs.aws.amazon.com/Route53/latest/APIReference/API-create-hosted-zone-private.html)

**Comment by Dumbris** [comment]
@ikben Thank you for clarifying.

**Comment by markpeek** [comment]
@cdandekar fyi

**Comment by kjhosein** [comment]
Hello all - looks like CF now supports private hosted zones:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-vpcs

**Comment by amuraru** [comment]
can you reopen this now that cf supports private hz?

**Comment by markpeek** [comment]
I believe that feature was implemented in this [commit](https://github.com/cloudtools/troposphere/commit/cdd1b271030d26312c51fdc53ab04bc3aa6fc8b7) in release 1.0.0. Is there something else that needs implementing for it?
