### ISSUE TITLE
wafv2.py Missing Valid Transformation Types in VALID_TRANSFORMATION_TYPES List

### ISSUE THREAD

**Issue by dalgarin** [cloudtools/troposphere#1987]
The wafv2.py module is missing new TextTransformation values announced [here](https://aws.amazon.com/about-aws/whats-new/2021/06/aws-waf-adds-15-new-text-transformations/) (https://aws.amazon.com/about-aws/whats-new/2021/06/aws-waf-adds-15-new-text-transformations/) and documented as supported by CloudFormation [here ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-texttransformation.html)(https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-texttransformation.html).  

Transformations currently allowed:  CMD_LINE | COMPRESS_WHITE_SPACE | HTML_ENTITY_DECODE | LOWERCASE | NONE | URL_DECODE

Full set of transformations that are allowed by CloudFormation:  BASE64_DECODE | BASE64_DECODE_EXT | CMD_LINE | COMPRESS_WHITE_SPACE | CSS_DECODE | ESCAPE_SEQ_DECODE | HEX_DECODE | HTML_ENTITY_DECODE | JS_DECODE | LOWERCASE | MD5 | NONE | NORMALIZE_PATH | NORMALIZE_PATH_WIN | REMOVE_NULLS | REPLACE_COMMENTS | REPLACE_NULLS | SQL_HEX_DECODE | URL_DECODE | URL_DECODE_UNI | UTF8_TO_UNICODE

**Comment by markpeek** [comment]
Thanks for this issue. I'll include these changes in an upcoming update I have pending for WAFv2. I'm going to be pulling out the validators into a separate file to allow for better auto-generation of the core files.

**Comment by markpeek** [comment]
Please review PR #1996 which includes these changes.

**Comment by markpeek** [comment]
These were included in the [Release 3.2.0](https://github.com/cloudtools/troposphere/releases/tag/3.2.0).
