### ISSUE TITLE
elb sample

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#199]
In the elb sample, if you attempt to create a stack from the generated cloud formation script you will get an error because 'us-east' is not defined. This needs to be changed to

```python
def AddAMI(template):
    template.add_mapping("RegionMap", {
        "us-west-1": {"AMI": "ami-3bcc9e7e"},
        "us-east-1": {"AMI": "ami-3bcc9e7e"}
    })
```

**Comment by phobologic** [comment]
Fortunately @k-ong helped us out with this one!  The latest source should handle this for you - as well as a ton of other regions.
