### ISSUE TITLE
AWS::Lex::BotAlias TextLogDestination needs a Type

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#1992]
@PatMyron do you know how to file an issue to get the Type for this defined?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lex-botalias-textlogdestination.html

**Comment by markpeek** [comment]
Note: assuming it is CloudWatchLogGroupLogDestination for now.

**Comment by PatMyron** [comment]
some resource types are open source now: https://github.com/patmyron/cloudformation-resource-providers and issues/PRs can be filed there, but unfortunately looks like Lex isn't

no longer at Amazon, but @kddejong might be able to raise an internal issue

**Comment by JohnPreston** [comment]
@PatMyron 
side question : do you know if there were a good place where one can catalog "custom made" ones ?

**Comment by PatMyron** [comment]
@JohnPreston https://github.com/org-formation/aws-resource-providers

**Comment by markpeek** [comment]
@PatMyron thank you for the update above and the redirect for the issue.

**Comment by markpeek** [comment]
Latest spec included the correct type.
