### ISSUE TITLE
NoneAction not supported by troposphere.wafv2

### ISSUE THREAD

**Issue by sid21rane** [cloudtools/troposphere#1998]
Yesterday I started using troposphere version 3.2.0.

Now I am getting "ImportError: cannot import name 'NoneAction' from 'troposphere.wafv2'".

I am using it like below -

OverrideAction=OverrideAction(**{"None": NoneAction()})

Please help.

**Comment by markpeek** [comment]
Thank you for the issue. Apologies for this change. The resource spec shows the [OverrideAction](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-overrideaction.html) None property as "Json". As such this property isn't emitted anymore. For any of the Json properties you can just use a dict.

troposphere 3.1.1
```
>>> from troposphere.wafv2 import OverrideAction, NoneAction
>>> OverrideAction(**{"None": NoneAction()}).to_dict()
{'None': {}}
```

troposphere 3.2.0
```
>>> from troposphere.wafv2 import OverrideAction
>>> OverrideAction(**{"None": {}}).to_dict()
{'None': {}}
```

Hope that helps...

**Comment by sid21rane** [comment]
Thanks Mark,

So I found out that to be used as -

from troposphere.wafv2 import OverrideAction
OverrideAction=OverrideAction(**{"None": {}})

Since then my build goes fine. 

Though I get error in cloudformation stack saying "Resource handler returned message: "Error reason: You have used none or multiple values for a field that requires exactly one value., field: STATEMENT, parameter: Statement (Service: Wafv2, Status Code: 400, Request ID: 00de1c1d-aef7-4a72-b0c3-fadefd361f3e, Extended Request ID: null)" (RequestToken: 4a25ba14-39e2-a826-ab70-5807bdc08962, HandlerErrorCode: InvalidRequest)".

My Statement block says -

Statement=StatementOne(
                LabelMatchStatement=LabelMatchStatement(
                    Scope="LABEL", Key="awswaf:managed:aws:linux-os:LFI_URIPath"
                ),
                NotStatement=(
                    NotStatementOne(
                        Statement=StatementTwo(
                            ByteMatchStatement=ByteMatchStatement(
                                SearchString="/abc/123/sample.js",
                                FieldToMatch=FieldToMatch(**{"UriPath": {}}),
                                TextTransformations=[
                                    TextTransformation(Priority=0, Type="URL_DECODE")
                                ],
                                PositionalConstraint="CONTAINS",
                            )
                        )
                    )
                ),
            ),

Anything I am missing?

**Comment by markpeek** [comment]
I'm not exactly sure what could cause that error. I did see an extra set of parens around NotStatementOne. Perhaps try this?
```
Statement=StatementOne(
    LabelMatchStatement=LabelMatchStatement(
        Scope="LABEL",
        Key="awswaf:managed:aws:linux-os:LFI_URIPath"
    ),
    NotStatement=NotStatementOne(
        Statement=StatementTwo(
            ByteMatchStatement=ByteMatchStatement(
                SearchString="/abc/123/sample.js",
                FieldToMatch=FieldToMatch(**{"UriPath": {}}),
                TextTransformations=[
                    TextTransformation(Priority=0, Type="URL_DECODE")
                ],
                PositionalConstraint="CONTAINS",
            )
        )
    ),
)
```
