### ISSUE TITLE
Not able to set EnableVersionUpgrade in AWS ElasticSearchDomain

### ISSUE THREAD

**Issue by jayk-sub** [cloudtools/troposphere#1999]
Currently I am using troposphere version 2.7.1 and am I trying to set the EnableVersionUpgrade for AWS ElasticSearchDomain using the below code snippet. But, it doesn't work. Is this option possible in troposphere or it is not yet supported?
 I am able to generate the cloudformation but it sets the ElasticSearchVersion to 6.2. But when I remove the EnableVersionUpgrade, the generated cloudformation has ElasticSearchVersion 6.7

search_domain = template.add_resource(
        Domain(
            "ElasticsearchDomain",
            DomainName=Ref("AWS::StackName"),
            ElasticsearchVersion="6.7",
            NodeToNodeEncryptionOptions=NodeToNodeEncryptionOptions(Enabled=True),
            UpdatePolicy=UpdatePolicy(
                EnableVersionUpgrade=True),

References:
[1] AWS::Elasticsearch::Domain - Properties - ElasticsearchVersion - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-elasticsearchversion 

[2] UpdatePolicy attribute - EnableVersionUpgrade policy  - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-upgradeopensearchdomain

**Comment by jayk-sub** [comment]
Sorry, This issue is not valid any more. It works.

**Comment by markpeek** [comment]
Glad to hear it works. BTW, noticed you mentioned troposphere 2.7.1. As you likely know that version is end of life with Python 2 so for future changes you will need to upgrade to Python 3 and troposphere 3.x.
