### ISSUE TITLE
Bug with TransitEncryption property for EFSVolumeConfiguration for ECS

### ISSUE THREAD

**Issue by Jmevorach** [cloudtools/troposphere#2000]
This : https://github.com/cloudtools/troposphere/blob/main/troposphere/validators/ecs.py#L81

is not supposed to be the validator for EFSVolumeConfiguration.TransitEncryption.

Furthermore putting that validator here:

https://github.com/cloudtools/troposphere/blob/9d4300f2dd4e479b7df350a6e42fbb2a242039e7/troposphere/ecs.py#L675

Makes it impossible to use encrypted EFS volumes in ECS.

If you try to set TransitEncryption to "ENABLED" you'll get an error saying that it needs to be "APPMESH" which is not accurate.

**Comment by markpeek** [comment]
Thanks for the issue and sorry for the regression. Fixed on main. I will do a release later today to include it.

**Comment by Jmevorach** [comment]
@markpeek All good! I'm a big fan of the library! Really appreciate the quick turn around on this.

**Comment by Jmevorach** [comment]
@markpeek Sorry to be a bother; any word on when the new release is coming out?

**Comment by markpeek** [comment]
Just released [3.2.2](https://github.com/cloudtools/troposphere/releases/tag/3.2.2)

**Comment by Jmevorach** [comment]
@markpeek Thank you!
