### ISSUE TITLE
FMS::Policy ResourceTypeList property set as required when conditional

### ISSUE THREAD

**Issue by MattJaccino** [cloudtools/troposphere#2002]
https://github.com/cloudtools/troposphere/blob/5b8ae9cb48852ce0488d85873f664ec3926392a4/troposphere/fms.py#L42

Hi guys,
Team and I have been using this library for a while now, thank you for that.  An issue I ran into recently is that the `ResourceTypeList` property for FMS Policy resources is set as a required property, but according to the [AWS CFN documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-policy.html#cfn-fms-policy-resourcetypelist), the list is only required if the `ResourceType` property is set to `ResourceTypeList`.  Remedied this by re-creating the class locally, but others might have the same issue

Thank you!

**Comment by markpeek** [comment]
Thank you for the issue. Fixed via d5aa3a45d1e53c300d6e5bc92cc2feeda56b07e9
