### ISSUE TITLE
Missing `Parameters` support in imagebuilder.ComponentConfiguration in v3.2.2

### ISSUE THREAD

**Issue by rahulakash** [cloudtools/troposphere#2005]
Missing `Parameters` support in imagebuilder.ComponentConfiguration in `v3.2.2`. 

I see that this is already included here [imagebuilder.py#L58](https://github.com/cloudtools/troposphere/blob/main/troposphere/imagebuilder.py#L58) with this [commit](https://github.com/cloudtools/troposphere/commit/96a96ea4a9bef498847abfc78bcebfd000ff5228#diff-ad3a0d7fd42a3816b5e5fe06c8877450ccee5e05fd2db08598627553029a1e8cR58) but missing in the latest release. 

@markpeek: Can we get the latest main update released please?

**Comment by markpeek** [comment]
[Release 4.0.0](https://github.com/cloudtools/troposphere/releases/tag/4.0.0) is now available with this change.
