### ISSUE TITLE
Add MSK Connect support

### ISSUE THREAD

**Issue by pankajpreet** [cloudtools/troposphere#2006]
I would be good to have support for AWS [MSK](https://aws.amazon.com/msk/features/msk-connect/). [Cloudformation template](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kafkaconnect-connector.html)

**Comment by markpeek** [comment]
Thanks for the issue. Added via a19fb78a9016b99d1e0d623e2a682eb6f37ee507.

**Comment by pankajpreet** [comment]
@markpeek thanks :), do you know when new version of troposphere will be released.
