### ISSUE TITLE
AWS::Lambda::Function ImageConfig EntryPoint is Type: List of String while troposphere is Str

### ISSUE THREAD

**Issue by evilensky** [cloudtools/troposphere#2008]
I think this is defined here? https://github.com/cloudtools/troposphere/blob/main/troposphere/awslambda.py#L287 Would it makes sense to change this definition to List?

**Comment by markpeek** [comment]
Looking at both 3.2.2 and 4.0.0-beta.0, this is defined as `[str]` which means a list of strings. This matches the AWS documentation. Do you have an example that doesn't work?
```
>>> from troposphere.awslambda import ImageConfig
>>> ImageConfig(EntryPoint=["string1", "string2"]).to_dict()
{'EntryPoint': ['string1', 'string2']}
```

**Comment by evilensky** [comment]
We are on [2.7,](https://github.com/cloudtools/troposphere/blob/23a112c631152b2e59a2079ca34e2c5555f22db7/troposphere/awslambda.py#L162) apologies for wasting your time. Is there by chance a direct upgrade guide to 3.x+ ? It looks like at a minimum `'False'` needs to become `False`.

**Comment by markpeek** [comment]
Going from Python 2.x to 3.x with troposphere 3.x should be fairly straightforward. Just check out these [breaking changes](https://github.com/cloudtools/troposphere/blob/main/CHANGELOG.rst#breaking-changes-1).
