### ISSUE TITLE
Internal facing ELB?

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#201]
I'm looking at the elastic load balancer class for a property to define 'internal facing' only, however I don't see this option. How can I achieve this with Troposphere?

All about ELB internet facing and internal facing: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/vpc-loadbalancer-types.html

**Comment by BardiaAfshin** [comment]
foudn it. it's under scheme

**Comment by mekazu** [comment]
https://xkcd.com/979/
