### ISSUE TITLE
Add spec version to maintenance action

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#2010]
It would be good to add the spec version to the PR submitted via the maintenance action. It can be obtained via:
```
jq -r .ResourceSpecificationVersion CloudFormationResourceSpecification.json
```
@PatMyron is there a way to customize the action in this way?

**Comment by PatMyron** [comment]
I've always just manually edited commit messages while merging, but it does look documented here:
https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#dynamic-configuration-using-variables

**Comment by markpeek** [comment]
Added via e9328bba5fc69babccdbb00cbcd64213fb9d12aa. Wondering if this should be removed to only trigger via cron or manual workflows.
```
  push:
    branches: [ main ]
```
