### ISSUE TITLE
Creating security group with group name and group id 

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#202]
Where can I create a security group with the group name and group id set. I've looked through example code, and nothing immediate is found. I can see in several instances they reference it as a parameter for the user to enter, but I'm trying to create a security group with both the valid name, and valid group id set and added to different resources throughout my script, and not ask for the user to enter any sort of parameter. If anything, having it a pre populated parameter, but that's bonus.

```PYTHON
    SecurityGroup = template.add_parameter(Parameter(
        "SecurityGroup",
        Type="String",
        Description="Security group for api instances.",
        GroupName="mygroupname",
        GroupId="sg-xxxxxxxx"
        ))
```

**Comment by markpeek** [comment]
If you are creating the security group in your troposphere script via CloudFormation then you should not use Parameter for it. That is only used for actual input from the CloudFormation console. You want to add it as a resource instead. The general form if you're in a VPC (and needing a group id) would be:

```
...
instanceSecurityGroup = t.add_resource(
    SecurityGroup(
        'InstanceSecurityGroup',
        GroupDescription='Enable SSH access via port 22',
        SecurityGroupIngress=[
            SecurityGroupRule(
                IpProtocol='tcp',
                FromPort='22',
                ToPort='22',
                CidrIp=Ref(sshlocation_param)),
            SecurityGroupRule(
                IpProtocol='tcp',
                FromPort='80',
                ToPort='80',
                CidrIp='0.0.0.0/0')],
        VpcId=Ref(VPC),
    ))
...
```
This is from examples/VPC_single_instance_in_subnet.py and note the Ref(VPC) which is a reference to a previously defined VPC object. This will cause CloudFormation to create a new resource. Then you can  reference it later on using `Ref(instanceSecurityGroup)`.

There is a little "magic" going on where the Ref in troposphere is to a python object which will output the appropriate security group name you specified when you created the object. This in turn will be used inside of CloudFormation to insert the appropriate group id.

**Comment by BardiaAfshin** [comment]
This is very helpful, but I already have the Security Group defined via the amazon console. I'd like to be able to just reference that. What I really desire is the ability to append the following JSON in both instances and ELB's via troposphere attributes

```JSON
                    "SecurityGroups": [
                        {
                            "GroupName": "moonshot", 
                            "GroupId": "sg-d82d95bc"
                        }
                    ], 
...
```

I've played with the example you've mentioned above and as helpful as it is, I need to define the VPC along with a few more other things that require me to make more changes to the script than I'd like... for now.

Thoughts?

**Comment by markpeek** [comment]
If you look at this [snippet](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ec2.html) you will see: ```"SecurityGroups" : [{ "Ref" : "Ec2SecurityGroup" }],```. This is usually expressed in troposphere as an argument ```SecurityGroups=[Ref(Ec2SecurityGroup),]```. But that is because a Ref is occurring (meaning you're probably creating it in the CloudFormation script). But that is really a list of strings so you could use ```SecurityGroups=["moonshot",]``` for a pre-exising SG.

How you get a name or id (depending on vpc or not) into your script is up to you. You can hard code it, pull it out of AWS via boto dynamically, or even use a parameter to allow it to be included into your script upon launch.

Note, if you do that latter using a parameter, you need to so the Ref trick again. Slight tweaks to the EC2InstanceSample.py:
```
...
sg_param = template.add_parameter(Parameter(
    "SecurityGroup",
    Description="Existing Security Group",
    Type="String",
))
...
SecurityGroups=[sg_param],
...
```

No idea what is wrong with your other script. It seems to imply you have a parameter object being created which you're trying to call. Verify you're not using the same object/variable names.

**Comment by BardiaAfshin** [comment]
Can you reuse defined SecurityGroups in both your instances and elastic load balancers?

**Comment by markpeek** [comment]
In theory, yes. If you are talking about reusing objects within troposphere.

In practice, probably not. While you might have port 80 and 443 open to both, you probably would have ssh access open to the instances but not to the elb. Not to mention different network rules depending on being in a VPC, etc. So it would be more contextual.

An example is the ELB sample where the same security group is being used for the two instances.

**Comment by phobologic** [comment]
I'm going to close this since it's not a bug.  If you want to get help with this some more, lets take it to he group.  Thanks!
