### ISSUE TITLE
Confusing/missleading error messages around required attributes for some types (resource_type not defined)

### ISSUE THREAD

**Issue by canopus1io** [cloudtools/troposphere#2020]
```python
class CustomHeader(AWSProperty):
    """
    `CustomHeader <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-responseheaderspolicy-customheader.html>`__
    """

    props: PropsDictType = {
        "Header": (str, True),
        "Override": (boolean, True),
        "Value": (str, True),
    }

troposphere.cloudfront.CustomHeader(Header="Cache-Policy", Value="no-cache")
```

Yields this error in validation:
`ValueError("Resource Override required in type <unknown type>")`

# A couple things wrong with this:
- Override is not a Resource, its an attribute (not ideal, but I believe this is because its used for validating Resources primarily)
- and how am I supposed to find <unknown type> ?

# My proposal:
instead of falling back to <unknown type>
we should fall back to the classname.

e.g. error would be this instead:
`ValueError("Resource Override required in type <class 'troposphere.cloudfront.CustomHeader'>")`

My one liner PR for the change:
https://github.com/cloudtools/troposphere/pull/2019

**Comment by markpeek** [comment]
Fixed via #2019 and merged via cf527ab34cc7fe147a039b26c65febd775d0d6ff
