### ISSUE TITLE
New wafv2 implementation blocks >2 And/Or Statements

### ISSUE THREAD

**Issue by splunkbot9000** [cloudtools/troposphere#2031]
It seems that in 4.0.0 we can now only declare two statements in an AndStatement or OrStatement Statements list. Is this intended? Our implementation uses 2, 3 or sometimes more statements in some AndStatement's and OrStatement's.

Can https://github.com/cloudtools/troposphere/blob/main/troposphere/validators/wafv2.py#L32 be changed to <= 1 instead?

**Comment by markpeek** [comment]
Thank you for the issue. I meant to do a release over the weekend to resolve this issue. I'll get one out this afternoon.
Dup of #2026 and will be fixed via #2027.

**Comment by markpeek** [comment]
Fixed in [Release 4.0.1](https://github.com/cloudtools/troposphere/releases/tag/4.0.1)
