### ISSUE TITLE
Validation should only report CidrBlock as missing from VPC object when IPAM properties haven't been supplied

### ISSUE THREAD

**Issue by piboky** [cloudtools/troposphere#2042]
Now that AWS has released [IPAM](https://docs.aws.amazon.com/vpc/latest/ipam/what-it-is-ipam.html), the `CidrBlock` property is no longer required on VPC objects if IPAM properties (`Ipv4IpamPoolId` and `Ipv4NetmaskLength`) are supplied instead. Validation should reflect this change.

Similar to [this issue](https://github.com/aws-cloudformation/cfn-lint/issues/2237) in cfn-lint.

**Comment by markpeek** [comment]
Fixed via 9d73ae9f73f9b6ca884e1112c93857360b6f3270
