### ISSUE TITLE
New Generation Instance Types

### ISSUE THREAD

**Issue by mrswats** [cloudtools/troposphere#2047]
I was creating a new stack and I noticed there are not yet the new generation of AMD Machines (`c6a.large`, etc...) and I was wondering if they will be added soon or if they have to be added (I would gladly open a new PR for this). Same with the `cache.t3.small` collection.

Thanks!

**Comment by PatMyron** [comment]
Been thinking for a while [`constants`](https://github.com/cloudtools/troposphere/blob/main/troposphere/constants.py) shouldn't be hardcoded in `troposphere`: https://github.com/cloudtools/troposphere/issues/1558#issuecomment-703309200 (especially instance types)

---

Luckily, troposphere's hardcoded constants don't need to be used and you can hardcode any new instance type even if troposphere hasn't explicitly included it, so it should be possible to workaround with that

**Comment by mrswats** [comment]
Many thanks @PatMyron! All clear. Cheers 🍻
