### ISSUE TITLE
s3 module does not support bucket naming standards as per AWS

### ISSUE THREAD

**Issue by sunny2385** [cloudtools/troposphere#206]
__init__.py in troposphere throws out following error if "-" is used in S3 bucket name

ile "/Library/Python/2.7/site-packages/troposphere/__init__.py", line 43, in __init__
    raise ValueError('Name "%s" not alphanumeric' % title)
ValueError: Name "xx-xxx" not alphanumeric

AWS docs states that bucket names can contain hyphens. 

Here is the piece of concerned code 

line 49 in __init__.py
" if title and not valid_names.match(title):
raise ValueError('Name "%s" not alphanumeric' % title)
"

Line 28 in __init__.py
valid_names = re.compile(r'^[a-zA-Z0-9]+$')

**Comment by ikben** [comment]
There is a difference between bucketName and the name of the resource.

This works:

    bucket = s3.Bucket('NoHyphens', BucketName='with-hyphens')

This doesn't:

    bucket = s3.Bucket('Invalid-Hyphen', BucketName='valid-hyphen').

**Comment by phobologic** [comment]
Thanks @ikben!  Closing this issue.

**Comment by sunny2385** [comment]
thanks for the clarification
