### ISSUE TITLE
Missing querystring behaviour for cloudfront cache policies.

### ISSUE THREAD

**Issue by CaptainJiNX** [cloudtools/troposphere#2060]
According to your validation, the allowed values here are `["none", "whitelist", "all"]`, but according to AWS docs, they should be `["none", "whitelist", "allExcept", "all"]`.

Your validation:
https://github.com/cloudtools/troposphere/blob/main/troposphere/validators/cloudfront.py#L72

AWS documentation.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cachepolicy-querystringsconfig.html

**Comment by markpeek** [comment]
Thanks for the issue. Fixed now.
