### ISSUE TITLE
Remove redundant validators.py file from wheel

### ISSUE THREAD

**Issue by vinayinvicible** [cloudtools/troposphere#2070]
https://github.com/cloudtools/troposphere/commit/1b5108efc01be72a3959a9272062436accb3d6c5 has removed validators.py in favor of the module.
This file is still being bundled as part of whl but not as tar.gz.
Not sure how the release is managed. Would be nice to fix this, in order to avoid any confusion.

**Comment by markpeek** [comment]
Thank you for this issue. It was left over in the build directory and was removed.
