### ISSUE TITLE
Add support for FunctionUrlConfig in Serverless Function

### ISSUE THREAD

**Issue by quirozs** [cloudtools/troposphere#2071]
The serverless (SAM) definition of Function is missing the FunctionUrlConfig argument, see here:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-functionurlconfig

**Comment by markpeek** [comment]
@quirozs does this PR #2072 work for you?

**Comment by quirozs** [comment]
Yes, that's working perfectly. Thank you!

**Comment by markpeek** [comment]
Merged. Thanks for the issue.
