### ISSUE TITLE
Lakeformation PrincipalPermissions and Permissions incorrectly have the same ResourceProperty

### ISSUE THREAD

**Issue by mumblepins** [cloudtools/troposphere#2073]
[AWS::LakeFormation::Permissions Resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-permissions-resource.html) and [AWS::LakeFormation::PrincipalPermissions Resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-principalpermissions-resource.html) have different attributes, but are treated identically in Troposphere. 

I'm guessing that [`lakeformation.PrincipalPermissions`](https://github.com/cloudtools/troposphere/blob/759496c4d2ed3fec6fcb7315b98fa9bf7e2335b2/troposphere/lakeformation.py#L212) and [`lakeformation.Permissions`](https://github.com/cloudtools/troposphere/blob/759496c4d2ed3fec6fcb7315b98fa9bf7e2335b2/troposphere/lakeformation.py#L197) should probably reference different `ResourceProperty` classes.

**Comment by markpeek** [comment]
@mumblepins can you review this fix #2088?
