### ISSUE TITLE
RDS Validiation: minimum allocated storage for Provisioned IOPS for SQLServer is 20GiB, not 100GiB

### ISSUE THREAD

**Issue by wannessels** [cloudtools/troposphere#2075]
Troposphere validates the minimum allocated storage required for provisioned iops at 100
https://github.com/cloudtools/troposphere/blob/main/troposphere/validators/rds.py#L345

For SQLServer, the minimum is 20
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#USER_PIOPS

**Comment by markpeek** [comment]
@wannessels can you review and try #2087 which should fix this issue?

**Comment by wannessels** [comment]
👍 looks good
