### ISSUE TITLE
How do you define a stack-level tag on a cloudformation stack?

### ISSUE THREAD

**Issue by sgoudham** [cloudtools/troposphere#2081]
Hi, I'm wanting to add/propagate tags to all resources underneath a single cloudformation stack, it looks like AWS has the idea of a `stack-level` tag which automatically _tries_ to add/propagate the tag to every single resource. 

`Relevant AWS Docs`
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html?icmpid=docs_cfn_console
`Screenshot from AWS Clouformation Console`
![image](https://user-images.githubusercontent.com/58985301/195437729-c44f8501-4920-4eb0-ab0a-dcb00d42f8df.png)

Unfortunately, after scouring the documentation of troposphere, I'm still not able to find any relevant documentation on how to add this in the template. I was only able to find documentation for defining tags on singular resources. 

So... is there any way to define a stack-level tag on a cloudformation stack?

**Comment by markpeek** [comment]
I have not seen a way to define stack-level tags in the template itself. I believe you have to do that via the CLI or console when deploying the stack.

**Comment by sgoudham** [comment]
Oh okay, thanks!
