### ISSUE TITLE
RDS Aurora Serverless v2 support

### ISSUE THREAD

**Issue by roded** [cloudtools/troposphere#2086]
CloudFormation added support for Aurora Serverless v2 on Oct 5, 2022.

https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-aurora-serverless-v2-supports-aws-cloudformation

**Comment by markpeek** [comment]
The only thing I saw in the CloudFormation release notes was [ServerlessV2ScalingConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-serverlessv2scalingconfiguration.html) which was implemented in this PR #2077 (in a release likely today). Was there anything else you know of needed?

**Comment by roded** [comment]
Oh, excellent. I was not aware it has been implemented already.
I've found that I also need to remove `EngineMode` from `AWS::RDS::DBCluster` for serverless-v2, that's working properly though.
Thanks! I'll wait for the release.
