### ISSUE TITLE
We need "OSReleaseLabel" property to be added in emr.py under PropsDictType 

### ISSUE THREAD

**Issue by michelle37** [cloudtools/troposphere#2094]
Hi, AWS has added "OSReleaseLabel" object in AWS::EMR::Cluster resource type, in order for us to use it, troposphere will also need to add this property, is there a quick workaround for this issue? This is first time I am asking question here, hoping I am following the rules here...

**Comment by markpeek** [comment]
There was both this issue and email to the cloudtools mailing list. I'll just respond here for better tracking of this issue.

For new functionality the CloudFormation team adds it, then it shows up in the published documentation and resource specification. A new spec is published usually Thur/Fri timeframe and there is a daily github action which will pick up those changes to make a PR in troposphere.

For this specific need, we need to wait for OSReleaseLabel to be added by the CloudFormation team and then we can make it available automatically in troposphere. I'll leave this Issue open to track this need.

**Comment by michelle37** [comment]
@markpeek thank you for the information, you mentioned that the CloudFormation team adds the new functionality, are you talking about CloudFormation team from AWS? if so I can talk to AWS and get them input quickly.
Thank you

**Comment by markpeek** [comment]
@michelle37 yes, the AWS CloudFormation team (well, it likely is also the AWS EMR team in conjunction with the CF team). I usually see new functionality show up in these [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html) and the [release notes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).

**Comment by michelle37** [comment]
@markpeek got it, thank you! I have informed AWS TAM on this their engineer has reported this to CloudFormation team and hopefully they add this to their docs soon.

**Comment by michelle37** [comment]
@markpeek  aws has added the OSReleaseLabel in the cloudformation doc
https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.aws.amazon.com_AWSCloudFormation_latest_UserGuide_aws-2Dresource-2Delasticmapreduce-2Dcluster.html-23aws-2Dresource-2Delasticmapreduce-2Dcluster-2Dsyntax&d=DwMF_g&c=MrQrGL4Bt1iC3sN_evS3dQ&r=I3IEnYj9GbgezDTY5C9gq5u_h7coCgK9P_JvHrH2PI4&m=0idtDSQIL08l364MgXXniAUjPQY9HuGV9tLs2tfmyyKetb4uzKZAQ_D_zUHI02p6&s=4KkwNLar4xTF_RZUt3Jnx7pLqW2G6Z4hFMKqQNB3kEA&e=

**Comment by michelle37** [comment]
aww NVM, i see it is added in already!! awesome

**Comment by markpeek** [comment]
Added via 6a0699ac8830c8a1294678b4d641ac8977ba93d5 from spec 98.0.0
