### ISSUE TITLE
LoadBalancerInfo validator unnecessary or incorrect?

### ISSUE THREAD

**Issue by NeilJed** [cloudtools/troposphere#2096]
I've been making a LoadBalancerInfo resource and fallen foul of the validator when using a TargetGroupPairInfoList.

https://github.com/cloudtools/troposphere/blob/main/troposphere/codedeploy.py#L321

As far as I can tell from the LoadBalancerInfo class and AWS API Documentation, all three of the possible properties are optional yet the validator requires at least one of two of them to be used. Going on the documentation, I believe they are mutually exclusive.

Ref:
- https://docs.aws.amazon.com/codedeploy/latest/APIReference/API_LoadBalancerInfo.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentgroup-loadbalancerinfo.html

By disabling the validator I've been able to build my template and deployed it without any complaints or errors from Cloudformation and things work as expected.

**Comment by markpeek** [comment]
Thanks for the issue. I'm guessing 'TargetGroupPairInfoList' needs to be added to this [list](https://github.com/cloudtools/troposphere/blob/main/troposphere/validators/codedeploy.py#L41) in the validator. Can you give that a try?
