### ISSUE TITLE
ApiGatewayV2 Stage resource Tags should be a dict, and incorrect RouteSettings LoggingLevel in validator

### ISSUE THREAD

**Issue by lnreeder** [cloudtools/troposphere#2099]
Per latest Boto3 docs, the Stage Tags should be a dict (same as Troposphere currently has for the VpcLink resource).  Also, valid LoggingLevels per Cloudformation and Botot 3 should be "INFO, ERROR, or OFF" not `"WARN", "INFO", "DEBUG"` that the Troposphere LoggingLevel validator currently has.

**Comment by lnreeder** [comment]
Created PR 2100 to fix these two issues

**Comment by markpeek** [comment]
Fixed via #2100
