### ISSUE TITLE
ElasticBeanstalk ConfigurationTemplate properties are incorrect

### ISSUE THREAD

**Issue by mache** [cloudtools/troposphere#210]
ref: https://github.com/cloudtools/troposphere/blob/master/troposphere/elasticbeanstalk.py#L38-L46

According to the CF docs, there are some properties missing from troposphere for this resource.
 
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-beanstalk-configurationtemplate.html

The `TemplateName` is optional if you would like to inherit from another config template, however it's incorrectly required as a property in troposphere. Additionally, the `ApplicationName` must not be empty.

**Comment by phobologic** [comment]
Thanks for pointing this out - either we were *way* off when we created ElasticBeanstalk, or else the template objects have changed drastically.

I'm working on an update.

**Comment by phobologic** [comment]
BTW, I have a fix on deck in the branch: https://github.com/cloudtools/troposphere/tree/GH-210

That said, it looks like they got rid of the example template that we used for our examples & tests, so I'll need to convert one of the new ones (the nodejs one?) to this new format.  I'll try to get to that by this weekend.  If someone else wants to take a crack at it, or check out my branch to test it manually, that'd be awesome.

Thanks again @mache

**Comment by mache** [comment]
Great, thanks for the quick response.

**Comment by phobologic** [comment]
Ok, I've gone ahead and made a pull request that I believe fixes this and updates the example app/test.

https://github.com/cloudtools/troposphere/pull/213

@mache Any chance you could test the new classes, etc?  I don't use ElasticBeanstalk, so haven't played with it before.

**Comment by phobologic** [comment]
Had a bug due to a misunderstanding of the different Policy types in the IAM module.  Updated the pull with the new version - also tested that that version launches in CloudFormation.  Looks good so far.

**Comment by phobologic** [comment]
@mache Ok, we've merged GH-213.  Should be working as documented!
