### ISSUE TITLE
Capturing DNS information during Cloudformation boot time

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#211]
This is a more general question. How do I capture the output of a newly generated instance/ELB DNS? I'd like to chain this information into some other point of reference ie.

1. ELB is generated
2. Instance is created, and be able to put a text file into this instance with the reference of the DNS of newly generated ELB.

How does one go about this with Troposphere?

**Comment by phobologic** [comment]
This isn't super easy, and requires that the OS of the instance be able to parse user data and write out files.

For an LoadBalancer object that you named 'ELBNAME' you would then put a Ref("ELBNAME") in the UserData for the instance in whatever format you need it to be in for the OS to read from the user data and write out the name for you.

If you go here, and then take a look at the first example of Template Examples  here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-userdata

You should see something similar - where they are passing in the WebServerPort to the userdata of a launch configuration for autoscaling.

Worth understanding userdata - it makes life a lot easier in general:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html

**Comment by phobologic** [comment]
Also, you really should send these out to the cloudtools-dev mailing list - that way you don't have to wait for someone to notice your issue :)  I'm going to go ahead and close this.

**Comment by phobologic** [comment]
here's the URL to join the list in case you haven't already: https://groups.google.com/forum/#!forum/cloudtools-dev

**Comment by phobologic** [comment]
BTW, just so this doesn't confuse anyone else - It's not Ref() you should use, but GetAtt for the 'DNSName' attribute of the ELB.  The discussion has moved to the mailing list, thanks @BardiaAfshin!
