### ISSUE TITLE
Support for EMR volume type for gp3, st1, sc1

### ISSUE THREAD

**Issue by MircoGiorgetta** [cloudtools/troposphere#2113]
Hi,

from the AWS Cloudformation documentation it is possibile now to create EMR cluster with volume type gp3, st1 and sc1.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification.html#cfn-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification-volumetype
Looking in the troposphere source code under troposphere/validators/emr.py, there's the volume_type_validator function which is restricting the valid volume type only to standard, io1, gp2.
It would be necessary to extend the list of valid volume types by also including gp3, st1, sc1.

I've tried to make a new branch and a pull request but I haven't the write permissions

Please let me know if you can add these volume types.

Thanks,
Mirco

**Comment by markpeek** [comment]
Fixed. Thanks for the issue.
