### ISSUE TITLE
Lambda ZipFile 4096 characters limitation

### ISSUE THREAD

**Issue by cerbrus666** [cloudtools/troposphere#2119]
https://github.com/cloudtools/troposphere/blob/321b8870ac9b92a987fa21309ff9e8a3612fe546/troposphere/validators/awslambda.py#L89

The new AWS Cloudformation allow for up to 4MB ZipFile
The current implementation still uses the old limitation which is 4096 characters, this caused me error when compiling

**Comment by cerbrus666** [comment]
https://github.com/aws-cloudformation/cfn-lint/pull/2431 might be related to this too from cfn-lint

**Comment by markpeek** [comment]
Fixed. Thanks for the issue.
