### ISSUE TITLE
GetAtt returns object

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#212]
Is there anyway to parse out a string that's being returned from GetAttr?

ie:
```PYTHON
first_instance_DNSName = GetAtt(first_instance, "DNSName")
print first_instance_DNSName
exit()
```

```output
<troposphere.GetAtt object at 0x102851410>
```

I'd like the actual value that comes out of this. Very similar with what you can do via

```PYTHON
template.add_output(Output(
    "FirstInstanceGoodies",
    Description="Troposphere DNS name",
    Value=Join("", ["http://", GetAtt(first_instance, "DNSName")])
))
```

**Comment by phobologic** [comment]
It's not possible - you need to understand how GetAtt works and where the division of CloudFormation & python exist.  See my email in the group.
