### ISSUE TITLE
Version 4.3.1: ModuleNotFoundError: No module named 'troposphere.type_defs'

### ISSUE THREAD

**Issue by ecs-jnguyen** [cloudtools/troposphere#2132]
Hey guys, I was running into an error `ModuleNotFoundError: No module named 'troposphere.type_defs'`. I saw that `from ..type_defs.compat import Final` was added to `troposphere/validators/autoscaling.py`.

When I pulled down the 4.3.1 package I noticed that the `type_defs` folder doesn't exist. VS Code is giving also giving me the error `Import "..type_defs.compat" could not be resolved`.

**Comment by sbraverman** [comment]
Same here. It was added to ec2.py as well. I locked down to 4.3.0 for now until this is resolved.

**Comment by markpeek** [comment]
Thank you for the prompt issue and apologies for the breakage. The troposphere.type_defs package should now be included in the just released 4.3.2. I will have to look at improving the release test to ensure it catches this before it gets released.

**Comment by sbraverman** [comment]
Confirming, 4.3.2 working. Thank you for quick resolution

**Comment by markpeek** [comment]
Thanks for the confirmation. Closing.
