### ISSUE TITLE
field 'Tags' missing from events.Rule

### ISSUE THREAD

**Issue by lreeder-arpio** [cloudtools/troposphere#2151]
Per Boto and Cloudformation documents (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-tagging.html, or see Boto return types for EventBus and Rule), "In EventBridge, you can assign tags to rule[s] event buses".   In Troposphere, events.EventBus has Tags, but events.Rule does not.

**Comment by markpeek** [comment]
Thanks for the issue and PR.
