### ISSUE TITLE
Options object does not support attribute Igmpv2Support: Transit Gateway Multicast Domain

### ISSUE THREAD

**Issue by cubs818** [cloudtools/troposphere#2184]
ec2.TransitGatewayMulticastDomain uses ec2.Options for the options fields but they do not include these three options.  Confirmed this by adding Igmpv2Support: (str, false) to the Options class and it worked as expected.

Options available...
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-transitgatewaymulticastdomain-options.html#cfn-ec2-transitgatewaymulticastdomain-options-igmpv2support

**Comment by markpeek** [comment]
There are two Options properties in EC2 and I'll have to add a patch to disambiguate them to get both autogenerated correctly:

Potential property conflict: ec2 Options
    AWS::EC2::TransitGatewayAttachment.Options: ['ApplianceModeSupport', 'DnsSupport', 'Ipv6Support']
    AWS::EC2::TransitGatewayMulticastDomain.Options: ['AutoAcceptSharedAssociations', 'Igmpv2Support', 'StaticSourcesSupport']

**Comment by markpeek** [comment]
Thank you for the Issue. Fixed via e779387. Renamed to [MulticastDomainOptions](https://github.com/cloudtools/troposphere/blob/main/troposphere/ec2.py#L2493).
