### ISSUE TITLE
AWS::Events::Rule does NOT support implemented Tags attribute through CloudFormation

### ISSUE THREAD

**Issue by ilons** [cloudtools/troposphere#2203]
As of today CloudFormation does not support the `Tags` attribute for [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html), making any resource including this to fail the stack update.

There is an open request for this on the CloudFormation Roadmap: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/358

However the actual resource in AWS support tags: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-tagging.html

This is related to https://github.com/cloudtools/troposphere/issues/2151 where this was asked for and implemented in [4.4.0](https://github.com/cloudtools/troposphere/releases/tag/4.4.0).

**Comment by markpeek** [comment]
@ilons thank you for the issue. Confirmed it causes rollbacks and remove it for now.

**Comment by ilons** [comment]
> @ilons thank you for the issue. Confirmed it causes rollbacks and remove it for now.

Great, thanks for the swift reply, then I can soon remove the shim I'm using :joy:

**Comment by markpeek** [comment]
Fix is in [Release 4.5.2](https://github.com/cloudtools/troposphere/releases/tag/4.5.2)
