### ISSUE TITLE
AWS::ECS::TaskSet.LoadBalancer shadows AWS::ECS::Service.LoadBalancer

### ISSUE THREAD

**Issue by sterwill** [cloudtools/troposphere#2206]
When I upgraded troposphere recently, `troposphere.ecs.LoadBalancer` lost its `LoadBalancerName` attribute, which is necessary for classic ELB support.  The CloudFormation docs for [AWS::ECS::Service LoadBalancer](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-loadbalancer.html) still list `LoadBalancerName`, so it looked like a troposphere issue.  The comment on the class gave me a clue:

    class LoadBalancer(AWSProperty):
        """
        `LoadBalancer <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskset-loadbalancer.html>`__
        """

It looks like the `AWS::ECS::TaskSet.LoadBalancer` is getting used to generate this type, although I would expect `AWS::ECS::Service.LoadBalancer` to map to that class instead (and maybe `TaskSetLoadBalancer` handles the other one?).  I pulled the CloudFormation metadata archive and the service descriptions seem to confirm it.

I didn't submit a PR because I'm not sure how to handle a change like this in troposphere, since it has some back-compat implications.

**Comment by markpeek** [comment]
Thank you for the issue. I see this conflict when the code is generated:

Potential property conflict: ecs LoadBalancer
    AWS::ECS::Service.LoadBalancer: ['ContainerName', 'ContainerPort', 'LoadBalancerName', 'TargetGroupArn']
    AWS::ECS::TaskSet.LoadBalancer: ['ContainerName', 'ContainerPort', 'TargetGroupArn']
    
I'll have to decide whether to delete TaskSet.LoadBalancer to prefer Service.LoadBalancer or perhaps rename the TaskSet one.

**Comment by markpeek** [comment]
This has been released in [4.5.3.](https://github.com/cloudtools/troposphere/releases/tag/4.5.3)
