### ISSUE TITLE
CloudFormation General Templates

### ISSUE THREAD

**Issue by morphf** [cloudtools/troposphere#2208]
I would like to be able to get General CloudFormation Templates for all [AWS Resource Types](https://github.com/cloudtools/troposphere/blob/master/resources_aws.md).
The Template should have placeholder names and all Properties with placeholder values (for example arn format).
Is there a way to do it currently?

**Comment by markpeek** [comment]
This is outside the scope of troposphere and would not give you the results you would want. Would be best to parse and use the [CloudFormation resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as a starting point.
