### ISSUE TITLE
404 while accessing the troposphere module docx

### ISSUE THREAD

**Issue by yuv24793** [cloudtools/troposphere#2213]
Reference
https://troposphere.readthedocs.io/en/latest/_modules/troposphere/wafv2.html#

We were able to access the troposphere module documentation a while ago and the same link throws 404 now.

The permalinks load the same page (https://troposphere.readthedocs.io/en/latest/apis/troposphere.html#troposphere-wafv2-module)

Example
<img width="398" alt="image" src="https://github.com/cloudtools/troposphere/assets/64849397/cc5f1014-32de-4629-aa5a-5213dcda027a">

Please let us know if the documentation URL has been updated.

Thank you !

**Comment by markpeek** [comment]
Thank you for letting me know. This should be fixed now via 04904de3c61ae7c18739f6443be336329a6253bb
