### ISSUE TITLE
Add "EVENT" as accepted type in trigger_type_validator

### ISSUE THREAD

**Issue by praveen0609** [cloudtools/troposphere#2215]
Please update the trigger_type_validator for AWS Glue to have "EVENT" as an accepted trigger type.

**Comment by markpeek** [comment]
Thank you for the issue. Adds EVENT as an allowed value for [Glue::Trigger.Type](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-type).
