### ISSUE TITLE
Feature Request : Support for AWS CodePipeline V2 in troposphere

### ISSUE THREAD

**Issue by MozammilMinhajTR** [cloudtools/troposphere#2217]
Around oct last year, AWS announced support for v2 type of code pipeline which has more flexibility and options to dynamically pass parameters for given run.

> As of writing, troposphere is missing v2 option, so raising a feature req if someone can get this our ASAP, it would be great!

[AWS CodePipeline supports parameterized pipelines (amazon.com)](https://aws.amazon.com/about-aws/whats-new/2023/10/aws-codepipeline-parameterized-pipelines/)

[AWS::CodePipeline::Pipeline - AWS CloudFormation (amazon.com)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html#cfn-codepipeline-pipeline-pipelinetype)

@markpeek

**Comment by MozammilMinhajTR** [comment]
@markpeek

**Comment by markpeek** [comment]
Likely this was added in this [commit](https://github.com/cloudtools/troposphere/pull/2210/files#diff-26746995a8ddb94b619ff6a7a53218bd1ee422163857767d795810624730459a) but not released yet. Is this what you're looking for?

**Comment by MozammilMinhajTR** [comment]
> Likely this was added in this [commit](https://github.com/cloudtools/troposphere/pull/2210/files#diff-26746995a8ddb94b619ff6a7a53218bd1ee422163857767d795810624730459a) but not released yet. Is this what you're looking for?

Yeah, that's correct, looking forward to the release to try it out! 
Thanks!

**Comment by MozammilMinhajTR** [comment]
Hi @markpeek,
When can we expect this feature to be out so that we can make use of v2 functionality of aws codepipeline?

**Comment by markpeek** [comment]
Sorry for the delay. Now available in [Release 4.6.0](https://github.com/cloudtools/troposphere/releases/tag/4.6.0).
