### ISSUE TITLE
RDS VPCSecurityGroups must be of type List of String

### ISSUE THREAD

**Issue by robbyt** [cloudtools/troposphere#222]
CF requires the RDS param to be a list. When I set `VPCSecurityGroups` to be a single `Ref` instance, I get this error: `Value of property VPCSecurityGroups must be of type List of String`

**Comment by phobologic** [comment]
What is the value of the Ref that you are trying to submit?  Does it contain a proper list?

Can you give me an example of the code you are using, and the value that is going into the Parameter?

Also what version of troposphere are you using?

The part that I'm having a hard time with understanding at this point is this code *should* catch the fact that you've passed in a Ref:

https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L93

That happens before it even attempts to look at the expected values.

**Comment by markpeek** [comment]
This should be fixed as the example RDS_VPC.py uses a Ref() with VPCSecurityGroups.
