### ISSUE TITLE
Valid Canary runtime versions are outdated

### ISSUE THREAD

**Issue by theofilospan** [cloudtools/troposphere#2220]
Hello,

The current Canary runtime versions are outdated. Under `troposphere/validators/synthetics.py` the valid versions are the following:
["syn-nodejs-2.0", "syn-nodejs-2.0-beta", "syn-1.0"]
The versions syn-nodejs-puppeteer-3.5 to syn-nodejs-puppeteer-3.9 were deprecated on January 8, 2024. ([Source](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Library.html)) 

The current valid versions are the following:
* syn-nodejs-puppeteer-4.0
* syn-nodejs-puppeteer-5.0
* syn-nodejs-puppeteer-5.1
* syn-nodejs-puppeteer-6.0
* syn-nodejs-puppeteer-6.1

Let's add them to the valid canary runtime versions and replace the old ones.

**Comment by theofilospan** [comment]
Pull request submitted:
https://github.com/cloudtools/troposphere/pull/2221

**Comment by markpeek** [comment]
Fixed via #2221
