### ISSUE TITLE
CoreNetworkArn missing from Route validation code

### ISSUE THREAD

**Issue by mcgartyd** [cloudtools/troposphere#2224]
CoreNetworkArn is missing from the validate_route function for Class Route in validators/ec2.py.  As a consequence, attempts to create a route with a Core Network endpoint as a target fail validation with a value error:

ValueError: Route: one of the following must be specified: CarrierGatewayId, EgressOnlyInternetGatewayId, GatewayId, InstanceId, LocalGatewayId, NatGatewayId, NetworkInterfaceId, TransitGatewayId, VpcEndpointId, VpcPeeringConnectionId

**Comment by markpeek** [comment]
Thanks. Fixed via 459609a

**Comment by mcgartyd** [comment]
Speedy.  Thanks!
