### ISSUE TITLE
StorageEncrypted attribute support for rds.DBInstance

### ISSUE THREAD

**Issue by mattupstate** [cloudtools/troposphere#223]
See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-storageencrypted

Also doesn't look like the `KmsKeyId` attribute is supported then either.

**Comment by mattupstate** [comment]
Total coincidence that AWS just announced some new RDS cloudformation features today

**Comment by markpeek** [comment]
Added by @fbenz today with #224
