### ISSUE TITLE
Questions about Copilot + Open Source Software Hierarchy

### ISSUE THREAD

**Issue by liaochris** [cloudtools/troposphere#2232]
Hi! My name is Chris and I'm writing a thesis on Open Source Software. I'm trying to collect/validate my data and I have two questions for the maintainers of this project.
1. **Did maintainers of this project receive free github copilot access on June 2022, as maintainers of popular open source projects? And do project maintainers use Copilot?**
The Copilot FAQ says: “GitHub Copilot is free to use for verified students, teachers, and maintainers of popular open source projects. “
If you don't recall, it might be helpful to check if maintainers are currently eligible ([https://github.com/github-copilot/free_signup](https://github.com/github-copilot/free_signup))

2. My thesis is especially focused on understanding hierarchical structures. **Is there a publicly available list of of individuals in this project with maintain or admin access in this project?** I can only back out who has write access by looking at who has merged PRs. 

Happy to chat further if you have questions, and thank you for your time!

**Comment by PatMyron** [comment]
I'll answer briefly, but opening 100+ of these issues on popular Github repositories is not appropriate and I wouldn't open more:
https://github.com/issues?q=is:issue+author:liaochris+copilot

---

1) Idk when but got free access as a maintainer. Tested it and found Copilot's autocompletion suggestions worse than IDEs' status quo
2) You may see some organization members on Github organization pages, but Github teams can't be seen by the public:
https://docs.github.com/en/organizations/organizing-members-into-teams/changing-team-visibility
https://stackoverflow.com/questions/36736062/how-can-i-check-who-has-write-access-to-a-public-organizations-repository-on-gi
https://stackoverflow.com/questions/59009665/how-can-i-see-the-list-of-users-that-have-commit-privileges-to-a-git-repo

**Comment by liaochris** [comment]
Thanks for your response! Would you mind explaining why opening 100+ of these issues is not appropriate, and what might be a better way to collect this information? My intent isn't to spam these projects - the repositories I've opened these issues are the ones in my data, and I'm hoping this research will help better understand Github's policies on copilot + the impact of copilot.

**Comment by PatMyron** [comment]
Professionals' work on StackOverflow/Github/etc, so not the best place for users to spam survey others

These sites run their own wider less-intrusive annual surveys that ask about topics like Copilot:
https://github.blog/2023-11-08-the-state-of-open-source-and-ai/
https://survey.stackoverflow.co/2023/
https://www.jetbrains.com/lp/devecosystem-2023/
Not to say they currently cover every topic meaningfully well (they'd probably count me in Copilot users for trying it), but probably better to reach out to try to work with them first before surveying roguely
