### ISSUE TITLE
Add support for Amazon Timestream for InfluxDB

### ISSUE THREAD

**Issue by rtk-logan-fillo** [cloudtools/troposphere#2239]
A new service "Amazon Timestream for InfluxDB" was recently launched https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-timestream-influxdb-available/

Here are the CloudFormation docs for this service https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-timestream-influxdbinstance.html

This ticket is for adding support in troposphere for this new service.

**Comment by markpeek** [comment]
Added as part of the 170.0.0 spec update 6ea2be2. Will be included in the next release (likely at the end of this week).
