### ISSUE TITLE
CloudFormation now suppports Route 53's Private Hosted Zones

### ISSUE THREAD

**Issue by kjhosein** [cloudtools/troposphere#226]
Hello all - looks like CF now supports private hosted zones:
  http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-vpcs

but realized to my sadness that Troposphere does not.

**Comment by markpeek** [comment]
It supported some parts of hostedzones but I just pushed some additional changes. Check master.

**Comment by kjhosein** [comment]
Mark - thanks for your incredibly fast response to this!

I'm trying the following sort of code:
```
from troposphere import Template
from troposphere.route53 import HostedZone

t = Template()
t.add_version("2010-09-09")
t.add_description(""" test of creating a private DNS zone """)

t.add_resource(HostedZone(
    "DNSZonePrivate",
    Name="example.com",
    VPCs={"VPCId": "foo", "VPCRegion": "us-east-1"},
))
```
but I'm getting this error:
`TypeError: VPCs is <type 'dict'>, expected [<class 'troposphere.route53.HostedZoneVPCs'>]`

Am I doing something wrong?

**Comment by markpeek** [comment]
Here's the snippet I used for my testing last night:
```
t.add_resource(HostedZone("DNS",
    HostedZoneConfig=HostedZoneConfiguration(
        Comment="My hosted zone for example.com",
    ),
    Name="example.com",
    VPCs=[
      HostedZoneVPCs(VPCId="vpc-abcd1234", VPCRegion="ap-northeast-1"),
      HostedZoneVPCs(VPCId="vpc-efgh5678", VPCRegion="-west-2"),
    ],
    HostedZoneTags=Tags(
      SampleKey1="SampleValue1",
      SampleKey2="SampleValue2",
    ),
))
```
Note: I was debating about using positional parameters (below) for HostedZoneVPCs but left the above syntax:
   HostedZoneVPCs("vpc-abcd1234", "ap-northeast-1")

I never know if new parameters will be added so at least it safeguards it for future use.

**Comment by kjhosein** [comment]
Mark - Fantastic, thank you! Works like a charm.

**Comment by naveenpolamreddi** [comment]
Can we create a public hosted zone using troposphere..? If so can you please give me a snippet on how to do that where the hosted zone should log on the query calls to the cloudwatch log group.
