### ISSUE TITLE
Lambda environment validator prevents the use of the TZ variable

### ISSUE THREAD

**Issue by epequeno** [cloudtools/troposphere#2260]
The environment variable validator lists `TZ` as a reserved variable and so raises a ValueError if you try to use it in a template: https://github.com/cloudtools/troposphere/blob/1de57d3e0d3b6d6561bd9c349011f3ee6ac1f363/troposphere/validators/awslambda.py#L72

The `TZ` variable is unreserved as documented here: https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html

I've confirmed that creating a stack with the `TZ` variable set does not produce any CloudFormation or Lambda errors.

**Comment by markpeek** [comment]
Hmmm, must have changed it at some point. Fixed via 40028ad
Thanks for the issue.
