### ISSUE TITLE
Missing constants - AWS ElastiCache m7g nodes

### ISSUE THREAD

**Issue by javid-abd** [cloudtools/troposphere#2261]
Hi,

Low priority, just wanted to point out that AWS Graviton3-based M7g nodes are missing
<img width="872" alt="Screenshot 2024-08-13 at 14 53 51" src="https://github.com/user-attachments/assets/0e920d51-5418-46fb-a46f-fe6905035934">

**Comment by markpeek** [comment]
Fixed via #2262
