### ISSUE TITLE
AWS::Chatbot::SlackChannelConfiguration LoggingLevel validation

### ISSUE THREAD

**Issue by neochrome** [cloudtools/troposphere#2264]
Hi!
I think there might be an error in the validation of the `LoggingLevel` property of the `AWS::Chatbot::SlackChannelConfiguration`. Currently the allowed values are `ERROR`, `INFO`, `NODE` - but that last one should be `NONE` according to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-chatbot-slackchannelconfiguration.html

**Comment by markpeek** [comment]
Thank you for the issue. Fixed.
