### ISSUE TITLE
Cannot create bucket with bucket name with periods e.g. "abc.pqr.io"

### ISSUE THREAD

**Issue by axitkhurana** [cloudtools/troposphere#231]
Buckets with names of domains like "abc.pqr.io" are legal and help in static hosting of pages on S3.

Troposphere raises `ValueError: Name "abc.pqr.io" not alphanumeric` because of the regex `valid_names = re.compile(r'^[a-zA-Z0-9]+$')` [here](https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L42).

Can we allow periods in names? (Maybe only for S3 buckets?)

**Comment by phobologic** [comment]
Yep, seems like a bug - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-name

Should allow periods, wonder if that got added recently or if we just missed it the first time through.

**Comment by phobologic** [comment]
Oh, wait - actually, are that line you're providing checks the CloudFormation resource name.  The bucket name is a separate parameter - see that link I sent you.

**Comment by phobologic** [comment]
If you still can't make it work after providing the BucketName as it's own parameter, let us know... and if you could provide an example that is breaking for you, we can dive into it more.

**Comment by axitkhurana** [comment]
Thanks for the quick response, looks like BucketName should work, will reopen if it doesn't.

Thanks!

**Comment by markpeek** [comment]
For reference, dup of #206 which has an example.

**Comment by axitkhurana** [comment]
Thanks @markpeek, sorry about the duplicate.
