### ISSUE TITLE
Missing required property error check isn't working

### ISSUE THREAD

**Issue by mschurenko** [cloudtools/troposphere#235]
##### Problem:
It seems that the required property error check for resources is not working as per the example in the README.

##### Troposphere Version: 
0.7.2
##### OS:
OS X 10.10.3

##### Steps:
```
>>> from troposphere import Template
>>> import troposphere.ec2 as ec2
>>> t = Template()
>>> t.add_resource(ec2.Instance("ec2instance", ImageId="ami-3bcc9e7e"))
<troposphere.ec2.Instance object at 0x10b8cf310>
>>> print(t.to_json())
```
##### Expected result:
```
ValueError: Resource InstanceType required in type AWS::EC2::Instance
```
##### Actual Result:
```
{
    "Resources": {
        "ec2instance": {
            "Properties": {
                "ImageId": "ami-3bcc9e7e"
            },
            "Type": "AWS::EC2::Instance"
        }
    }
}
```

**Comment by phobologic** [comment]
It looks like this is due to the fact that InstanceType is no longer necessary!

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype

Updating the README - pushing the change now.  Thanks!
