### ISSUE TITLE
Tag "PropagateAtLaunch" property is missing

### ISSUE THREAD

**Issue by amos-stan** [cloudtools/troposphere#244]
I started getting "PropagateAtLaunch not found in properties" error from stack deployment.
According to http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-tags.html this is a required property.
If I follow the code correctly then it should be added at https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L338.
I'll try to provide a pull request later (must leave now).
Thanks.

**Comment by markpeek** [comment]
There is a specialized Tag you can use here:
https://github.com/cloudtools/troposphere/blob/master/troposphere/autoscaling.py#L25

And example usage here (just note how Tag was imported at the top of the file):
https://github.com/cloudtools/troposphere/blob/master/examples/Autoscaling.py#L219

**Comment by amos-stan** [comment]
Thanks.
I keep falling into the trap of trusting the code generated by cfn2py...
