### ISSUE TITLE
Using VolumeType in a volume configuration for a Opsworks layer gives a null value

### ISSUE THREAD

**Issue by dggc** [cloudtools/troposphere#245]
If I use the following declaration in troposphere (note the "VolumeType"="standard"):

    MySQLLayer = template.add_resource(opsworks.Layer(
        "MySQLLayer",
        StackId=Ref(OpsworksStack),
        Type="custom",
        Shortname="mysql",
        EnableAutoHealing=True,
        AutoAssignElasticIps=False,
        AutoAssignPublicIps=True,
        Name="MySQL",
        CustomSecurityGroupIds=[Ref(MySQLSecurityGroup)],
        CustomRecipes=opsworks.Recipes(
            Setup=["mysql::server"],
        ),
        VolumeConfigurations=[opsworks.VolumeConfiguration(MountPoint="/mnt/mysql", NumberOfDisks=1, Size=4, Volume>>>Type="standard")],    ))

The generated json is like this ("VolumeType": null):

        "MySQLLayer": {
            "Properties": {
                "AutoAssignElasticIps": "false",
                "AutoAssignPublicIps": "true",
                "CustomRecipes": {
                    "Setup": [
                        "mysql::server"
                    ]
                },
                "CustomSecurityGroupIds": [
                    {
                        "Ref": "MySQLSecurityGroup"
                    }
                ],
                "EnableAutoHealing": "true",
                "Name": "MySQL",
                "Shortname": "mysql",
                "StackId": {
                    "Ref": "OpsworksStack"
                },
                "Type": "custom",
                "VolumeConfigurations": [
                    {
                        "MountPoint": "/mnt/mysql",
                        "NumberOfDisks": 1,
                        "Size": 4,
                        "VolumeType": null  
                    }
                ]
            },
            "Type": "AWS::OpsWorks::Layer"
        },

**Comment by markpeek** [comment]
The fix I just pushed should resolve this issue. Thanks for reporting it.

**Comment by dggc** [comment]
Cool, thank you!
