### ISSUE TITLE
BaseAWSObject has wrong regex for valid_names, specifically for SQS

### ISSUE THREAD

**Issue by greenscar** [cloudtools/troposphere#246]
From AWS:
Please enter a name for your new queue. Queue names must be 1-80 characters in length and be composed of alphanumeric characters, hyphens (-), and underscores (_). Your queue will be created in the US West (Oregon) region.

However, in BaseAWSObject:
valid_names = re.compile(r'^[a-zA-Z0-9]+$')

So using troposphere, I cannot include - or _ in my SQS names even though it's valid.

**Comment by markpeek** [comment]
Those are two distinct things. What you cited is the naming restriction for CloudFormation resources which is much stricter than the an SQS QueueName. The QueueName is specified here as a basestring:
https://github.com/cloudtools/troposphere/blob/master/troposphere/sqs.py#L29

There probably is an issue to improve the vaidation of that name. But what you're wanting is probably something like this (untested):
```
from troposphere.sqs import Queue

mydeadletterqueue = t.add_resource(
    Queue("CFQueueWithoutUnderscore", QueueName="SQS-Queue-With-Underscores"))
```

**Comment by greenscar** [comment]
@markpeek : Go test your code. I spent 3 hrs yesterday debugging SQS queue creation because although AWS does allow - and _ in the name, when I use troposphere to create a queue:


Traceback (most recent call last):
  File "scripts/full_envt_setup.py", line 260, in <module>
    generator.run(env_name)
  File "/Users/jamess/workspaces/cloudcruiser/bravo_aws_infrastructure/BravoInfrastructure/bravoinfra/service/Generator.py", line 66, in run
    optionalFeatures.configureFeatures(self.serviceName, self.optionalServices)
  File "/Users/jamess/workspaces/cloudcruiser/bravo_aws_infrastructure/BravoInfrastructure/bravoinfra/service/OptionalFeatures.py", line 25, in configureFeatures
    self.configureSQS(service_name, optionals[option])
  File "/Users/jamess/workspaces/cloudcruiser/bravo_aws_infrastructure/BravoInfrastructure/bravoinfra/service/OptionalFeatures.py", line 37, in configureSQS
    self.parameters.addSQSQueueName(queue_name)
  File "/Users/jamess/workspaces/cloudcruiser/bravo_aws_infrastructure/BravoInfrastructure/bravoinfra/service/ServiceParameters.py", line 52, in addSQSQueueName
    ConstraintDescription="Can contain only ASCII characters."
  File "/Library/Python/2.7/site-packages/troposphere/__init__.py", line 165, in __init__
    super(AWSDeclaration, self).__init__(title, **kwargs)
  File "/Library/Python/2.7/site-packages/troposphere/__init__.py", line 43, in __init__
    raise ValueError('Name "%s" not alphanumeric' % title)
ValueError: Name "dev-UpdatePipelineQueue" not alphanumeric

**Comment by greenscar** [comment]
NOTE: If I remove the - it works fine. This should not be closed.

**Comment by markpeek** [comment]
Sure seems to work for me...here's the quick test based on the code I posted above:

```
$ cat q.py
from troposphere import Template
from troposphere.sqs import Queue

t = Template()
queuetest = t.add_resource(
    Queue("CFQueueWithoutUnderscore", QueueName="SQS-Queue-With-Underscores"))
print t.to_json()

$ python q.py
{
    "Resources": {
        "CFQueueWithoutUnderscore": {
            "Properties": {
                "QueueName": "SQS-Queue-With-Underscores"
            },
            "Type": "AWS::SQS::Queue"
        }
    }
}
```
Can you distill your code down to a simple repro?

**Comment by greenscar** [comment]
Thanks Mark. Based upon what you have provided, I'm going to say the code I was handed was implemented wrong. A couple of java developers create a base system and handed it to me so it's far more complicated than it should be. Feel free to close this ticket and let's assume my code is bad. Should I find out more I can definitely re comment.

**Comment by markpeek** [comment]
np...good luck unwinding that code. :-)
