### ISSUE TITLE
Need to include AWS::Cloudformation::Init - commands

### ISSUE THREAD

**Issue by slimg00dy** [cloudtools/troposphere#250]
See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-commands

Here is a short snippet.

**Comment by markpeek** [comment]
You can include AWS::CloudFormation::Init in your stacks like this (note the use of python dicts):
https://github.com/cloudtools/troposphere/blob/master/examples/CloudFormation_Init_ConfigSet.py

**Comment by slimg00dy** [comment]
Thanks, I should have checked that.
