### ISSUE TITLE
No OpsWorks  Load Based Scaling

### ISSUE THREAD

**Issue by obiwanakin** [cloudtools/troposphere#254]
Hey, there isn't a way to make OpsWorks scale with load. Generally, in the json template, CloudFormation would be looking for an instance with a property of
``` "AutoScalingType":"load" ```
but there isn't an "AutoScalingType" property in opsworks.py. Instead, there is a 
"TimeBasedAutoScaling" property.

**Comment by phobologic** [comment]
Can you point at the property/resource you're talking about in the CloudFormation Template Reference?  I'm not sure which feature you're talking about here.

https://github.com/cloudtools/troposphere/blob/master/troposphere/opsworks.py#L103 exists, though not sure that's what you mean.

**Comment by phobologic** [comment]
Oh, I think I've figured out what you mean - is this it?

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-instance.html#cfn-opsworks-instance-autoscalingtype

Specifically on the Instance Resource?

**Comment by obiwanakin** [comment]
Yes, That's it! Give me a few min and I'll post a fix.

**Comment by markpeek** [comment]
Fix merged. Thanks.
