### ISSUE TITLE
Cloudwatch.Alarm() does not throw error on incorrect AlarmActions property

### ISSUE THREAD

**Issue by obiwanakin** [cloudtools/troposphere#256]
Cloudformation expects the AlarmAction property of AWS::CloudWatch::Alarm to be a list of strings, but troposphere.cloudwatch.Alarm() allows a string.

**Comment by markpeek** [comment]
The code and an example use a list of strings. Do you have sample code exhibiting this error you can share?

**Comment by phobologic** [comment]
Closing this since we haven't gotten a reply.  @obiwanakin - if you have an example let us know and we can re-open this.  Thanks!
