### ISSUE TITLE
troposphere documenation

### ISSUE THREAD

**Issue by baniobloom** [cloudtools/troposphere#258]
Perhaps I missed it, but I can't find documentation that tells me how to use troposphere.  There are some simple examples in the README but not much more.  I also saw the google group, but that is more a forum for specific questions.  If such a resource exists could you please point me to it?
Thanks,

**Comment by phobologic** [comment]
Hey @baniobloom - troposphere is basically just a python implementation of CloudFormation, with some added benefits.  That means that anything you read in the CloudFormation documentation can be done in troposphere.  But at it's core, that's just creating the CloudFormation templates.

There is the 'cfn' tool, which can be used to take those templates and push them into Cloudformation, bringing up the stacks defined in the templates.  You should check out the help on that tool.

Another project that handles more of the higher level things is stacker - you can read more about it here: http://stacker.readthedocs.org/en/latest/ and here's the github repo: https://github.com/remind101/stacker

Hope that helps!
