### ISSUE TITLE
Inconsistent letter case

### ISSUE THREAD

**Issue by nikolay** [cloudtools/troposphere#266]
`AWSObject`, `AWSProperty`, and so on, but `SslConfiguration`?!

**Comment by markpeek** [comment]
AWSObject and AWSProperty are internal troposphere names. Something like SslConfiguration is to mirror the spelling from AWS and the CloudFormation team.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opsworks-app-sslconfiguration.html
