### ISSUE TITLE
Trying to import create lambda function - clashes with Python lambda reserved word

### ISSUE THREAD

**Issue by hngkr** [cloudtools/troposphere#268]
Hi,

I'm trying to create a lambda function in Troposphere, but I'm stuck importing the module:

from troposphere import ec2, rds, lambda

Seems that the package file lambda.py might be a bad name, as Python throws a SyntaxError at the sight of what it expects to be the keyword lambda in Python.

Love CloudFormation a lot, BTW.

/ H

**Comment by markpeek** [comment]
Oh my, I did not catch that issue when merging it. Thanks for reporting it. I guess we need some tests for this subsystem. @philtay do you have a suggested rename? awslambda? llambda?

**Comment by markpeek** [comment]
Just pushed a change which renamed lambda->awslambda (aligning with how boto named it).

**Comment by philtay** [comment]
oooops... sorry about that

**Comment by msirull** [comment]
Can this fix be pushed to PyPi?

**Comment by markpeek** [comment]
@msirull Release 1.1.1 was just pushed to PyPI. Thanks for the reminder.
