### ISSUE TITLE
ECS resources support

### ISSUE THREAD

**Issue by axltxl** [cloudtools/troposphere#271]
As of June 12th 2015, according to [this source](https://forums.aws.amazon.com/ann.jspa?annID=3096), CloudFormation now supports creation of ECS resources. 

It'd be nice that troposphere had support for this as well, it seems not to be that complicated as CF has only implemented three ECS resources into their specification, which are the following: 

* [`AWS::ECS::Cluster`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html) 
* [`AWS::ECS::Service`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html)
* [`AWS::ECS::TaskDefinition`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html)

Cheers :wine_glass:

**Comment by markpeek** [comment]
Please upgrade to [troposphere release 1.1.0](https://github.com/cloudtools/troposphere/releases/tag/1.1.0) or via [pypi](https://pypi.python.org/pypi/troposphere/1.1.0) which included ECS support via #259.

**Comment by axltxl** [comment]
Thanks a lot for the update! :+1: keep up the good work!
