### ISSUE TITLE
Wrong prop name in rds.OptionGroup()

### ISSUE THREAD

**Issue by tamas7** [cloudtools/troposphere#274]
The `OptionGroupConfigurations` prop should be named `OptionConfigurations` according to [AWS docs] (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html).

Otherwise template creation will fail with:
> Encountered unsupported property OptionGroupConfigurations

**Comment by markpeek** [comment]
@tamas7 I pushed a proposed fix onto a branch if you want to test and validate.

**Comment by tamas7** [comment]
@markpeek Could not get the unit test running, it fails with:
> NameError: name 'basestring' is not defined

The changes made in `rds.py` does solve the issue, though.

**Comment by markpeek** [comment]
Thanks for the verification. Odd you got that error as basestring is a builtin type:
```
$ python
Python 2.7.9 (default, Dec 19 2014, 06:00:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> basestring
<type 'basestring'>
```
And to run the tests I use ```python setup.py test```.

**Comment by tamas7** [comment]
Got my Python versions mixed up. The relevant output line is:

    test_optiongroup (tests.test_rds.TestRDS) ... ok

Thanks!

**Comment by markpeek** [comment]
Fix pushed. Thanks for reporting and testing the fix.
