### ISSUE TITLE
Unable to pass Cluster name as String

### ISSUE THREAD

**Issue by bpholt** [cloudtools/troposphere#281]
When using the ECS `Service` class, I'm unable to pass a simple string name to the `Cluster` property. For example:

    service = Service('Service',
                      Cluster='cluster',
                      DesiredCount=2,
                      LoadBalancers=[ecs_load_balancer],
                      Role='ecsServiceRole',
                      TaskDefinition=Ref(task_definition))

If I do so, I get a type error:

    TypeError: Cluster is <type 'str'>, expected [<type 'basestring'>, <class 'troposphere.Ref'>]

I don't understand why `'Cluster': ([basestring, Ref], False)` is the right type definition for the property ([`ecs.py:23`](https://github.com/cloudtools/troposphere/blob/78e7a075d461d706661fb5a8156df9a5b9ae7da4/troposphere/ecs.py#L23)). It appears that when passed a `Ref`, the type checking is simply ignored (see [`__init__.py:93`](https://github.com/cloudtools/troposphere/blob/78e7a075d461d706661fb5a8156df9a5b9ae7da4/troposphere/__init__.py#L93)), so it works in that case. If a string is passed, then it carries on to [`__init__.py:102-105`](https://github.com/cloudtools/troposphere/blob/78e7a075d461d706661fb5a8156df9a5b9ae7da4/troposphere/__init__.py#L102-L105), where it expects the passed value to be a list. Since it’s not, it raises a `TypeError`.

I noticed there are several other places where the `([basestring, Ref], False)` syntax is used both in ECS and elsewhere, and I’m new to Python, so I’m probably missing something obvious. 

We have separate CloudFormation templates for our clusters and the services running on the clusters, so in the service template I’m not sure how I can obtain something `Ref`erenceable to avoid passing the plain string.

**Comment by markpeek** [comment]
I could only take a quick look at it right now but it appears (based on [this](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-cluster)) it should be:
```
'Cluster': (basestring, False),
```
I'll be able to take a closer look over the weekend. Feel free to try this and let me know if it works for you.

**Comment by bpholt** [comment]
When I changed it it to 

    'Cluster': (basestring, False),

it worked, but I assumed that would cause problems when passing in a `Ref` since 78e7a075d461d706661fb5a8156df9a5b9ae7da4 specifically mentioned them in its commit message. (Making that change basically reverts 78e7a075d461d706661fb5a8156df9a5b9ae7da4.) On second thought, though, maybe not, since the type checking ignores `Ref`s. I’ll give it a try tomorrow. Thanks!

**Comment by bpholt** [comment]
I tried passing a `Ref` for `Cluster` after changing the type back to `'Cluster': (basestring, False)` and it worked, so it looks like reverting 78e7a075d461d706661fb5a8156df9a5b9ae7da4 would fix the problem. @philtay, do you remember why that change was made?

**Comment by philtay** [comment]
Have a look at the "Example", bottom of [doc page](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html). They use a Ref.

**Comment by bpholt** [comment]
They use a `Ref` when the cluster is declared elsewhere in the same template. In this case, the cluster is defined in a different template altogether and so a `Ref` is invalid.

I’m working around this right now by adding a `Parameter` to my stack with a single-item list of values and a matching default, and then using a `Ref` to the parameter, but that’s obviously a hack. :-)

**Comment by markpeek** [comment]
Thanks for the testing. Fix pushed.

**Comment by bpholt** [comment]
Thanks!
