### ISSUE TITLE
Unable to set StringValue on ObjectField in DataPipeline

### ISSUE THREAD

**Issue by grubernaut** [cloudtools/troposphere#283]
I'm unable to properly set a StringValue inside of an ObjectField resource when creating a DataPipeline. 

This error gets returned from CloudFormation:
```
Value of property StringValue must be of type String
```

Snippit of troposphere code:
```
        schedule = PipelineObject(
            Fields=[ObjectField(
                Key='type',
                StringValue=['Schedule']
            ), ObjectField(
                Key='occurences',
                StringValue=['2']
            ), ObjectField(
                Key='startAt',
                StringValue=['FIRST_ACTIVATION_DATE_TIME']
            ), ObjectField(
                Key='period',
                StringValue=['1 day']
            )],
            Id= 'S3_Schedule',
            Name='S3Schedule'
        )
```

I believe this is due to @philtay's latest commit (https://github.com/cloudtools/troposphere/commit/a1957fb04118ce13f2cb37a52bc93718eed0ae41), which now expects StringValue to be an array. 

If I specify the StringValue as a string and not an array, troposphere fails to build the cloudformation as well:
```
TypeError: StringValue is <type 'str'>, expected [<type 'basestring'>, <class 'troposphere.Ref'>]
```

I could, however, be declaring the ObjectField's completely wrong.

**Comment by philtay** [comment]
It looks like the same problem of #281. `[<type 'basestring'>, <class 'troposphere.Ref'>]` should allow both `Ref`s and strings. Am I missing something @markpeek? Probably yes, but no time to check right now.

**Comment by markpeek** [comment]
@grubernaut thank you for filing the issue. I reverted the change.

@philtay sorry I didn't catch this issue originally. The code [here](https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L102) handles allowing Ref() in a non-list context. Previously a list "[]" expected type was the only thing supported without any element type checking. Later on I added the ability to check list elements as well in this [commit](https://github.com/cloudtools/troposphere/commit/be6a78d9bd73ec3bd0b824fa7dc03ffd2a793b13) which allows for things like: ```[basestring, Ref]``` or ```[basestring, AWSHelperFn]```.
