### ISSUE TITLE
Add of Metadata property to the template anatomy?

### ISSUE THREAD

**Issue by rackerroush** [cloudtools/troposphere#286]
This might be a some what recent addition to templates.  I was hoping to add metadata as a section as detailed in the doc in this link.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html

We are hoping to use that section for helping to track versions once they are deployed.

It would look something like this:

"Metadata": {
"Version": "V1.0",
"LastUpdated": "Jan 1st 2015",
"UpdatedBy": "First Last",
"Comments": "Initial Draft"
},

**Comment by markpeek** [comment]
Please give the patch above a try to see if it meets your needs.

**Comment by rackerroush** [comment]
That update seems to be working great!
Thank you for tackling this so quickly.
Much appreciated! =)

**Comment by markpeek** [comment]
No problem, thanks for reporting the issue. This just got pushed out in v1.1.2.
