### ISSUE TITLE
ValueError: Name "sg_name_with_underscore" not alphanumeric for SG

### ISSUE THREAD

**Issue by abdulirfan3** [cloudtools/troposphere#287]
Hello,

I think this might be an issue in troposphere(please correct me if i am wrong).  While working on a Security group, our naming convention dictates to have underscore.  But when i use that with troposphere i get error that states "ValueError: Name "sg_name_with_underscore" not alphanumeric" but that is supported by AWS(see below for a screenshot of the console that shows an SG name that have underscore).  How do we overcome this ??

![image](https://cloud.githubusercontent.com/assets/11415069/8967337/d0dc5788-35fb-11e5-8102-99d0015774d9.png)
 

Here is the simple test/code that fails
from troposphere import Template
import troposphere.ec2 as tec2

template = Template()
gd = "allow access to my instance"
sg = "Pub_HDP_SG"
tsg2 = tec2.SecurityGroup(sg)
tsg2.GroupDescription = gd
tsg2.SecurityGroupIngress = [
    tec2.SecurityGroupRule(
        IpProtocol="tcp",
        FromPort="22",
        ToPort="22",
        CidrIp="10.10.10.10/0",
    )]

template.add_resource(tsg2)
print template.to_json()

Below is the error..

Traceback (most recent call last):
  File "<pyshell#80>", line 1, in <module>
    execfile('test.py')
  File "test.py", line 10, in <module>
    tsg2 = tec2.SecurityGroup(sg)
  File "C:\Python27\lib\site-packages\troposphere\__init__.py", line 43, in __init__
    raise ValueError('Name "%s" not alphanumeric' % title)
ValueError: Name "Pub_HDP_SG" not alphanumeric

**Comment by phobologic** [comment]
Closing this per the discussion on the cloudtools-dev group.  Keep in mind: A Cloudformation resource name is not the same thing as the name of the thing it creates.  Cloudformation resource names can't have underscores.
