### ISSUE TITLE
troposphere compiles, cloudformation feedback exception

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#291]
My troposphere script runs just fine,

however pushing it into cloudformation via CLI I get this

```log
A client error (InsufficientCapabilitiesException) occurred when calling the CreateStack operation: Requires capabilities : [CAPABILITY_IAM]
```

**Comment by phobologic** [comment]
That is an error from the AWS client - you need to pass the correct capabilities for your stack - see the           [--capabilities <value>] argument to aws cloudformation

**Comment by markpeek** [comment]
Another reference for which resources require it: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html

**Comment by BardiaAfshin** [comment]
that was the case, feel free to close issue.
