### ISSUE TITLE
Adding Metadata to an existing ec2.Instance instance generates an AttributeError

### ISSUE THREAD

**Issue by dlongman** [cloudtools/troposphere#298]
Using the [example](https://github.com/cloudtools/troposphere/blob/master/examples/CloudFormation_Init_ConfigSet.py) it is possible to set the Metadata for an ec2 instance when it is initialised. However you get an exception if you try to define the Metadata property after the instance has been initialised, for e.g.

```Python
myInstance = ec2.Instance('MyEC2Instance')
myInstance.Metadata = cloudformation.Metadata(...)
``` 
generates the following error:
`AttributeError: AWS::EC2::Instance object does not support attribute Metadata`

All the other parameters in the example (i.e. UserData, KeyName, ImageId, InstanceType, etc) can be set on an existing instance object. 

Is there a reason why setting the Metadata property is not supported in this way? I can set the same Metadata against the Template without error.

**Comment by markpeek** [comment]
Sounds like a bug. At first glance I think it could be fixed by pushing the various check/set of self.attributes into self.__setattr__(). I'll have to look when I have more time. Thanks for reporting it.

**Comment by markpeek** [comment]
@dlongman please try this (quick) [patch](https://github.com/cloudtools/troposphere/commit/7445ab6c638c1345feef2f63cbbcfbc7b804eb8d) to see if it works with your use case.

**Comment by dlongman** [comment]
@markpeek that patch fixes the issue I was seeing, thanks!

**Comment by dlongman** [comment]
sorry closed by mistake - probably should wait until the patch is merged :-)

**Comment by markpeek** [comment]
Merged.
