### ISSUE TITLE
How to create SecurityGroupIngress

### ISSUE THREAD

**Issue by dinilatgit** [cloudtools/troposphere#299]
Hi,
    This is mostly not a bug but how to go about it.
How can we add SecurityGroupIngress or SecurityGroupEgress referring to SecurityGroup created part of the same stack.
My requirement is to loop through rules(how many ever are input) and create them referring to the SG and not defining the rules inline with the SG as shown in examples.
I am trying something like:
```
   for r in rules:
      t.add_resource(SecurityGroupEgress=[
           SecurityGroupRule(
           IpProtocol=r[1],
           FromPort=r[2],
           ToPort=r[3],
           CidrIp=r[4],
           )
           ],
           GroupId=Ref(sg_name)
           )
```

I tried variations like
```
   t.add_resource(SecurityGroupEgress[
           SecurityGroupRule(
```

OR
```
 t.add_resource(SecurityGroupEgress(
           SecurityGroupRule(
           IpProtocol=r[1],
 ```
But am not able to find a way to declare/define SecurtiyGroupIngress or SecurtiyGroupEgress as a resource. 
I have to add the rules separately after defining the SG since I have to run loops.

Please help me what I might be missing.

Also, more of a generic question, what is the best way to use Python loops with troposphere. Obvious ways are in play since loops work for distinct add_resource and variable assignment works within add_resource but there's no provision(expectedly) to run loops within add_resource.

Regards.

**Comment by AkhterAli** [comment]
I haven't figured this out yet.  Although I don't know why you want to use a for loop and declare the security group rules with list parameters.

Also this doesn't look right.

```python
t.add_resource(SecurityGroupEgress=[
    SecurityGroupRule(
        IpProtocol=r[1],
        FromPort=r[2],
        ToPort=r[3],
        CidrIp=r[4],
        )
    ],
    GroupId=Ref(sg_name)
)
```

Shouldn't it be this?

```python
t.add_resource(SecurityGroupEgress=[
    SecurityGroupRule(
        IpProtocol=r[1],
        FromPort=r[2],
        ToPort=r[3],
        CidrIp=r[4],
        ),
    GroupId=Ref(sg_name) 
    ]
)

**Comment by phobologic** [comment]
See the SecurityGroupIngress and SecurityGroupEgress resource types in troposphere:

https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py#L236

For an example, see this blueprint from stacker:

https://github.com/remind101/stacker/blob/master/stacker/blueprints/asg.py#L95

The way you're doing for loops is the right way to do it - there's no way, in Cloudformation, to do a for loop really, so you won't find it in troposphere itself.

**Comment by phobologic** [comment]
It's worth noting that the SecurityGroup[Ingress|Egress] `resources` (https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py#L236) are different than the SecurityGroupRule `property` (https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py#L273).

The former is a resource, and used for adding rules to an existing SecurityGroup (either created in the template separately, or previously created) and the latter is for adding rules at the creation time of the security group (a use of that can be seen here: https://github.com/remind101/stacker/blob/master/stacker/blueprints/bastion.py#L56)

**Comment by phobologic** [comment]
Oh, and to be a little more helpful - here's how you'd actually want to do your first example:

```
for r in rules:
    t.add_resource(
        SecurityGroupEgress(
            **UNIQUE NAME HERE**,
            IpProtocol=r[1],
            FromPort=r[2],
            ToPort=r[3],
            CidrIp=r[4],
            GroupId=Ref(sg_name)
        )
    )
```

**Note:** I've left creating your own unique resource name up to you, since it could get quite complicated here. Remember that resource names don't allow for special characters.

**Comment by dinilatgit** [comment]
Thanks All.

Reason i raised the issue was add_resource did not recognize SecurityGroupIngress or SecurityGroupIngress as a property and kept failing.

For now, I have accomplished it as:
sg_rules_i = []
for r in rules:
    sg_rules_i.append(SecurityGroupRule(
                   suitable_loop_name,
                   IpProtocol=r[1],
                   FromPort=r[2],
                   ToPort=r[3],
                   CidrIp=r[4]
               ))

and further
t.add_resource(SecurityGroup(
       sg_name,
       GroupDescription=sg_desc,
       VpcId=Ref(vpcid),
       SecurityGroupIngress=sg_rules_i

Stack creation was successful.

Regards.

**Comment by dinilatgit** [comment]
As expected and since this is no bug, I would be closing the issue.

Regards.

**Comment by aehlke** [comment]
@phobologic doesn't `GroupId` have to be `GroupName` there?

**Comment by phobologic** [comment]
Nope: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html

**Comment by aehlke** [comment]
Sorry, I was getting confused due to dealing with both non-VPC and VPC security groups, which have different cloudformation requirements around using group names vs. IDs, surprisingly.
