### ISSUE TITLE
aws_access_key_id and aws_secret_access_key

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#302]
How can I pass these variables into troposphere so it doesn't look at ~/.aws/credentials?

I'm trying to build out a mechanism in which I can switch between amazon accounts and rename directories is error prone and not really efficient.

**Comment by phobologic** [comment]
Which part of troposphere are you using that is using your credentials?  The library is just an implementation of the Cloudformation Template language.

In general though, if you're using boto to talk to the cloudformation API, you should check out the documentation for how that uses your credentials.
