### ISSUE TITLE
S3 Bucket - valid_names regex

### ISSUE THREAD

**Issue by jrasell** [cloudtools/troposphere#311]
The regex used for validating S3 bucket names omits a number of valid S3 bucket names:

```
valid_names = re.compile(r'^[a-zA-Z0-9]+$')
```
```
    raise ValueError('Name "%s" not alphanumeric' % title)
ValueError: Name "jrasell-internal" not alphanumeric
```

It would be handy if it could at least support dashes.

**Comment by ikben** [comment]
There is a difference between bucketName and the name of the resource.

This works:

    bucket = s3.Bucket('NoHyphens', BucketName='with-hyphens')

This doesn't:

    bucket = s3.Bucket('Invalid-Hyphen', BucketName='valid-hyphen').

**Comment by jrasell** [comment]
My bad.
Thanks very much for the help @ikben.

**Comment by bjinwright** [comment]
This should be added to the S3 example
