### ISSUE TITLE
AWS Lambda Support Status?

### ISSUE THREAD

**Issue by Miserlou** [cloudtools/troposphere#313]
Does Troposphere support AWS Lambda? I see some references to it in the commit logs, but nothing in the documentation. What's the status of Lambda support in Troposphere?

**Comment by markpeek** [comment]
Yes, troposphere has [lambda support](https://github.com/cloudtools/troposphere/blob/master/troposphere/awslambda.py).

**Comment by Miserlou** [comment]
Excellent. In that case, please update the list of supported resources - https://github.com/cloudtools/troposphere#currently-supported-aws-resource-types
