### ISSUE TITLE
RDS ValueError

### ISSUE THREAD

**Issue by Poil** [cloudtools/troposphere#316]
Hi,

ValueError: DBInstance Engine must be one of: MySQL, oracle-se1, oracle-se, oracle-ee, sqlserver-ee, sqlserver-se, sqlserver-ex, sqlserver-web, postgres

Why MySQL ? previously I had mysql and it was working fine in cfn (and all other type are defined in lowercase)

Best regards

**Comment by phobologic** [comment]
This was added by me - I was going by what is in the documentation here for the Engine attribute:

http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

```
Engine
The name of the database engine to be used for this instance.

Valid Values: MySQL | oracle-se1 | oracle-se | oracle-ee | sqlserver-ee | sqlserver-se | sqlserver-ex | sqlserver-web | postgres

Not every database engine is available for every AWS region.

Type: String

Required: Yes
```

I'm curious what the actual limits are.

**Comment by Poil** [comment]
Hey,

I will open a case, brb in 1 or 2 days :)

**Comment by phobologic** [comment]
Thanks Poil!  Open a PR with the actual set they give you - or just share it here, and I'll make one ASAP.

**Comment by markpeek** [comment]
@Poil any word back on the case?

**Comment by micahhausler** [comment]
I'm hitting the same wall, Postgres instances only have the string `'postgresql-license'` and I'm getting the same ValueError

**Comment by markpeek** [comment]
Closing due to commit of #323. Thanks for reporting.
