### ISSUE TITLE
Rename awslambda to lambda

### ISSUE THREAD

**Issue by Miserlou** [cloudtools/troposphere#317]
Inconsistent naming.. they're all AWS products, why is this one called awslambda when all of the others aren't?

(Sorry for all the issues, but we have a very large product we're porting to tropo and are encountering some small errors like this. Do you accept pull requests?)

**Comment by bobveznat** [comment]
lambda is a keyword in python. If you name a module lambda you can't import it:

```
>>> import lambda
  File "<stdin>", line 1
    import lambda
                ^
SyntaxError: invalid syntax
```

Notice that boto did the same thing. We are consistent with boto here.

**Comment by Miserlou** [comment]
Ah, of course! Thanks.
