### ISSUE TITLE
SSL Certificate ID

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#318]
In this example, https://github.com/cloudtools/troposphere/blob/master/examples/Autoscaling.py#L28

Where does the SSLCertificate come from? Is it a PEM file that it gets passed on here via command line as a parameter?

EDIT:
I'm trying to figure out how to create a SSL connection for a enterprise Application on Amazon. It'll be a self signed certificate.

**Comment by phobologic** [comment]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-listener.html#cfn-ec2-elb-listener-sslcertificateid

**Comment by bobveznat** [comment]
It is "The ARN of the SSL certificate to use. "

The idea being that you somewhat securely upload the cert and associated
private key to AWS separately. The ARN of the uploaded cert then gets put
into the template as a parameter. The ARN for an ssl cert will be of the
form "arn:aws:iam::123456789012:server-certificate/my-new-certificate"

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-listener.html#cfn-ec2-elb-listener-sslcertificateid

**Comment by BardiaAfshin** [comment]
wow. thanks for this reply, it help clears things further. So I need to 

1. generate whatever public/private certificates
2. upload them to some amazon service? s3?
3. get something called a ARN of these certificates and simply reference them in my cloudformation script?

**Comment by Poil** [comment]
Hi,

You need to upload it via the CLI http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs_manage.html
