### ISSUE TITLE
RDS validation check for "AvailabilityZone and MultiAZ" breaks conditional parameters

### ISSUE THREAD

**Issue by sterwill** [cloudtools/troposphere#320]
This validation check in rds.py:195 causes my valid templates to fail:

        if 'AvailabilityZone' in self.properties and \
                self.properties.get('MultiAZ', None):
            raise ValueError("AvailabiltyZone cannot be set on DBInstance if "
                             "MultiAZ is set to true.")

My code, which worked before this validation check was added, sets MultiAz to a Ref of a required boolean parameter and AvailabilityZone to a conditional that may evaluate to AWS::NoValue (meaning CloudFormation disregards the parameter):

    database = template.add_resource(
        troposphere.rds.DBInstance(
            ...
            AvailabilityZone=If(
                'DbAvailabilityZoneSpecified',
                Ref(db_availability_zone),
                Ref(AWS_NO_VALUE)),
            ...
            MultiAZ=Ref(db_multi_az),
        )
    )

This is the only pattern I know of for handling optional parameters in nested stacks when the resource requires that a parameter be unset to trigger the default.  

I think the fix is to simply remove the exclusivity check in validate(), or possibly fail only if the value is not one of the conditional functions.

**Comment by markpeek** [comment]
@sterwill looks like we both provided fixes for this issue. :-) I'll let @phobologic take a look and review.

**Comment by sterwill** [comment]
Your is the better fix (and I made a mess of my branch history in my fork) so feel free to ignore mine. 

Thanks for the lightning fast fix.

**Comment by sterwill** [comment]
types.NoneType was removed from Python 3, so the check may have to add some additional "is None" checks.

**Comment by markpeek** [comment]
Merged. Thanks for the bug report.
