### ISSUE TITLE
Example request, scaling policy based on http request

### ISSUE THREAD

**Issue by BardiaAfshin** [cloudtools/troposphere#325]
This is not a bug, as more of a request to build a scaling policy with troposhphere that is based on the number of requests per second over http for a period of time.

**Comment by phobologic** [comment]
You should be able to build one using the docs here:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html

which maps to the object here:

https://github.com/cloudtools/troposphere/blob/master/troposphere/autoscaling.py#L197

If you need help building that, I'd suggest pinging the Google Group and possibly look for Cloudformation examples online - here's a good one:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/example-templates-autoscaling.html

**Comment by phobologic** [comment]
BTW, if you'd like to submit a pull request with an example that you've created, that'd be awesome!
