### ISSUE TITLE
Keyname to basestring

### ISSUE THREAD

**Issue by sherabi** [cloudtools/troposphere#326]
Hi, I am working on a rather complex cloudformation template and here is a snippet of a resulting block that I am trying to output

```
"KeyName": {
                   "Fn::If": [ "IsAppKey",
                            {"Fn::FindInMap": ["KeyNames", {"Ref": "Environment"}, "App"]},
                            {"Ref" : "AWS::NoValue"}
                   ]
                },
```

Here is what I have so far but its not working

I get an error for KeyName (rightly so) which I am not sure how to fix, the relevant error is:
```
TypeError: KeyName is <type 'dict'>, expected <type 'basestring'>
```

However I am not sure how to convert the following line:
```
KeyName= {"Fn::If": ["IsAppKey", FindInMap("KeyNames", Ref(Environment), "App"), Ref("AWS::NoValue")]},
```

To one that will appropriately output the json block stated at the top of this issue. Please advise.
Thanks in advance and your help will be greatly appreciated.

**Comment by phobologic** [comment]
KeyName is an attribute of a Resource?  It looks like you're trying to mix raw Cloudformation (your Fn::If statement) in your python/troposphere templates?

This should work - just use the built in If() method of troposphere: 

```
KeyName=If("IsAppKey",
           FindInMap("KeyNames", Ref(Environment), "App"),
           Ref("AWS::NoValue")))
```

**Comment by markpeek** [comment]
What @phobologic said and import those with something like:
```
from troposphere import If, FindInMap, Ref
```

**Comment by sherabi** [comment]
You guys rock, thanks for all you help.
