### ISSUE TITLE
Data Pipeline RefValue should accept string

### ISSUE THREAD

**Issue by khueue** [cloudtools/troposphere#328]
Hi!

I'm getting complaints from CloudFormation that ```RefValue``` in ```datapipeline.ObjectField```. should be a string, but troposphere doesn't seem to allow this. If I try this:

```
datapipeline.ObjectField(
	Key = 'input',
	RefValue = 'DDBSourceTable',
)
```

I get this:

```
TypeError: <class 'troposphere.datapipeline.ObjectField'>: None.RefValue is <type 'str'>, expected [<type 'basestring'>, <class 'troposphere.Ref'>]
```

I can't use a ```Ref()``` since I'm referring to other inline objects in the pipeline, not to an actual resource in the template.

At some point, I got this error when launching the stack in CF:

```
Value of property RefValue must be of type String
```

Is this a bug or am I doing something crazy? Thanks!

**Comment by markpeek** [comment]
Thanks for reporting this issue. I just pushed a change that should fix it.

**Comment by khueue** [comment]
Nice! Works perfectly!
