### ISSUE TITLE
Aurora DBInstance,

### ISSUE THREAD

**Issue by hauboldj** [cloudtools/troposphere#341]
https://github.com/cloudtools/troposphere/blob/master/troposphere/rds.py#L337

The property should be AvailabilityZones not AvailabilityZone.

**Comment by markpeek** [comment]
That's odd. I swear AWS changes the docs out from under us. To your point, I do see ```AvailabilityZones``` in the docs. However, it shows as needing a ```String``` but seems to need ```List of Strings```. Can you confirm which is correct?

**Comment by hauboldj** [comment]
It will need a list of strings.

**Comment by markpeek** [comment]
Thanks for the issue and quick response. Fixed on master.
