### ISSUE TITLE
ValueError('Name "%s" not alphanumeric' % title) on resource which allows non-Alphanumeric characters in name

### ISSUE THREAD

**Issue by ocsi01** [cloudtools/troposphere#344]
I just faced the issue, that I'm not allowed to give my custom name to a Cloudwatch Log-Group:
"tomcat/error.log".
AWS allows the name above for a Log-Group, however Troposphere not.

**Comment by markpeek** [comment]
I suspect this is one of the FAQ we get about CloudFormation usage. The CloudFormation resource name is very strict and not the same as names used within the resource. An example illustrating this is #311. But feel free to post a snippet of your log group creation and we might be able to give you more concrete advice.

**Comment by ikben** [comment]
This is more a limitation of CloudFormation, not of Troposphere.

There is no 'LogGroupName' property in the AWS::Logs::LogGroup resource (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html), and like @markpeek said, resource names must be alphanumeric. In this case it's not possible to use a non-alphanumeric name.

If you really need the alphanumeric name, you can use a Custom Resource, or generatie the log group with the API the first time you create a log stream.

**Comment by markpeek** [comment]
Closing based on previous comments.
