### ISSUE TITLE
iam.Policy missing "Users", "Roles" and "Groups"?

### ISSUE THREAD

**Issue by amosshapira** [cloudtools/troposphere#346]
I'm trying to convert a static CloudFormation template to be generated by troposphere. Here is a Policy resource:
```
"contentServiceUserAccessPolicy": {
  "Properties": {
    "PolicyDocument": {
      "Statement": [],
      "Version": "2012-10-17"
    }, 
    "PolicyName": "contentServiceBucketAccess", 
    "Users": [
      {
        "Ref": "contentServiceUser"
      }
    ]
  }, 
  "Type": "AWS::IAM::Policy"
}
```
And the part of the code I'm trying to convert it to is:
```
template.add_resource(iam.Policy(
    "contentServiceUserAccessPolicy",
    PolicyName = "contenServiceBucketAccess",
    Users = [ Ref("contentServiceUser")],
    PolicyDocument = awacs.aws.Policy()
))
```
But I get the following error:
```
AttributeError: Policy object does not support attribute Users
```
According to http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html, `Users` is an accepted attribute (as well as Roles and Groups), but it doesn't appear in the troposphere source code in https://github.com/cloudtools/troposphere/blob/master/troposphere/iam.py#L42

**Comment by markpeek** [comment]
Try using [PolicyType](https://github.com/cloudtools/troposphere/blob/master/troposphere/iam.py#L30).

**Comment by amosshapira** [comment]
Ouch. This looks promising. Thanks.

**Comment by markpeek** [comment]
Also, if you're looking to implement policies, check out [awacs](https://github.com/cloudtools/awacs) which interfaces with troposphere.

**Comment by amosshapira** [comment]
Thanks. I'm aware of Awacs. I use it where I can.
