### ISSUE TITLE
No class for creating Elasticsearch instances

### ISSUE THREAD

**Issue by RichardBradley** [cloudtools/troposphere#347]
I'd like to create a hosted AWS Elasticsearch instance, as per https://aws.amazon.com/elasticsearch-service/

There is no class in toposphere for this.

I can't even find how to do it in Cloudformation: there's no sample at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html or http://aws.amazon.com/cloudformation/aws-cloudformation-templates/ or in the cloudformation/designer UI in my AWS homepage.

How on earth can I guess the right json to use to create one of these?

The blog post from amazon does hint "you also can do this using the AWS Command Line Interface (CLI)": https://aws.amazon.com/blogs/aws/new-amazon-elasticsearch-service/  but doesn't say how!

**Comment by markpeek** [comment]
At this time I do not see that AWS has implemented Elasticsearch in CloudFormation yet. There isn't anything troposphere can do until that occurs. You should raise either a support issue or AWS forum issue (in the [CloudFormation](https://forums.aws.amazon.com/forum.jspa?forumID=92) and/or [Elasticsearch](https://forums.aws.amazon.com/forum.jspa?forumID=200) forums.

**Comment by RichardBradley** [comment]
Thanks
