### ISSUE TITLE
Can't set the logging driver inside the ECS object

### ISSUE THREAD

**Issue by techgnosis** [cloudtools/troposphere#348]
There is no functionality for setting the logging driver in the ECS object. Is there a preferred way to set this given what exists today?

**Comment by phobologic** [comment]
I take it you're asking about docker logging drive options?  Currently Cloudformation doesn't yet support the logging/storage driver options as far as I can tell - hopefully this will change soon.  Usually as soon as it's supported in CF, it gets brought into troposphere shortly after.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

**Comment by techgnosis** [comment]
Yeah you're right it doesn't :( Thanks for the swift reply.

**Comment by phobologic** [comment]
NP!  Hopefully it'll show up soon!
