### ISSUE TITLE
Beanstalk OptionSettings should have ResourceName

### ISSUE THREAD

**Issue by vkorn** [cloudtools/troposphere#349]
Options in EB have support of resource_name field to aggregate group of options, so OptionSettings props should have 
```
'ResourceName': (basestring, False)
```
For example here's part of generating autoscale triggers: 
```
                  {
                        "Namespace": "aws:autoscaling:trigger",
                        "OptionName": "BreachDuration",
                        "ResourceName": "TriggerMin",
                        "Value": "5"
                    },
{
                        "Namespace": "aws:autoscaling:trigger",
                        "OptionName": "BreachDuration",
                        "ResourceName": "TriggerMax",
                        "Value": "5"
                    },
```

**Comment by markpeek** [comment]
CloudFormation docs for [OptionSettings](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-option-settings.html) do not indicate ResourceName as a valid property.

**Comment by vkorn** [comment]
Indeed there's no mentioning of this property in general docs, but it's the only way to group same types of properties. [Here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.as.html#using-features.managing.as.timebased
) is an example of configuring EB through .ebextensions files with this property. I've tweaked code a bit to include property in output and successfully created triggers with different names and desired params.
