### ISSUE TITLE
S3 Tags not accepting list in Troposphere

### ISSUE THREAD

**Issue by amitgup** [cloudtools/troposphere#350]
I have checked the troposphere code, it seems for all resources troposphere is using list format for tags. This method in fact supports both Tags Object and list.

troposphere/rds.py

'Tags': (list, False),

But for some reason S3 does not.

troposphere/s3.py
'Tags': (Tags, False),

To support list and object for S3 tags, just need to change Tags to list. 
troposphere/s3.py
'Tags': (list, False),

**Comment by amitgup** [comment]
Please consider to fix this next release

**Comment by jlbribeiro** [comment]
Just bumped into this, :+1:

**Comment by markpeek** [comment]
The bug should be against the RDS usage instead of the S3 usage. The intent is to allow the following usage to make it easier to format Tags:
```
>>> from troposphere import Tags
>>> Tags(foo='bar', baz='boo').JSONrepr()
[{'Value': 'boo', 'Key': 'baz'}, {'Value': 'bar', 'Key': 'foo'}]
```
or
```
>>> from troposphere import Tags
>>> d = {'foo': 'bar', 'baz': 'boo'}
>>> Tags(**d).JSONrepr()
[{'Value': 'boo', 'Key': 'baz'}, {'Value': 'bar', 'Key': 'foo'}]
```
