### ISSUE TITLE
How to add optional attribute?

### ISSUE THREAD

**Issue by amosshapira** [cloudtools/troposphere#352]
(I asked this on StackOverflow but I think there is a better chance of response here)

I would like to pass the Elastic Load Balancer `ConnectionSettings` attribute only if it's set in my configuration, otherwise I don't want to specify it.

If I set it to default python `None` then I get an error about the value not being of the expected type of `troposphere.elasticloadbalancing.ConnectionSettings`.

I'd rather try to avoid setting an explicit default in the call because it might override other settings.

Ideally, I would like to be able to add attributes to an existing object, e.g.:

    lb = template.add_resource(elb.LoadBalancer(
      ...
    ))

    if condition:
      lb.add_attribute(ConnectionSettings = elb.ConnectionSettings(
        ...
      ))

I achieved it using the hidden `__setattr__` method, which works but I'm not happy with just because it's a hidden method:

    if condition:
      lb.__setattr__('ConnectionSettings', elb.ConnectionSettings(
        ....
      ))

Thanks.

**Comment by markpeek** [comment]
I responded with this back to StackOverflow as well.

The main README eludes to just using the attribute names like this:
```
from troposphere import Template
import troposphere.elasticloadbalancing as elb

template = Template()
webelb = elb.LoadBalancer(
    'ElasticLoadBalancer',
    Listeners=[
        elb.Listener(
            LoadBalancerPort="80",
            InstancePort="80",
            Protocol="HTTP",
        ),
    ],
)

if True:
    webelb.ConnectionSettings = elb.ConnectionSettings(IdleTimeout=30)
elasticLB = template.add_resource(webelb)
print(template.to_json())
```
