### ISSUE TITLE
Route53 standalone RecordSet gets formatted as a RecordSetGroup entry

### ISSUE THREAD

**Issue by rakslice** [cloudtools/troposphere#356]
RecordSet resources at the top level in the template are being formatted incorrectly by troposphere. 

As noted in the link on the previous issue #51 "A RecordSet can be either a standalone resource or an embedded property. As an embedded property within a RecordSetGroup you don't specify a Type or have a the entries under Properties." As a standalone resource, you do specify a Type and have the entries under Properties.

See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html#scenario-route53-recordset-by-host for examples.

**Comment by phobologic** [comment]
https://github.com/cloudtools/troposphere/blob/master/troposphere/route53.py#L51

There are two RecordSet objects - one called `RecordSetType` which is the standalone resource, and one called `RecordSet` which is the property.
