### ISSUE TITLE
CloudFront TTL issue - undocumented AWS change

### ISSUE THREAD

**Issue by slikk66** [cloudtools/troposphere#359]
Suddenly working with CloudFront via CloudFormation if you pass in a MinTTL value for your cache behavior, you will get an error saying:

**MinTTL must be less equal to DefaultTTL must be less equal to MaxTTL**

however, according to the docs (as of 12/21) there are no DefaultTTL or MaxTTL values: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-defaultcachebehavior.html#cfn-cloudfront-defaultcachebehavior-minttl

Troposphere reflects this fact and won't let you add MaxTTL or DefaultTTL.  However, now all CloudFront adjustments using TTLs will fail.  If you manually add in the MaxTTL and DefaultTTL values to the code, now it works!  Just verified and tested working with adjusted code.  PR to fix issue is #360

**Comment by markpeek** [comment]
Fixed with merge of #360
