### ISSUE TITLE
RDS iops can't be set to 0

### ISSUE THREAD

**Issue by hauboldj** [cloudtools/troposphere#361]
Allow Iops to be set to 0 for an RDS instance.
While the CF docs say the minimum is 1000, there is a use for setting iops to 0. See http://docs.aws.amazon.com/AmazonRDS/latest/CommandLineReference/CLIReference-cmd-RestoreDBInstanceFromDBSnapshot.html for the usage. Basically setting to 0 allows you to restore a provisioned iops snapshot to a non provisioned iops instance.

**Comment by markpeek** [comment]
Thanks for the issue. Let me know if this fix works for you.

**Comment by hauboldj** [comment]
This fix worked great.
