### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by craigbruce** [cloudtools/troposphere#365]
The last release (1.3.0) is missing many of the cool new features added since including, but not limited to, support for RDS Aurora & CodePipeline. Fixes for Spot Fleet & CodeDeploy. Plus new properties for many existing services.

Can we start 2016 with a 1.4.0 release?

**Comment by markpeek** [comment]
@craigbruce agreed on needing a new release soon. Still playing catchup to get all of the CF Dec 3 and Dec 28 changes added (some got added last week).

**Comment by markpeek** [comment]
Just pushed out release 1.4.0. Thank you for all your changes. Happy New Year.

**Comment by craigbruce** [comment]
Thanks @markpeek!
