### ISSUE TITLE
Python 2.6.9 unsupported

### ISSUE THREAD

**Issue by cep21** [cloudtools/troposphere#369]
Is it expected that python 2.6.9 is unsupported?

```
>>> import troposphere
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/site-packages/troposphere/__init__.py", line 168
    k: v for k, v in self.resource.items()
           ^
SyntaxError: invalid syntax
```

https://github.com/cloudtools/troposphere/commit/77320c91cf86589df0f1e861d1a273d251f4f127

**Comment by markpeek** [comment]
@cep21 I only validate troposphere to work against 2.7, 3.3, and 3.4 via [travis](https://github.com/cloudtools/troposphere/blob/master/.travis.yml). That particular usage of dictionary comprehension could be recoded via a loop if there is a need to support 2.6. But I do worry about needing to support future compatibility to 2.6. Let me know what your use case is for needing it or whether you can move to 2.7+.

**Comment by cep21** [comment]
Only the normal operations issues around upgrading python being a scary thing to do.  It would be nice to add 2.6 to .travis, especially since it was previously working.

**Comment by wt** [comment]
If you're validating for 2.7, 2.6 should be pretty straightforward to support in most cases. Without trying, it was only 1.4.0 that broke python 2.6 support.

Would it be possible to add py2.6 to the travis just so you know when it breaks?

**Comment by markpeek** [comment]
I took a quick look at 2.6 compatibility but there are some test regressions I need to resolve first. If I can get it working I'll add 2.6.
