### ISSUE TITLE
Output is more than a `basestring`

### ISSUE THREAD

**Issue by sesas** [cloudtools/troposphere#379]
Offending line: https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L465

AWS Docs: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html#Value

> Value (required)
> The value of the property that is returned by the aws cloudformation describe-stacks command. The value of an output can be **literals, parameter references, pseudo parameters, a mapping value, and intrinsic functions.**

(emphasis mine)

**Comment by markpeek** [comment]
Not sure there is a bug here. Helper functions can be used as well as basestrings ([example](https://github.com/cloudtools/troposphere/blob/master/examples/SQSDLQ.py)). Please let me know (and give an example of) what you feel isn't working correctly.

**Comment by phobologic** [comment]
@markpeek beat me too it, but to elaborate a bit, AWSHelperFn's are allowed here: https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L98

FindInMap is an AWSHelperFn, so should work.  Do you have an exception you can share?

**Comment by sesas** [comment]
Oh sorry guys, I must have made a mistake.
