### ISSUE TITLE
SimpleAD resource throws value errors

### ISSUE THREAD

**Issue by l0neranger** [cloudtools/troposphere#384]
Tried multiple iterations for setting VpcSettings in SimpleAD and it simply does not work.  The traceback is attached which claims a ValueError

```
template.add_resource(SimpleAD(
    "simplead",
    CreateAlias="simpleadalias",
    Description="Simple AD Directory",
    Name="corp.test.com",
    Password="test123",
    Size="small",
    VpcSettings=VpcSettings(SubnetIds=["subnet-xxxxxxxx, subnet-yyyyyyyy"], VpcId="vpc-zzzzzzzz")
))
```
Traceback
```
Traceback (most recent call last):
  File "./aws-simplead.py", line xx, in <module>
    VpcSettings=VpcSettings(SubnetIds=["subnet-xxxxxxxx, subnet-yyyyyyyy"], VpcId="vpc-zzzzzzzz")
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/troposphere/__init__.py", line 66, in __init__
    self.__setattr__(k, v)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/troposphere/__init__.py", line 103, in __setattr__
    value = expected_type(value)
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/troposphere/validators.py", line 12, in boolean
    raise ValueError
ValueError
```
Does this work for anyone? Any help appreciated.

**Comment by phobologic** [comment]
This is because CreateAlias is supposed to be a boolean, not a string:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-directoryservice-simplead.html#cfn-directoryservice-simplead-createalias

**Comment by phobologic** [comment]
BTW, I'm looking at making that particular failure case more user friendly right now - thanks for pointing it out. (We've made many others easier to figure out from the exception they raise, this one not quite).

**Comment by phobologic** [comment]
@l0neranger can you verify what version of troposphere you have installed?

Inside a python shell type:

```
>>> import troposphere
>>> troposphere.__version__
'1.3.0'
```

Thanks.

**Comment by l0neranger** [comment]
Thanks for the help - that solved my issue.

I'm currently running troposphere 1.4.0

**Comment by phobologic** [comment]
Cool, thanks.  I've got a PR (GH-385) opened that will hopefully make this more apparent, though I wish I could make the error statement even more apparent.
