### ISSUE TITLE
Output section errors

### ISSUE THREAD

**Issue by taps04** [cloudtools/troposphere#406]
In my python file the outputs ref the proper subnet, but when I convert to json it changes the ref values in the outputs to ref the route tables. It appears this is only happening for the private subnets and is possibly random. One of my team mates caught it on one subnet at first. When I re-ran the py file it now refs the route tables for all of the private subnets as seen in the attached files.

![not-good](https://cloud.githubusercontent.com/assets/17559388/13415664/9a1bdd9e-df2a-11e5-9493-217b82081f7d.png)
![good](https://cloud.githubusercontent.com/assets/17559388/13415666/9cb21492-df2a-11e5-903c-73369b119ae2.png)

**Comment by phobologic** [comment]
Can we see the definitions of the `PrivateSubnet1AFW` object?  My guess is that when you define your subnets you are assigning them to `PrivateSunet1AFW`, but when you create your Routes you are assigning them to the same variable. Note: You aren't using a string in your Ref, so it's referring to a python object.  If you override that python object with another value, it's going to cause issues.  Basically, can you give us the code snippets for where you build `PrivateSubnet1AFW` and `Private1AFWRouteTable`?  Preferably in a gist, or pasted as actual code into this issue - screen shots are hard to work with :)

Thanks!

**Comment by taps04** [comment]
You're 100% correct. I caught it when I was creating the gist. I'm using the same variable for both the subnet and the route table by mistake. Thanks for the quick response!

https://gist.github.com/taps04/8eb985a23af094954df9

https://gist.github.com/taps04/fc841cd40e47eca6aeb6

**Comment by phobologic** [comment]
No problem, glad to help :)
