### ISSUE TITLE
Add support to create Elasticsearch Domains

### ISSUE THREAD

**Issue by edubxb** [cloudtools/troposphere#411]
Cloudformation recently has implemented the creation of Elasticsearch domains, would be nice to have this feature in troposphere too.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html

**Comment by phobologic** [comment]
@edubxb - are you planning on submitting a PR for this?  I can take a stab at it if not, just don't want to double up work :)

**Comment by edubxb** [comment]
I will try... I will take a look at the code and make a PR.

**Comment by phobologic** [comment]
Cool - if you decide you don't have the  time, let us know here and I'll get it knocked out soon.  It looks like you'll need to create an AWSObject for the Domain itself, and then AWSProperties for: 

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-ebsoptions.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-snapshotoptions.html

Shouldn't be too hard - if you need a hand, go ahead and ping here.  Good luck!

**Comment by edubxb** [comment]
Thanks for your help!

**Comment by phobologic** [comment]
Just an update  - #414 was submitted, so hopefully this will go in soon.

**Comment by Bazze** [comment]
Would be great to get one of the two PRs (#414, #415) merged soon! :)
