### ISSUE TITLE
Add support for EMR Resources

### ISSUE THREAD

**Issue by alonsodomin** [cloudtools/troposphere#412]
CloudFormation just recently added support for EMR resources:
https://aws.amazon.com/about-aws/whats-new/2016/02/aws-cloudformation-adds-support-for-amazon-vpc-nat-gateway-amazon-ec2-container-registry-and-more/

It has happened this latest addition to CloudFormation was added in the moment that me and my colleagues were actually experimenting with it using CloudFormation CustomResources and Lambda Functions.

Adding pure "native" support sounds simpler though and we already have prototyped something extending Troposphere AWSObject & AWSProperty base objects. We are happy to PR it if no one else is working on it

**Comment by phobologic** [comment]
We have no current pull requests, and I haven't heard of anyone working on it yet, so if you want to submit a PR that'd be great!  Thanks.

**Comment by alonsodomin** [comment]
Cool, will try to get some unit tests for the new objects and properties and then make the PR, feel free to assign this issue to me

**Comment by phobologic** [comment]
Great, thanks @alonsodomin

**Comment by phobologic** [comment]
btw, instead of writing unit tests, we like to add an example to `examples`.  The test suite will automatically run all examples and compare the output to the templates in `tests/examples_output`.  This would probably be a good one:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-cluster.html#d0e52177

**Comment by alonsodomin** [comment]
Just realised right now (after receiving an AWS announcement email) that now CloudFormation supports EBS volumes... should have included those in the initial PR. Will try to get some come working in the next hours and submit a new PR if here are happy with it:

https://aws.amazon.com/about-aws/whats-new/2016/03/aws-cloudformation-updates-amazon-s3-aws-lambda-and-amazon-emr-resources-support/?sc_channel=em&sc_campaign=releasenotes&sc_publisher=aws&sc_medium=em_13165&sc_content=launch&sc_country=mult&sc_geo=mult&sc_category=20160404_releasenotes&mkt_tok=3RkMMJWWfF9wsRonuK3Pd%2B%2FhmjTEU5z16OspWaKxgIkz2EFye%2BLIHETpodcMTcNmM7rYDBceEJhqyQJxPr3ELdINzs9wRhbkDg%3D%3D

**Comment by alonsodomin** [comment]
Closing this off after the merge of #453
