### ISSUE TITLE
Please add support for ECR Repository

### ISSUE THREAD

**Issue by vpal** [cloudtools/troposphere#417]
You can find the ECR related documentations here: 

- https://aws.amazon.com/ecr/
- http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

Thanks

**Comment by matalo33** [comment]
#395 has been merged

**Comment by vpal** [comment]
Sorry I just searched the issues and it did not give any result for ecr and it was also not listed in the readme.
I just updated troposphere with pip and see the ECR resource, many thanks.
