### ISSUE TITLE
Alphanumeric characters allowed by CloudFormation in titles, but not troposphere

### ISSUE THREAD

**Issue by daltonconley** [cloudtools/troposphere#430]
When trying to make a subnet with a name like `myVpc.internal.us-west-2a`, I get the following error:

```
Traceback (most recent call last):
  File "./myCfScript", line 123, in <module>
    bu_cf = bu.get_cloudformation_template(args.region)
  File "/Users/me/Development/project/cf_stuff.py", line 74, in get_cloudformation_template
    RouteTableId=Ref(privateRouteTable),
  File "/Library/Python/2.7/site-packages/troposphere/__init__.py", line 44, in __init__
    self.validate_title()
  File "/Library/Python/2.7/site-packages/troposphere/__init__.py", line 159, in validate_title
    raise ValueError('Name "%s" not alphanumeric' % self.title)
ValueError: Name "myVpc.internal.us-west-2a" not alphanumeric
```
However, I'm allowed to create a subnet with this name manually via the AWS Console, which means it's allowed, right? The reason I want this type of name is [for use with spinnaker](http://spinnaker.io/documentation/troubleshooting.html#i-dont-see-my-vpcs-in-any-of-the-dropdowns).

**Comment by phobologic** [comment]
Cloudformation has limits on the characters you can use that the services themselves don't have:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html (see Logical Id): 

```
The logical ID must be alphanumeric (A-Za-z0-9) and unique within the template. You use the logical name to reference the resource in other parts of the template. For example, if you want to map an Amazon Elastic Block Store to an Amazon EC2 instance, you reference the logical IDs to associate the block stores with the instance.
```

Note that that is not even what the physical ID of the object will be, as CF will create a physical ID based upon the logical Id.  Some resources (s3:Bucket for example) give a property that can be used to control the physical name of the object (BucketName in the example), but not every resource does.
