### ISSUE TITLE
Automatically insert Ref() calls where appropriate

### ISSUE THREAD

**Issue by mjuenema** [cloudtools/troposphere#434]
**Summary**

I am toying with the idea of automatically inserting  `Ref()` calls whenever appropriate. The current progress is available at https://github.com/mjuenema/troposphere/tree/develop. It passes all tests (https://travis-ci.org/mjuenema/troposphere/builds/116539701) but I had to disable the `examples/DynamoDb...` examples. 

The functionality is implemented by adding a `referrable = True` attribute to all `AWSObject` derived classes that can be referenced in CloudFormation JSON. An additional function `_autoinsert_ref()` automatically wraps objects that can be referenced in a `Ref()`.  Pseudo-parameters like `AWS::Region` are also covered. 

Any thoughts?

**Example 1: Referencing a key**

```
ec2_instance = template.add_resource(ec2.Instance(
    "Ec2Instance",
    ImageId=FindInMap("RegionMap", Ref("AWS::Region"), "AMI"),
    InstanceType="t1.micro",
    KeyName=keyname_param,     # instead of Ref(keyname_param)
    SecurityGroups=["default"],
    UserData=Base64("80")
))
```

**Example 2: `Ref()` in `FindInMap()`**

```
MyEC2Instance = t.add_resource(Instance(
    "MyEC2Instance",
    SecurityGroupIds=GetAtt("AllSecurityGroups", "Value"),
    InstanceType=InstanceType,
    ImageId=FindInMap("AWSRegionArch2AMI", Ref("AWS::Region"),
                   FindInMap("AWSInstanceType2Arch", InstanceType,   # not Ref(InstanceType)
                                "Arch")),
))
```

**Example 3: `Ref()` in `Join()`**

```
myDNSRecord = t.add_resource(RecordSetType(
    "myDNSRecord",
    HostedZoneName=Join("", [hostedzone, "."]),
    Comment="DNS name for my instance.",
    Name=Join("", [instance, ".", Ref("AWS::Region"), ".",
              hostedzone, "."]),       # not Ref(hostedzone)
    Type="A",
    TTL="900",
    ResourceRecords=[GetAtt("Ec2Instance", "PublicIp")],
))
```

**Example 4: Pseudo-parameters**

```
instance = t.add_resource(Instance(
    "Ec2Instance",
    ImageId=FindInMap("RegionMap", "AWS::Region", "AMI"),    # not Ref("AWS::Region")
    InstanceType="m1.small",
))
```

**Comment by ikben** [comment]
I think the last one is dangerous.

Having the constant `AWS_REGION` transformed to `Ref("AWS::Region)` seems a better way. The way you wrote your example there is no way to do that join with the literal string "AWS::Region".

**Comment by mjuenema** [comment]
Oh, I nearly forgot about this issue. I haven't been working with Cloudformation since. In fact, I have little experience with Cloudformation. It just irked me from a Python point of view. Seeing that issue #25 had been idle for almost 3 years it doesn't seem to be a high priority. After all ``Ref(...)`` works fine.

**Comment by mjuenema** [comment]
Oh, I nearly forgot about this issue. I haven't been working with Cloudformation since. In fact, I have little experience with Cloudformation. It just irked me from a Python point of view. Seeing that issue #25 had been idle for almost 3 years it doesn't seem to be a high priority. After all ``Ref(...)`` works fine.
