### ISSUE TITLE
Please add the ability to import an existing cloudformation template

### ISSUE THREAD

**Issue by rjmpsmith** [cloudtools/troposphere#441]
Hello there,

My company tries to keep everything related to a specific set of resources in a single cloudformation stack. This means that if we wish to deploy another, related, EC2 instance, we don't create a new stack, we update the existing one.

So what we rally need is the ability to import an existing cloudformation template (from an existing stack), analyze it, add or modify resources, then generate the updated cloudformation template that can be used when updating the stack.

I know that there is something which can generate python code from a cloudformation template, but this doesn't really help. We need the existing template imported into troposphere objects that we can analyze and manipulate.

Cheers!

Robert

**Comment by muikrad** [comment]
#468 will help you achieve this. It takes an existing cloudformation template and creates a troposphere Template object out of it.

**Comment by markpeek** [comment]
Just committed #468 from @muikrad.
