### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Bazze** [cloudtools/troposphere#448]
Hello!

When do you think we will see a new release? I'd love to get some of the new juicy stuff available in master :)

**Comment by Bazze** [comment]
#455 should probably be dealt with before making a release.

**Comment by edubxb** [comment]
#456 need to be merged too.

**Comment by matalo33** [comment]
I'd love to see a new release also. Currently having to install Troposphere via git clone in order to have in-vpc lambda functions created by our CI systems :)

**Comment by markpeek** [comment]
Thanks for the reminder. I'll see about getting a new version out over the weekend after I resolve some of the outstanding issues/pr's.

**Comment by Bazze** [comment]
Any status on this @markpeek?

**Comment by zen4ever** [comment]
It would be great to get another release, since installing troposphere from master is a bit of a pain

**Comment by markpeek** [comment]
Release 1.6.0 has been pushed to github and PyPI. Thank you to all the people submitting issues and PR's.
