### ISSUE TITLE
AWS Lambda Function class doesn't support FunctionName property

### ISSUE THREAD

**Issue by 3dsorcery** [cloudtools/troposphere#450]
When creating an AWS Lambda function via troposphere, I need to be able to provide a deterministic name for the function. To do this, I need to specify the FunctionName property, but the current Function class's properties list doesn't support that. I will be adding a pull request with a fix shortly.

**Comment by terodox** [comment]
w00t!  I was wondering what piece of magic I was missing to name the function!

**Comment by 3dsorcery** [comment]
The fix for this issue has been merged - Thanks @markpeek!

**Comment by Bazze** [comment]
Anyone knows when this `FunctionName` property in CluodFormation was released by AWS? Can't find any announcement or anything about it, I've been waiting for it for ages!
