### ISSUE TITLE
ElasticSearch Naming

### ISSUE THREAD

**Issue by otm** [cloudtools/troposphere#455]
The class for ElasticsearchDomain in the elasticsearch module should maybe be named Domain to match the name in CloudFormation better and prevent stuttering in the API.

That is troposphare.elasticsearch.ElasticsearchDomain becomes troposphare.elasticsearch.Domain 
https://github.com/cloudtools/troposphere/blob/master/troposphere/elasticsearch.py#L58

Another place might be ElasticsearchClusterConfig, however I'm hesitant to rename that. How is the normal naming for this in troposphare?
https://github.com/cloudtools/troposphere/blob/master/troposphere/elasticsearch.py#L41

**Comment by markpeek** [comment]
I agree we should change the name (ElasticsearchDomain => Domain) to match the [documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html). Using ElasticsearchClusterConfig is correct per the [documentation.](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html).

**Comment by patrickpierson** [comment]
I believe this is closable.

**Comment by PatMyron** [comment]
https://github.com/cloudtools/troposphere/commit/7037c723305a9ad8f60a610969b3e6982bcd5020
