### ISSUE TITLE
API Gateway Support

### ISSUE THREAD

**Issue by svdgraaf** [cloudtools/troposphere#464]
As (just) announced here: https://aws.amazon.com/about-aws/whats-new/2016/04/aws-cloudformation-adds-support-for-amazon-api-gateway-and-updated-resource-support/

I'm currently working on a branch for a PR with the added features for API Gateway, you can find it here: https://github.com/svdgraaf/troposphere/tree/feature/apigateway

If anyone wants to help out, be my guest :)

**Comment by nmyster** [comment]
Nice job getting this done so quickly - Where are you at with it and what do you need to do!

**Comment by svdgraaf** [comment]
I have all the basics in (resources and properties), working on the example and tests, the apigateway cf configuration is a bit finicky it seems :)

**Comment by svdgraaf** [comment]
Ok, got it, I will clean it up a bit, and send in a PR

**Comment by nmyster** [comment]
I am working on CloudWatch events now to add it - seperate PR will come in a bit

**Comment by svdgraaf** [comment]
Awesome :)

**Comment by svdgraaf** [comment]
PR is in: https://github.com/cloudtools/troposphere/pull/466

**Comment by markpeek** [comment]
Merged the PR. Thanks!

**Comment by jorgebastida** [comment]
Well done! Was about to start writing this :D
