### ISSUE TITLE
Why does the UserData helper join the results with ","?

### ISSUE THREAD

**Issue by philipbjorge** [cloudtools/troposphere#465]
We tried to use the helper defined [here](https://github.com/cloudtools/troposphere/blob/master/troposphere/helpers/userdata.py) to load a shell script.
When we deployed the template, we were a bit surprised to see that the bash script failed to run because commas had been prepended to every line...

```
,
,service tyk-dashboard restart
,service tyk-gateway restart
```

Why does the UserData helper join with a `,`?

**Comment by markpeek** [comment]
This was code added from a pull request. The use case seemed to want that behavior. You might want to comment back to #376 to see what the authors intention was with the change.
