### ISSUE TITLE
New ECSTaskDefinition ContainerDefinition properties

### ISSUE THREAD

**Issue by jianyuan** [cloudtools/troposphere#474]
New fields were recently added to the ContainerDefinition property of an `AWS::ECS::TaskDefinition` resource.

Reference: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html

**Comment by philtay** [comment]
Here they are: https://github.com/cloudtools/troposphere/pull/471

**Comment by markpeek** [comment]
Agreed - closing fixed with #471
