### ISSUE TITLE
AWSHelperFn vs AWSProperty

### ISSUE THREAD

**Issue by muikrad** [cloudtools/troposphere#477]
Is there a specific reason to use an AWSHelperFn subclass instead of an AWSProperty, or is that an old legacy technique that shouldn't be used anymore?

I noticed that the deprecated dynamodb.py module used them a lot, but the new one favors AWSProperties and custom validators. I assume the latter is the right way to do it.

I located similar objects in the EC2, Cloudformation, Route53 and EMR modules.

The main problem is the inability to inspect and discover how to instantiate an AWSHelperFn dynamically. This prevents me from converting an existing CFN template into troposphere objects. Also, the fact that AWSObjects systematically skips all validations on AWSHelperFns objects means that aws properties targetting HelperFns objects are not type-checked using the usual method.

If the 'fake' helper fns cannot be easily converted to be AWSProperties, perhaps a safe first step would be to subclass AWSHelperFn into AWSBuiltinFn and TroposphereHelperFn. The former would be strictly reserved for real AWS functions and they would have additional metadata; at the minimum, the actual tag (e.g.: 'Fn::GetAtt') should be available at the class level (currently, it's added during __init__ making inspections less than ideal).

Should I go ahead and prepare a PR to at least separate those concerns? Or should we instead keep AWSHelperFn as-is and do some extra work to convert the fake functions into AWSProperties/validators?

**Comment by markpeek** [comment]
AWSHelperFn should only be used for CF intrinsic functions listed [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html). All others (items without a resource type) should be AWSProperties. Feel free to submit a PR if any are incorrect.
