### ISSUE TITLE
wrong json created for AWS::Logs::Destination

### ISSUE THREAD

**Issue by drmaples** [cloudtools/troposphere#481]
`logs.Destination` doesnt generate the correct json CloudFormation expects since [its sublcassing the wrong thing]( https://github.com/cloudtools/troposphere/blob/c75f4e2186bc06385cfbad98101e5163aeee581e/troposphere/logs.py#L5). should be `AWSObject` instead of `AWSProperty`

attempting to create the stack throws this exception
```python
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Invalid template resource property 'DestinationName'
```

bad json output
```json
"MyLogDestination": {
    "DestinationName": "destination-name",
    "DestinationPolicy": "destination-policy-arn",
    "RoleArn": "role-arn",
    "TargetArn": "target-arn",
    "Type": "AWS::Logs::Destination"
}
```

according to the [docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-destination.html), the output should look like this:
```json
"MyLogDestination": {
    "Properties": {
        "DestinationName": "destination-name",
        "DestinationPolicy": "destination-policy-arn",
        "RoleArn": "role-arn",
        "TargetArn": "target-arn"
    },
    "Type": "AWS::Logs::Destination"
}
```

**Comment by markpeek** [comment]
Thanks. I pushed a fix at about the same time you did. :-)
