### ISSUE TITLE
Selecting LaunchConfigurationName

### ISSUE THREAD

**Issue by fiunchinho** [cloudtools/troposphere#488]
I'd like to select the name when creating a new LaunchConfiguration. I'd like to have a new LaunchConfiguration every time I deploy, so a new LaunchConfiguration is created with the current timestamp. That way, the CloudFormation gets updated since it's a new LaunchConfiguration.

How can I set the name for the LaunchConfiguration creation?

**Comment by phobologic** [comment]
Every resource in Cloudformation (and troposphere) is named- if you check out the autoscaling example, it shows how to setup a LaunchConfiguration.  The name is the first property of every resource.

https://github.com/cloudtools/troposphere/blob/master/examples/Autoscaling.py#L128

**Comment by phobologic** [comment]
BTW, it's worth mentioning, that that is the Cloudformation 'Virtual Name' - it will add characters to create a 'Physical Name' for the object.  Keep in mind that CloudFormation virtual names have limitations on what characters they take.

If you want full control over the physical name of the LaunchConfig, it doesn't look like CloudFormation allows that.

**Comment by fiunchinho** [comment]
Using Ref() for the LaunchConfiguration name fails. Any ideas?

```python
    launchconfigurationname = template.add_parameter(Parameter(
        "LaunchConfigurationName",
        Type="String",
    ))

    launchconfiguration = template.add_resource(autoscaling.LaunchConfiguration(
        Ref(launchconfigurationname),
        IamInstanceProfile=Ref(instancerole),
        AssociatePublicIpAddress=True,
        UserData=Base64(Ref(userdata)),
        ImageId=Ref(amiid),
        KeyName=Ref(keyname),
        SecurityGroups=[Ref(securitygroup)],
        InstanceType=Ref(instancetype),
    ))
```

**Comment by phobologic** [comment]
Ahh - ok, so you can't use helper functions (like Ref) in the name.  That said, can you give me an idea why you want to change the name of the LaunchConfig every time?  Do you plan to update the same stacks and change the LaunchConfig name?  Or is this so each LaunchConfig in new stacks has a different name?

**Comment by fiunchinho** [comment]
Yes, I plan to update my stack on every deploy. That way, on every deploy I keep the same ELB with the same ASG, but a new LaunchConfiguration (LC) is created. This LC name contains the version that I'm deploying together with the current timestamp. When the deploy is made, since the LC is new, a rolling update is done and all the instances in the ASG get replaced by instances for the new LC.

Keeping one LC for every deploy allows me to rollback whenever I want and keep track of all the deploys.

**Comment by phobologic** [comment]
The issue is that in that case the old LaunchConfig would be deleted from the stack each time, since it no longer exists (unless you plan on adding a new LaunchConfiguration() resource each time?  In which case using the ref doesn't give you much).  Honestly, what I'd suggest, is keeping versioned copies of each template.  Store them in S3, and launch your stacks directly from there.  Then you can name the templates whatever you like (including timestamps) and you know that any change is fully represented there.

**Comment by phobologic** [comment]
BTW, that's what we do in stacker - though we use an md5 hash of the template, rather than a timestamp (since s3 keys all have timestamps as attributes already): https://github.com/remind101/stacker/blob/master/stacker/actions/base.py#L9

**Comment by fiunchinho** [comment]
I'll take a look. Thank you for the suggestions.

**Comment by phobologic** [comment]
NP!  Good luck, and let me know if you have any other questions with this :)
