### ISSUE TITLE
Option mappings in templates for Troposphere like Pyplates.

### ISSUE THREAD

**Issue by dsmithwfm** [cloudtools/troposphere#494]
Hello,

I originally started out using Pyplates and it has an awesome feature.  That feature is a command line argument to specify an options mapping .yaml file.  This let me setup an Integration, QA, and Production environment using one Python template.  The problem is the Pyplates Github repo seems dead and an issue on DependsOn statements I opened will probably never be looked at.  I'd rather not use a tool with little to no current development so, I'm abandoning the idea of Pyplates.

This leaves me wanting to use Troposphere to convert my CF to PY and then use Troposphere py templates as needed to generate an environment options mapped CF template.  I'd love to have a Python wrapper that allows specifying options mappings.  Is there something else I'm missing to quickly set this up or should I bite the bullet and try writing my own script to generate templates by feeding the Troposphere .py file variables from my own script?

**Comment by phobologic** [comment]
Just to clarify - you mean to use options mappings in the `cfn` tool, or in troposphere in general?  Troposphere itself is just python, so you can use a yaml loaded dictionary anywhere you like.  If you are asking for this specifically with the `cfn` tool though, that might make sense, though it makes the cfn tool a bit more complex.

Another option is for you to check out out [stacker](https://github.com/remind101/stacker) - it has a concept of `Local Parameters` that is similar to this, though it is more heavy weight and does a lot more (cross stack coordination, determining update vs create automatically, etc)

**Comment by dsmithwfm** [comment]
Yes in general and your repsonse makes sense.   I'll dig in and look at python and see if I can just use a yaml to generate templates.  I'm sure it wont take much work for me to figure it out.

I'm going to keep watching stacker.  I think it's a bit heavy for me at this stage as you said but, as we are moving from Ansible to Cloudformation I'm sure I'll need more and more functionality soon.

**Comment by phobologic** [comment]
Yeah, if you just want to use a yaml file in general, you can just do something like:

```
import yaml

with open("options.yaml") as fd:
    options = yaml.load(fd.read())

```

and then use the options dictionary anywhere in the code you need.  You'll obviously want to provide the ability to change the yaml file you load, but argparse should make that easy enough.  Good luck!

**Comment by dsmithwfm** [comment]
This was super easy, updating in case some else comes across this issue...

parser = argparse.ArgumentParser(description='This Troposphere template builds an API v3 environment.')
parser.add_argument('-c', '--config', required=True, help='specify the location of a .yaml config file "mappings/test-v3.yaml"')
args = parser.parse_args()


with open(args.config) as fd:
    keys = yaml.load(fd)
    StackRole = keys["StackRole"]
    KeyPair = keys["KeyPair"]
    AppServerInstanceType = keys["AppServerInstanceType"]
    Environment = keys["Environment"]
    ImageId = keys["ImageId"]

contents of the yaml file:

StackRole: test
WfmEnvironment: v3
AppServerInstanceType: t2.micro
ImageId: ami-35eff65f
KeyPair: sage2


These variables from the .yaml can also be used to set Name tags on resources...

Tags=Tags(
        Name="api:" + StackRole + ":" + "sage" + WfmEnvironment + "php" + ":vpc:cf",
    ),

**Comment by phobologic** [comment]
Awesome, glad it worked out :)  One potential 'feature' would be to use `os.path.expanduser` on the path provided for `--config` which will allow people to do things like `--config ~/someplace/config.yaml`

Anyway, let us know if you run into any other issues!
