### ISSUE TITLE
Getting a TypeError in waf.XssMatchTuple waf.py

### ISSUE THREAD

**Issue by cigan1** [cloudtools/troposphere#498]
Traceback (most recent call last):
  File "cf_waf_ddos_elb_ssl.py", line 540, in <module>
    TextTransformation = "LOWERCASE"
TypeError: __init__() takes at least 2 arguments (1 given)

`
xss_body_detect_match_set = template.add_resource(waf.XssMatchSet(
    "XssBodyMatchSet",
    Name = "Find XSS in Body lowercase",
    XssMatchTuples = [
        waf.XssMatchTuple(
            FieldToMatch = waf.FieldToMatch(
                Type = "BODY"
            ),
            TextTransformation = "LOWERCASE"
        )
    ]
))
`

**Comment by markpeek** [comment]
Thanks. Please try the fix I just pushed.

**Comment by cigan1** [comment]
Perfect this works. Thanks.
