### ISSUE TITLE
No Example for KMS Key 

### ISSUE THREAD

**Issue by pquery** [cloudtools/troposphere#500]
Trying to write template with KMS key, the object is Key, and  looks like it is inherited from AWSObject but a solid example would be great

**Comment by bobveznat** [comment]
I have one that is simply:

    template.add_resource(
            troposphere.kms.Key(
                "KmsKey",
                Description="Key for encrypting the secrets",
                KeyPolicy=key_policy
            )
        )

Constructing the KeyPolicy is potentially the hard part. A reasonable
starting point would be to copy one from a key you generate in the EC2
console.

**Comment by pquery** [comment]
I am  working on getting this working and could commit an example once completed. 
Like you said the hardest part is the key policy

**Comment by DagW** [comment]
Did you manage to create an example of the policy @pquery ?

**Comment by phobologic** [comment]
Hey guys - I actually had to do this recently for the firehose blueprint in stacker, this might help: 

https://github.com/remind101/stacker_blueprints/blob/master/stacker_blueprints/firehose.py#L118

I'll look into including it in an example here if someone doesn't get to it first, not sure when I'll have a chance.

**Comment by DagW** [comment]
Thanks @phobologic , for me this works perfectly.

**Comment by willj12** [comment]
@phobologic's example worked for me as well, a link to the commit as the file has changed/moved.
https://github.com/remind101/stacker_blueprints/blob/53062d568a7556fc5630c228e4225ebc37bf0288/stacker_blueprints/firehose.py#L118

**Comment by drernie** [comment]
I'm confused. Did someone add an actual example of how to create a KMS policy / properly use KMS Key? If so, where?
