### ISSUE TITLE
Add Support for AWS::EC2::FlowLog

### ISSUE THREAD

**Issue by marty-sullivan** [cloudtools/troposphere#509]
VPC FlowLog was added in most recent update to CloudFormation:

[Documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-flowlog.html)

**Comment by dnarwani** [comment]
Hi,

Can this be closed please and merged into master branch? Need this asap for a client's project. 

Cheers.

**Comment by ikben** [comment]
This was added in https://github.com/cloudtools/troposphere/pull/507 so it's already in the master branch.

@dnarwani I assume you mean that  you need a new release?

**Comment by ikben** [comment]
See https://github.com/cloudtools/troposphere/pull/507

**Comment by markpeek** [comment]
#507 merged
