### ISSUE TITLE
Support for specifying protocol when mapping ports in ECS task definitions.

### ISSUE THREAD

**Issue by SamDownton** [cloudtools/troposphere#514]
As of Version 1.2 of ECS there has been the option to specify a protocol when mapping container ports in task definitions: [source](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)
It would be great if this functionality was available through troposphere, which currently only supports specifying host/container port numbers.

**Comment by phobologic** [comment]
Doesn't look like it is supported in Cloudformation yet.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions-portmappings.html

Troposphere can't support anything that cloudformation doesn't, unfortunately. As soon as that support exists though, I'm sure you will see it in troposphere.
