### ISSUE TITLE
StageDescription does not support all attributes

### ISSUE THREAD

**Issue by pbudzon** [cloudtools/troposphere#521]
Support for the following attributes is missing in ApiGateway StageDescription:

```
"ThrottlingRateLimit": (positive_integer, False),
"ThrottlingBurstLimit": (positive_integer, False),
"DataTraceEnabled": (bool, False),
"MetricsEnabled": (bool, False),
"LoggingLevel": (basestring, False),
"CachingEnabled": (bool, False),
```

as per documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-deployment-stagedescription.html

**Comment by markpeek** [comment]
Thanks!
