### ISSUE TITLE
emr.Step ActionOnFailure param does not support TERMINATE_JOB_FLOW

### ISSUE THREAD

**Issue by igozali** [cloudtools/troposphere#528]
In `emr.py`, the action_on_failure_validator function does not support TERMINATE_JOB_FLOW. 

https://github.com/cloudtools/troposphere/blob/master/troposphere/emr.py#L201-L206

According to http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/UsingEMR_TerminationProtection.html, TERMINATE_JOB_FLOW is also a possible value for ActionOnFailure.

Please add that value, since it seems to be pretty useful :)

**Comment by phobologic** [comment]
Can you validate that this is allowed when using CloudFormation to setup EMR?  It's not listed in the Cloudformation resource docs for EMR::Step:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html

**Comment by igozali** [comment]
I see, I missed that documentation. Thanks for the info!
