### ISSUE TITLE
S3ObjectVersion is spelled "SS3ObjectVersion" in the lambda Code object validation

### ISSUE THREAD

**Issue by sonya** [cloudtools/troposphere#530]
I just noticed [this](https://github.com/cloudtools/troposphere/blob/1f67fb140f5b94cf0f29213a7300bad3ea046a0f/troposphere/awslambda.py#L31) while I was reading through the code. I haven't run into problems as I haven't had to use this particular key, but it looks like something you might want to know about.

**Comment by ikben** [comment]
Good eye (and my bad)!
