### ISSUE TITLE
Iam  user has no UserName argument.

### ISSUE THREAD

**Issue by jeffreyctang** [cloudtools/troposphere#534]
Per the [docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html#cfn-iam-user-username), the User type should have a UserName argument when being created.   The object in iam.py does not have this argument.

**Comment by ikben** [comment]
See also the open pullul request #539

**Comment by markpeek** [comment]
Fixed by merging #529.
