### ISSUE TITLE
CloudFront DistributionConfiguration ViewerCertificate missing propertie

### ISSUE THREAD

**Issue by Christoph-Schabert** [cloudtools/troposphere#546]
Hello,
in the source code of troposphere 1.7.0  are the props defined as:

> class ViewerCertificate(AWSProperty):
>     props = {
>         'CloudFrontDefaultCertificate': (boolean, False),
>         'IamCertificateId': (basestring, False),
>         'MinimumProtocolVersion': (basestring, False),
>         'SslSupportMethod': (basestring, False),
>     
> 
>  }

But the documentation has an addition field:
AcmCertificateArn
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distributionconfig-viewercertificate.html

**Comment by ikben** [comment]
This has been merged to master in #540
