### ISSUE TITLE
AWS::CertificateManager::Certificate is missing

### ISSUE THREAD

**Issue by Christoph-Schabert** [cloudtools/troposphere#547]
This resource is currently not implemented.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html

class Certificate(AWSObject):
            resource_type = "AWS::CertificateManager::Certificate"
            props = {
                'DomainName': (basestring, True),
                'DomainValidationOptions': (list, False),
                'SubjectAlternativeNames': (list, False)

            }

**Comment by ikben** [comment]
It has been merged to the master branch (https://github.com/cloudtools/troposphere/blob/master/troposphere/certificatemanager.py) in #538
