### ISSUE TITLE
SizeConstraint for WAF generating JSON with the parameters wrapped in Properties

### ISSUE THREAD

**Issue by Tibrim** [cloudtools/troposphere#561]
While configuring rules for our CloudFront WAF, I encountered an error from CloudFormation due to the JSON generated for the SizeConstraint object.

The SizeConstraint object gets written as:

    {
        "Properties": {
            "ComparisonOperator": "GE",
            "FieldToMatch": {
                "Type": "BODY"
            },
            "Size": 256000,
            "TextTransformation": "NONE"
        }
    }

Based on CloudFormations documentation and the error output from CloudFormation those parameters should not be wrapped in a Properties object.

See the "Define a Size Constraint" section - 
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-waf-sizeconstraintset.html 

Error from CloudFormation:

    Status: CREATE_FAILED, Type: AWS::WAF::SizeConstraintSet, Reason: Encountered unsupported property Properties

Here is what I had defined in troposphere:

    size_constraint_set = template.add_resource(SizeConstraintSet(
        "WafSizeConstraintSet",
        Name="WafSizeConstraintSet",
        SizeConstraints=[
            SizeConstraint(
                "WafSizeConstraint",
                ComparisonOperator="GE",
                FieldToMatch=FieldToMatch(
                    Type="BODY"
                ),
                Size=256000,
                TextTransformation="NONE"
            )
        ]
    ))

I've tested removing the "Properties" object, and CloudFormation accepted that.

**Comment by markpeek** [comment]
Thanks for the issue. Fix just pushed.

**Comment by Tibrim** [comment]
Thanks, Mark!  Could you point me in the right direction of release schedule for troposphere?
