### ISSUE TITLE
Fn::GetAtt for Cloudfront Distribution returns the entire object definition 

### ISSUE THREAD

**Issue by markhorta** [cloudtools/troposphere#566]
Fn::GetAtt for Cloudfront Distribution returns the entire object definition as opposed to returning just the attribute being asked for.

template.add_output(Output(
            "CloudFrontDistributionEndpoint",
            Description="CloudFront distribution endpoint.",
            Value=GetAtt(cloudFrontDistribution, "DomainName")
        ))

Returns the following:
"Outputs": {
        "CloudFrontDistributionEndpoint": {
            "Description": "CloudFront distribution endpoint.",
            "Value": {
                "Fn::GetAtt": [
                    [
                        {
                            "DependsOn": [
                                "OriginS3BucketPolicyForCloudFront"
                            ],
                            "Properties": {
                                "DistributionConfig": {
                                    "Aliases": [
                                        {
                                            "Ref": "cloudFrontAlias"
                                        }
                                    ],
                                    "Comment": {   .............  etc.......

**Comment by markpeek** [comment]
What are you assigning to the ```cloudFrontDistribution``` variable? I believe this [example](https://github.com/cloudtools/troposphere/blob/master/examples/CloudFront_S3.py) is doing something similar and is part of our regression tests.

**Comment by markhorta** [comment]
I'm assigning a Distribution object as follows below.  If I remove the output, the generated template provisions the Cloudfront distribution appropriately.  

`cloudFrontDistribution = template.add_resource(Distribution(
            cloudFrontDistributionName,
            DistributionConfig=DistributionConfig(
                Aliases=[Ref(cloudFrontAliasParam)],
                Comment=Join("", ["Distribution for ", Ref(applicationNameParam)]),
                CustomErrorResponses=[CustomErrorResponse(
                    ErrorCachingMinTTL=300,
                    ErrorCode=403,
                    ResponseCode=404,
                    ResponsePagePath="/404.html",
                )], ..... etc.......`

**Comment by markpeek** [comment]
I replace the output section of the example I cited with your code and it worked fine for me. If you could post a gist of a minimal reproducible example then I could try to figure out what is different. Right now the only thing I can think of is you're reusing that variable in your code which is causing an issue.

**Comment by markhorta** [comment]
Mark - thank you for your speedy response.  I figured out what the issue was.  It was a copy/paste error.  I had an extra comma at the end of the section (i.e. add_resource(  ... ),   ).  The extra comma was causing the issue.  Again, I'm sorry for all the trouble
