### ISSUE TITLE
Output templates in YAML

### ISSUE THREAD

**Issue by edubxb** [cloudtools/troposphere#567]
Cloudformation now supports YAML, could be awesome the possibility to generate the templates in this format.

More info:

https://aws.amazon.com/es/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/

**Comment by SonOfBytes** [comment]
This may help in the short term
`import json
# Using yaml from package pyyaml
import yaml

t = Template(Description="My Amazing Template")

print(yaml.safe_dump(json.loads(t.to_json()), None, allow_unicode=True))`

**Comment by vaneek** [comment]
Any update on YAML support? The preceding example work only for the simplest of templates, otherwise it just spits out useless gibberish. For example intrinsic functions such as Ref or Fn::GetAtt are not properly converted to !Ref or !GetAtt

**Comment by LoicAG** [comment]
Native YAML support in troposphere would be very much appreciated!

**Comment by SonOfBytes** [comment]
The format I've seen from AWS documentation is as follows - i.e. no "!" - so I believe the above YAML output snippet should work for Ref and GettAtt.

Here is a cut and paste from AWS docs

```Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - AMI
      UserData:
        Fn::Base64: 80```

The following is sample output from the code snippet method.

```Resources:
  BaseSAMLGWInstance:
    Properties:
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - {Ref: 'AWS::Region'}
        - Fn::FindInMap: [AWSInstanceType2Arch, t2.micro, Arch]
      InstanceType: t2.micro
      KeyName: {Ref: BaseSAMLGWKeyName}
      NetworkInterfaces:
      - AssociatePublicIpAddress: 'true'
        DeleteOnTermination: 'true'
        DeviceIndex: '0'
        GroupSet:
        - {Ref: BaseSAMLGWSecurityGroup}
        SubnetId: {'Fn::ImportValue': BaseVPCSubnet1}```

**Comment by sanyer** [comment]
I would recommend using https://github.com/AutoScout24/autostacker24 for JSON->YAML conversion for now. Works without problems, just doesn't use fancy stuff (new tag-based syntax for function definition and simplified substitution) described here https://aws.amazon.com/es/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/

**Comment by pilgrim2go** [comment]
Thank @sanyer : to try autostacker24 for converting yaml from json

**Comment by markpeek** [comment]
FYI...[troposphere yaml output](https://github.com/cloudtools/troposphere/tree/markpeek-flip-yaml) using [cfn_flip](https://github.com/awslabs/aws-cfn-template-flip). Try out the branch and let me know if this suffices.

**Comment by jdbass** [comment]
@markpeek Thx,  only done very limited testing on simple stacks so far but looks promising, no immediate issues.  I'll do some work over the next couple of days using some more complex stacks and update.

**Comment by jdbass** [comment]
working well for me, generating fairly substantial templates (multiple VPCs, subnets etc...), no issues yet

**Comment by Canuteson** [comment]
This is an amazingly concise solution just for achieving YAML output, but I feel like the more compelling reason to use YAML is the extra functionality Cloudformation has added to YAML templates that is not available in JSON templates.

**Comment by LoicAG** [comment]
@Canuteson which extra functionality are you referring to? AFAIK it's only a difference of notation?

**Comment by rackerroush** [comment]
Notation would be fantastic.  Sections of a template could be included but in a disabled state to effectively toggle functionality. (Conceptually more interesting than practical perhaps).  Readability for many people is easier in YAML.  I have personally watched people struggle with getting all of the escapes correct when adding cfn-init or user sections and YAML can help simplify some of that by not needing to worry about all the nested brackets etc. 

I'm hoping to see this merged in asap.

**Comment by Canuteson** [comment]
I may have been confused. I had thought in the original announcement they'd mentioned new intrinsic fucntions that were YAML only, but I don't see any exclusive YAML features now.

**Comment by astrostl** [comment]
https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/

`When you use YAML, you can also use a new, abbreviated syntax to refer to CloudFormation functions`

**Comment by tdi** [comment]
Can we just use cfn flip inside the tropo and have to_json and to_yaml methods?

**Comment by markpeek** [comment]
@tdi I've had that implemented for a few months on a [branch](https://github.com/cloudtools/troposphere/tree/markpeek-flip-yaml) and commented earlier in the issue. Probably better to just merge it rather than wait longer. Please give it a try and let me know if it works for you.

**Comment by tdi** [comment]
It works just fine. Maybe just merge and if there are problems we can fix them on the go. It does not break `to_json` so it is a safe merge anyways.

**Comment by hammadzz** [comment]
Any updates on this?
