### ISSUE TITLE
Add AWS::KMS::Alias

### ISSUE THREAD

**Issue by chrisgilmerproj** [cloudtools/troposphere#568]
AWS just released a new resource that allows setting the Alias on a key:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-alias.html

Probably would look like this in troposphere:

```py
class Alias(AWSObject):
    resource_type = "AWS::KMS::Alias"

    props = {
        'AliasName': (basestring, True),
        'TargetKeyId': (basestring, True)
    }
``` 

Please add to your next release.

**Comment by markpeek** [comment]
Thanks!

**Comment by chrisgilmerproj** [comment]
@markpeek - thanks for the fast turnaround:)
