### ISSUE TITLE
Support Cross-Stack references

### ISSUE THREAD

**Issue by rjpereira** [cloudtools/troposphere#571]
There has been a number of new features announced recently (https://aws.amazon.com/about-aws/whats-new/2016/09/aws-cloudformation-introduces-yaml-template-support-and-cross-stack-references/). 

This issue refers to adding support to Cross-Stack references.

**Comment by markpeek** [comment]
This was already committed via #569 although the implementation may change before the next release.

**Comment by aehlke** [comment]
Any plans for a release soon now to support this, or should I just start integrating with trunk for the meantime?
