### ISSUE TITLE
Support ECS IAM Role for Task References

### ISSUE THREAD

**Issue by rjpereira** [cloudtools/troposphere#572]
There has been a number of new features announced recently (https://aws.amazon.com/about-aws/whats-new/2016/09/aws-cloudformation-introduces-yaml-template-support-and-cross-stack-references/). 

This issue refers to adding support to ECS IAM Role for Task References (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-taskrolearn)

**Comment by markpeek** [comment]
This was already committed via #556.
