### ISSUE TITLE
cfn2py generates "from troposphere.lambda import Function"

### ISSUE THREAD

**Issue by maxi-milian** [cloudtools/troposphere#573]
This import results in a syntax error (clash with Python lambda keyword).

With issue #268 the troposphere lambda module was renamed to awslambda to avoid this clash.
Hence, shouldn't cfn2py generate "from troposphere.awslambda import Function"?

**Comment by markpeek** [comment]
Thanks for the issue. I just pushed a change that should fix it.

**Comment by markpeek** [comment]
@maxi-milian ping...did this work for you?

**Comment by markpeek** [comment]
Assuming it works now.

**Comment by maxi-milian** [comment]
Sorry for my late response.

Yes, it works. Appreciating your prompt fix, thanks a lot.
