### ISSUE TITLE
Support for Fn::Sub

### ISSUE THREAD

**Issue by philipmw** [cloudtools/troposphere#577]
CloudFormation now offers the ["Fn::Sub" intrinsic function](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html), but Troposphere does not support it.

**Comment by rjpereira** [comment]
Hi.
I'm not so familiar with the whole Pull requests process, but if someone wants to pick up this one I added it with

class Sub(AWSHelperFn):
    def __init__(self, s, **kwargs):
        self.data = {'Fn::Sub': [s, kwargs]} if kwargs else {'Fn::Sub': s}

    def JSONrepr(self):
        return self.data

Cheers
