### ISSUE TITLE
ClassicLink Support

### ISSUE THREAD

**Issue by BGarretson** [cloudtools/troposphere#578]
I was wondering if/when Troposphere planned to integrate ClassicLink support into the framework

**Comment by markpeek** [comment]
Do you mean the ClassicLinkVPCId and ClassicLinkVPCSecurityGroups in autoscaling::LaunchConfiguration? If so, it went in via c2569df9. If not, please add a reference to the documentation about the feature.

**Comment by markpeek** [comment]
@BGarretson ping...any further details?

**Comment by markpeek** [comment]
Closing due to no response.
