### ISSUE TITLE
Not possible to use parameters of type `List` with VpcConfig

### ISSUE THREAD

**Issue by Schweigi** [cloudtools/troposphere#593]
`VpcConfig` is defined in Troposphere as:

```
class VPCConfig(AWSProperty):

    props = {
        'SecurityGroupIds': (list, True),
        'SubnetIds': (list, True),
    }
```

The problem is that using `list` as Python data type for `SecurityGroupIds` and `SubnetIds` prevents using parameters with type `List` (e.g. `List<AWS::EC2::Subnet::Id>`).

Sample:

```
subnets = template.add_parameter(Parameter(
    "ParamMySubnets",
    Type="List<AWS::EC2::Subnet::Id>",
    Description='My VPC subnets'
)

template..add_resource(Function(
    'MyLambda',
    VpcConfig=VPCConfig(
        SubnetIds=Ref(subnets),  # <===== doesn't work with Troposphere
    )
))
```

My current workaround is to overwrite the VpcConfig class and using `basestring` as the Python data type for `SecurityGroupIds` and `SubnetIds`.

It would be great to change VpcConfig in order to be able to use both approaches with an array and also with a single parameter of type List.

**Comment by vivricanopy** [comment]
I think this might be related: https://github.com/cloudtools/troposphere/issues/607

**Comment by vivricanopy** [comment]
^ otoh probably not; that was just a misunderstanding

**Comment by markpeek** [comment]
The use of Ref() should work fine as we override the type checking for those AWS functions. Are you running a recent troposphere (much older versions didn't have this override)? Or could you post a fuller example with the error you are seeing?

**Comment by Schweigi** [comment]
@markpeek Thanks! I tried to reproduce the problem with a clean sample project and v1.8.2. It worked correctly.

Will close this issue.
