### ISSUE TITLE
ecs.Environment should accept Ref, GetAtt, Join, etc. in values

### ISSUE THREAD

**Issue by vpal** [cloudtools/troposphere#600]
```
env = ecs.Environment(
        'EnvTitle',
        Name='EnvName',
        Value=Ref('EnvProperty'),
)
```

Combination of these functions as a value of an Environment are valid and working.

I know it states sting here, but it seems that this string value can also come from an output of a CF function:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions-environment.html

I guess the same is true for Name, haven't tried it though.

**Comment by phobologic** [comment]
Have you actually had an issue using it?  This line of code should allow it, and we use `Ref`'s as the Value of ecs Environments at my work regularly (for an Open Source example, see: https://github.com/remind101/stacker_blueprints/blob/master/stacker_blueprints/empire/daemon.py#L427) .  If you have an error, can you share the exception?  Closing this for now, if you have an exception go ahead and share it and I'll re-open.  Thanks!

**Comment by vpal** [comment]
Sorry, the cause of my issue was different, but I mislead myself by reading troposphere code.
Thanks for the help.
