### ISSUE TITLE
Support for ecs.TaskDefinition#networkMode is missing

### ISSUE THREAD

**Issue by mbuccini** [cloudtools/troposphere#604]
It would be great to have support for "networkMode" in ecs.TaskDefinition. It's a feature offered since the 15th of August (as reported [here](https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-ec2-container-service-now-supports-networking-modes-and-memory-reservation/)).

This way, it would be possible to specify the networkMode for a container, e.g., "host", "bridged", etc.

**Comment by mbuccini** [comment]
Okay, just as an update: https://forums.aws.amazon.com/thread.jspa?threadID=239577 

It seems that this feature is not available yet in CloudFormation. However, when this is available, it would be nice to have it in Troposphere as well.

**Comment by phobologic** [comment]
Yep - as soon as it's available, I'm sure it'll get pulled in.  People drop PRs within hours of the updates.
