### ISSUE TITLE
Export=Name() not supported

### ISSUE THREAD

**Issue by wesleywh** [cloudtools/troposphere#610]
Troposphere version: 1.8.2

When using the following syntax in the "Output" section:

```
template.add_output(Output(
    "myoutputname",
    Export=Name(Sub("${AWS::StackName}-mynewoutput")),
    Description="my description",
    Value=Ref("myRefValue")
))
```

It outputs:
```
"myoutputname": {
            "Description": "my description",
            "Export": {
                "Fn::Sub": "${AWS::StackName}-mynewoutput"
            },
            "Value": {
                "Ref": "myRefValue"
            }
        }
```

and it should be:

```
"myoutputname": {
            "Description": "my description",
            "Export": {
                "Name": {
                      "Fn::Sub": "${AWS::StackName}-mynewoutput"
                 }
            },
            "Value": {
                "Ref": "myRefValue"
            }
        }
```

As you can see it is simply missing the ability to use:

> Name(...)

That means you will not be able to use the "Output" sections other than to show values and not use them in other templates. (Unless you input this manually)

**Comment by markpeek** [comment]
Are you wanting to do this using Export()?

```
Export=Export(Sub("${AWS::StackName}-mynewoutput")),
```

**Comment by wesleywh** [comment]
Oh I guess I was just using it wrong. Sorry about that.
Reading the documentation for aws: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html

shows the use of name. That's why I thought to use it in the form of

```
Export=Name(Sub("${AWS::StackName}-mynewoutput")),
```

vs

```
Export=Export(Sub("${AWS::StackName}-mynewoutput")),
```
