### ISSUE TITLE
Bucket Resource S3Key Rules howto?

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [cloudtools/troposphere#613]
Hi,

For some reason I am unable to figure out how to use Filters for S3Key Rules in Bucket Resource. Can you provide an example how to set Filter Rules for Prefix and Suffix. See CloudFormation Template snippet below:

```
            "Filter" : {
              "S3Key" : {
                "Rules" : [{
                  "Name" : "Prefix",
                  "Value" : "FileName"
                },
                {
                  "Name" : "Suffix",
                  "Value" : "gz"
                }]
              }
            },
```

Thanks in advance

**Comment by markpeek** [comment]
Try something like this:
```
from troposphere.s3 import Filter, Rules, S3Key

rules = [
    Rules(Name="Prefix", Value="FileName"),
    Rules(Name="Suffix", Value="gz"),
]
f = Filter(S3Key=S3Key(Rules=rules))
```

**Comment by c2xbrhdj6u4qs15** [comment]
Hi Mark,

Thanks a lot for your quick response. I updated my script using your suggesting, but getting following error now:

`Traceback (most recent call last):
  File "my_lambda_cfn.py", line 259, in <module>
    Function=GetAtt(LambdaFunction, "Arn")
  File "/usr/local/lib/python2.7/dist-packages/troposphere/__init__.py", line 262, in __init__
    super(AWSProperty, self).__init__(title, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/troposphere/__init__.py", line 78, in __init__
    self.__setattr__(k, v)
  File "/usr/local/lib/python2.7/dist-packages/troposphere/__init__.py", line 131, in __setattr__
    self._raise_type(name, value, expected_type)
  File "/usr/local/lib/python2.7/dist-packages/troposphere/__init__.py", line 166, in _raise_type
    expected_type))
TypeError: <class 'troposphere.s3.NotificationConfiguration'>: None.LambdaConfigurations is <class 'troposphere.s3.LambdaConfigurations'>, expected [<class 'troposphere.s3.LambdaConfigurations'>]
`
I am using NotificationConfiguration/LambdaConfigurations in S3 Bucket see code below:
`S3Bucket = t.add_resource(Bucket(
    "MyBucket",
    AccessControl=BucketOwnerFullControl,
    BucketName=Ref("MyBucket"),
    NotificationConfiguration=NotificationConfiguration(
        LambdaConfigurations=LambdaConfigurations(
            Event="s3:ObjectCreated:*",
            Filter=Filter(S3Key=S3Key(Rules=S3KeyRules)),
            Function=GetAtt(LambdaFunction, "Arn")
        )
    ),
))`

Thanks in advance

Regards

**Comment by markpeek** [comment]
I believe this is a list as implied in the documentation:
```
LambdaConfigurations=[LambdaConfigurations(...)],
```

**Comment by c2xbrhdj6u4qs15** [comment]
Thanks a lot. That worked! One more Question: How to add multiple Tags to a S3 Bucket Resource, would you be able to provide an example?

Regards

**Comment by markpeek** [comment]
This thread should probably continue on the mailing list or stackoverflow. To answer your question, use something like:
```
Tags=Tags(key1="value1", key2="value2")
```

**Comment by c2xbrhdj6u4qs15** [comment]
Thanks for all your help and prompt response.
