### ISSUE TITLE
Create N number of instances from Cloudformation Template

### ISSUE THREAD

**Issue by jk1510karti** [cloudtools/troposphere#623]
Hi,

How Can I specify number of instance in my template. My requirement is, User will input the number of required instances, based on that the EC2 instance should be spin up. I will use single AMI image in all instances.

Please let me know the syntax for the same.

Timely response much appreciated.
Warm Regards,
Karthik

**Comment by pbudzon** [comment]
You can use an AutoScalingGroup and set DesiredCapacity to the parameter set from the user.

Although this question isn't specific to troposphere, and directly to CloudFormation...

**Comment by jk1510karti** [comment]
thank you @pbudzon
