### ISSUE TITLE
CloudFront on S3 example is buggy!

### ISSUE THREAD

**Issue by emayssat-ms** [cloudtools/troposphere#636]
d = Distribution(
            "PacDistribution",
            DistributionConfig=DistributionConfig(
                Origins=[
                    Origin(
                        Id="Origin 1",
                        DomainName=Ref('S3DNSName'),
                        S3OriginConfig=S3Origin(),                      # This line is missing
                        )
                ],
                DefaultCacheBehavior=DefaultCacheBehavior(
                    TargetOriginId="Origin 1",
                    ForwardedValues=ForwardedValues(
                        QueryString=False
                    ),
                    ViewerProtocolPolicy="allow-all"
                ),
                Enabled=True
            )
        )

**Comment by markpeek** [comment]
I believe the line you mentioned as missing is [here](https://github.com/cloudtools/troposphere/blob/master/examples/CloudFront_S3.py#L33) in the examples.

**Comment by emayssat-ms** [comment]
Sorry, I wan't using the latest version .... I just cloned it. Thx.
