### ISSUE TITLE
Using Environment Variables with Lambda 

### ISSUE THREAD

**Issue by vincentvdk** [cloudtools/troposphere#649]
Today I tried to add **Environment Variables** to a Lambda function but this resulted in some issues. Apparently there are 2 PR merged in the 1.9.1 release ( #616 and #631 ). One uses a _dict_, the other uses a _Class_ (which is currently used).

When I try to use this  in a stack where I also use Elastic Beanstalk, the following error occurs:

```
AttributeError: Environment object does not support attribute ApplicationName
```

When I import the _Environment_ Class under a different name like so:
```
from troposphere.awslambda import Environment as lambdaenv
````

And then do something like this:
```
lambda_functionname = t.add_resource(Function(
    'lambdaFunction',
    Condition="IsProd",
    FunctionName=Join("-", [Ref(namespace_proj_param), "prod", "FunctionName"]),
    Environment=lambdaenv(
        Variables={'ENV_VAR': 'varvalue'}
    ),
    Code=Code(
````
Then it works.

Not sure if I'm doing something wrong or if I'm missing something though. But might renaming the _Environment_ Class be a solution to this?

**Comment by markpeek** [comment]
I believe you're indicating that multiple files (elasticbeanstalk and awslambda) have an Environment class. These classes are following the naming from CloudFormation. The correct way to handle this is to either rename with 'as' like you did above or not use import-from (and use fully qualified modules.
