### ISSUE TITLE
Wrong limit for conditions in template

### ISSUE THREAD

**Issue by mello7tre** [cloudtools/troposphere#657]
in troposphere/__init__.py
add_condition functions:
```
    def add_condition(self, name, condition):
        if len(self.conditions) >= 60:
            raise ValueError('Maximum of 60 conditions per template reached')

        self.conditions[name] = condition
```

apparently CloudFormation do not have such limit!!
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html

60 is the limit for Outputs and Parameters.

**Comment by markpeek** [comment]
@lil-cain could you comment on this issue? Thanks.

**Comment by mello7tre** [comment]
After i received the error message "Maximum of 60 conditions per template reached", i searched for documents that confirmed the existence of that limit, and apparently that limit do not exist!
I manually changed the code to allow a number of condition greater than 60, submitted the resulting template to CloudFormation and all worked without problem.
So there is no such limit.

**Comment by lil-cain** [comment]
Huh. I was certain I checked all the limits in the docs at the time (as
there was at least one that I had to change as I was mistaken about it). I
am more inclined to trust the current docs than me though.

**Comment by mello7tre** [comment]
no problem, just wanted to signal it, so that it will be "globally" fixed.
Maybe if someone can ask some "aws guru" to know if they are really unlimited or if an upper limit does exist.

**Comment by braidenj** [comment]
Sorry this limit was missing from our docs. This has been added and will go out with our documentation update.

**Comment by mello7tre** [comment]
Do you mean that the limit does exist ?
Strange as i submitted a template with more than 60 conditions and it has been accepted and worked without problem!
Would be a really sad news and a problem if you are limited to 60 conditions in a template.

**Comment by braidenj** [comment]
There is not a 60 condition max. There is no limit of the number of conditions you can have.

**Comment by markpeek** [comment]
Thanks @braidenj for the clarification. I just pushed a change to remove the limit check.
