### ISSUE TITLE
ecr.PutImage returns not alphanumeric exception when using "-" in name

### ISSUE THREAD

**Issue by moshe0076** [cloudtools/troposphere#660]
Hi,
I get this exception:
ecr.PutImage\n  File \"/usr/local/lib/python2.7/dist-packages/troposphere/__init__.py\", line 83, in __init__\n    self.validate_title()\n  File \"/usr/local/lib/python2.7/dist-packages/troposphere/__init__.py\", line 198, in validate_title\n    raise ValueError('Name \"%s\" not alphanumeric' % self.title)\nValueError: Name \"crud-demo\" not alphanumeric", "stdout": "", "stdout_lines": [], "warnings": []}

But I can create the repository via the console with the same name (crud-demo)

Version: 1.9.2

**Comment by markpeek** [comment]
It would be best to post a snippet of your code for better diagnosis. But I suspect this is a duplicate of the FAQ described in these issues: #344 and #311. The title (first parameter to PutImage) must be alphanumeric only. The repositoryName used for PutImage can contain additional characters.

**Comment by moshe0076** [comment]
Hi,

Thanks for the prompt response!

You are absolutely right - my mistake. Now it works perfectly.

Thanks!
