### ISSUE TITLE
Tags on EBSBlockDevice

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [cloudtools/troposphere#662]
I was unclear in issue #658.

I have a LaunchConfiguration with a BlockDeviceMapping.

Can I somehow add tags to my EBSBlockDevice? There does not seem to be an option for this.

**Comment by horacio3** [comment]
Doesn't look like it from the docs:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig-blockdev-template.html

**Comment by markpeek** [comment]
Right, this looks like you're using autoscaling and I don't see a way to set tags for the EBSBlockDevice.
