### ISSUE TITLE
How I can change the default param from python

### ISSUE THREAD

**Issue by ismaelfernandezscmspain** [cloudtools/troposphere#663]
How I can pass other value from python to keyname_param?
I Have:
```
template = Template()

keyname_param = template.add_parameter(Parameter(
    "KeyName",
    Description="Name of an existing EC2 KeyPair to enable SSH "
                "access to the instance",
    Default="param",
    Type="String",
))
```

**Comment by markpeek** [comment]
I'm not sure I understand your question. Do you want to add multiple Parameters? There are uses of Parameters in the example directory that might help.

**Comment by ismaelfernandezscmspain** [comment]
Not, 

I want to pass other value to key_param.
I have param as a default with value `param`
I'm calling my troposphere template like:
`python template.py`
When I calling a CloudFormation I can pass the vars to set my template.
How can I do this from troposphere?

**Comment by glitchindustries** [comment]
@ismaelfernandezscmspain You wouldn't necessarily do it from within troposphere, you would pass it as a variable using boto3 or one of the other aws sdk's. Below is how you could do it using Boto3:
`cfparams = []
cfparams.append({'ParameterKey' : 'KeyName', 'ParameterValue': <value you want to pass here or variable>, 'UsePreviousValue' : False )
`
and then in your create_stack function use 'Parameters=cfparams,'

That should do what you're asking.

**Comment by ismaelfernandezscmspain** [comment]
👍 works it!

thanks!

**Comment by emayssat-ms** [comment]
Troposphere just generate a template FILE. Nothing else! You can change the default value in template generation process or (better) you call your template with a non-default parameter! You can accomplish the latter with boto or from the aws cli, i.e. 

aws cloudformation create-stack --stack-name myteststack --template-body file:////home//local//test//sampletemplate.json --parameters ParameterKey=KeyPairName,ParameterValue=TestKey ParameterKey=SubnetIDs,ParameterValue=SubnetID1\\,SubnetID2
