### ISSUE TITLE
userdata - interpolate stack variables into file

### ISSUE THREAD

**Issue by brettswift** [cloudtools/troposphere#677]
It'd be great if we could interpolate variables within an external userdata file. 

Problem statement: 

given this: 
   ` UserData=userdata.from_file('./templates/userdata/userdata.sh'),`

and a requirement to drop in a cfn-signal that contains parameters at the end of the script: 

```
    "cfn-signal -e 0",
        "    --resource AutoscalingGroup",
        "    --stack ", Ref("AWS::StackName"),
        "    --region ", Ref("AWS::Region"), "\n"
```

I'd like to have a way to drop params and have them replaced within the external file.  :)

Maybe there's a magical way I haven't come across?

**Comment by phobologic** [comment]
@brettswift In stacker we have the `file` lookup, which handles loading a file and replacing certain patterns with `Ref` statements.  You can see that here:

https://github.com/remind101/stacker/blob/master/stacker/lookups/handlers/file.py

**Comment by markpeek** [comment]
I haven't looked at the code but could there be a variant that does dictionary based string formatting against the file being imported?

**Comment by brettswift** [comment]
@phobologic  cool - I'm pretty new to trop but stacker is on the radar as well.  I'm more familiar with ruby but I'm sure there's a robust templating language on the python side that would be a good candidate.   At risk of bloating the code for a fringe case.

The simple one would be along the lines of @markpeek - pass a dict into the function and find / replace.   Likely not a massively hard PR to throw in.  Even for a ruby guy :)

**Comment by brettswift** [comment]
Another use case: 
This would need to be a generic function for other files not just userdata. 

For instance putting environment variables into a buildspec file for codebuild.    

It's nicer to have a buildspec as a .yml file a opposed to inline with \n carriage returns all over :)

I haven't done the work around yet. I'm guessing someone has?

**Comment by hybmg57** [comment]
#724 should address this issue. I have tested it. It would be great if we can merge this one in @markpeek

**Comment by brettswift** [comment]
@hybmg57  that will still result in a Base64 string though?

#683  is another ticket I created that might solve this one, if we can bring files in that aren't base64 encoded, then you can wrap the result in a `Sub()` function and use template variables directly in the files.
