### ISSUE TITLE
Missing ReplaceUnhealthyInstances property in SpotFleetRequestConfigData

### ISSUE THREAD

**Issue by EugeniuZ** [cloudtools/troposphere#678]
Hi,

Please add the ReplaceUnhealthyInstances property to SpotFleetRequestConfigData class.

Documentation: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html

Oddly, it is missing here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications.html

**Comment by markpeek** [comment]
There is a lag on some properties getting implemented into the CloudFormation resources. I would suggest putting the request for this into the AWS help system or the CloudFormation forums. Closing for now until it is implemented in CF.
