### ISSUE TITLE
ApiGateway Model Schema should be a Dict not a string

### ISSUE THREAD

**Issue by tradenity** [cloudtools/troposphere#679]
troposphere.apigateway.Model class contains a property called schema, it is defined as 'basestring', this property should be a dict.

Ideally, you should supply a class to represent 'Schema'

**Comment by markpeek** [comment]
The documentation for the CloudFormation Schema property is type "JSON object". As such you should be able to create the basestring using json.dumps(your_dict). Give that a try as a work around for now. Looking at it I could allow both a basestring and dict with the dict doing the json.dumps() in the validator. I'll leave this issue open for now to remind me to try that out.

**Comment by tradenity** [comment]
Hi
Thanks, This worked, it temporary solved the problem, but I think it is like a hack not a permanent solution.

It is better to make it a dict instead of basestring, or to make a class to model the Schema element

Thanks a lot
