### ISSUE TITLE
support sourcing  codebuild buildspec from a file

### ISSUE THREAD

**Issue by brettswift** [cloudtools/troposphere#683]
https://github.com/cloudtools/troposphere/blob/master/troposphere/helpers/userdata.py

That reads from a file and base64 encodes the string.   

buildspec yml files are expected to be one honkin line with carriage returns - not base64 encoded.

**buildspec docs**
http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-example

**Feature Desired**
A helper/buildspec.py  that reads from a file and joins the file to one big long string would be awesome.

I'm not sure how much re-use on the file reading here would keep this module DRY, but maybe we abstract that if a 3rd instance comes around.   

Thoughts?

I'm pretty much a python noob.. but guessing we'd remove the blank lines always: 

```python
 #!/usr/bin/python

def from_file_to_oneline(filepath):
    """
    Imports userdata from a file.
    :type filepath: string
    :param filepath
    The absolute path to the file.
    :type delimiter: string
    """

    data=""

    try:
        with open(filepath, 'r') as thefile:
            data=thefile.read()

    except IOError:
        raise IOError('Error opening or reading file: {}'.format(filepath))

    return data

```

sound about right?  Unless there's an easier way to just read a file - the line endings will come for free in this example.

**Comment by phobologic** [comment]
Hey @brettswift, I'd be up for having a helper for this, though it's a pretty simple use case.  In general I think this could be simplified to:

```
with open(filepath, 'r') as fd:
    return fd.read().replace('\n', '\\n')
```

I don't think there's any reason to catch the exception, since it'd hide any specifics of the IOError itself - might as well let the IOError bubble up directly.  This would also replace the actual newline characters with the string for the newline character, which I think is necessary here:

```
>>> x = """abc
... def
... ghi
... """
>>> x.replace("\n", "\\n")
'abc\\ndef\\nghi\\n'
>>> print x.replace("\n", "\\n")
abc\ndef\nghi\n```

**Comment by pbudzon** [comment]
Are you sure this is needed? I'm working with CodeBuild and specs stored in external files, and use them like this:
```
with open(os.path.dirname(os.path.realpath(__file__)) + "/buildspecs/whatever.yaml") as spec:
    build_spec = spec.read()

codebuild.Project(
    "CodeBuildProject",
     ...
    Source=codebuild.Source(
        Type="...", #whatever here
        BuildSpec=build_spec
    ),
)
```

where `buildspecs/whatever.yaml` is a "normal" yaml buildspec file, and this works perfectly fine without any transformations done to the file.

**Comment by markpeek** [comment]
@pbudzon thank you for following up. @brettswift the code in helpers/userdata.py was intended to be used with the EC2 UserData property which does require the Base64 transform on the file. Per the comments by @pbudzon and @phobologic, I'm not sure this warrants inclusion for this limited use case.
