### ISSUE TITLE
Can we have ipv6 support? Apple force us to be ipv6 ready now.

### ISSUE THREAD

**Issue by grapemix** [cloudtools/troposphere#686]
Background:

Recently, Apple force all iOS app works in ipv6 only environment, that force all the backend system ipv6 ready. So the ipv6 feature is not optional for companies who have iOS product.

According to the [aws doc](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html), CF should have some support for ipv6. When we applied those ipv6 tag, like Ipv6CidrBlocks, we found that troposphere is not ipv6 ready yet. Currently, we have to manually edit thru aws web interface, but we would hope troposphere be ipv6 ready soon.

Thanks a lot for your time and this wonderful lib.

**Comment by markpeek** [comment]
What version are you running today? Most of the IPv6 changes went into 1.9.1 and there was an PR for one that was missed (https://github.com/cloudtools/troposphere/commit/1f170ca00ca45f42254063bf25de2daa95dbdbc9) that is awaiting release.

**Comment by grapemix** [comment]
boto==2.46.1
troposphere==1.9.2

And I double check https://github.com/cloudtools/troposphere/blob/master/troposphere/ec2.py
Ipv6CidrBlocks is not in the props list.

the props I am using are : Ipv6CidrBlocks, DestinationIpv6CidrBlock, CidrIpv6 and Ipv6CidrBlock. Some people may need more props and all ipv6 props are listed in the aws doc.

Thanks for your reply.

**Comment by markpeek** [comment]
The commit adding these is this one: https://github.com/cloudtools/troposphere/commit/b29a4b34679f3106a551d27e2f4fee275e8128d8 and is in 1.9.2.

Note: you mentioned Ipv6CidrBlocks (trailing "s") but it is singular Ipv6CidrBlock.

**Comment by grapemix** [comment]
I see. That is why the confusion is there.

From the aws [VPC doc](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html), the prop "Ipv6CidrBlocks" has "s" in there. In AWS::EC2::Subnet and AWS::EC2::VPC, the prop "Ipv6CidrBlocks" has "s" at the end.

But for "AWS::EC2::NetworkAclEntry" , the prop "Ipv6CidrBlock" is without "s".

According to the [aws release note](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html), 

AWS::EC2::Subnet
Added the Ipv6CidrBlocks attribute for the Fn::GetAtt function.
AWS::EC2::VPC
Added the Ipv6CidrBlocks attribute for the Fn::GetAtt function.


Thanks for your patient.

**Comment by markpeek** [comment]
Looks like a difference between the resource/properties and using GetAtt. Thanks for following up.
