### ISSUE TITLE
Some small DBSecurityGroup issue

### ISSUE THREAD

**Issue by yhajji94** [cloudtools/troposphere#700]
Hi,

I'm trying to include the parameter EC2SecurityGroupName in an RDS DBSecurityGroup, however I keep getting the error " EC2SecurityGroupName" is not defined. I may be wrong in the syntax but I can't find any exemple to have a reference. Could you please help me? 

I wrote the part like this : 

```
#Create rds security group
dbsecuritygroup = rds.DBSecurityGroup("rdssecurity")
dbsecuritygroup.DBSecurityGroupIngress = [(
        EC2SecurityGroupName(Ref(sg))
)]

temp.add_resource(dbsecuritygroup)

```

**Comment by markpeek** [comment]
Untested but try something like:
```
#Create rds security group
dbsecuritygroup = rds.DBSecurityGroup("rdssecurity")
dbsecuritygroup.DBSecurityGroupIngress = [
    RDSSecurityGroup(EC2SecurityGroupName=Ref(sg)),
]
```

**Comment by yhajji94** [comment]
Thank you very much, it worked just fine :) !
