### ISSUE TITLE
CodeBuild Artifacts NameSpaceType not Supported

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [cloudtools/troposphere#701]
Hi,

Just came across the Issue with CodeBuild Artifacts Property NameSpaceType. AWS Cloudformation gives me following error:

> Property validation failure: [Encountered unsupported properties in {/Artifacts}: [NameSpaceType]]

which means that Cloudformation only supports Property "NamespaceType" and not "NameSpaceType" according to the [AWS Documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-artifacts.html). Can you please update this at your end.

Please let me know if you require more information.

Regards

**Comment by markpeek** [comment]
Thanks for the issue.
