### ISSUE TITLE
Add attribute for AWS::IAM::ManagedPolicy

### ISSUE THREAD

**Issue by mentalblock** [cloudtools/troposphere#714]
Please add support for the attribute 'ManagedPolicyName' for the 'AWS::IAM::ManagedPolicy' resource. This will make listing my managed policies more readable.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-managedpolicyname

**Comment by markpeek** [comment]
ManagedPolicyName has now been added. Thanks for the issue.
