### ISSUE TITLE
ECS PlacementConstraint TypeError

### ISSUE THREAD

**Issue by marty-sullivan** [cloudtools/troposphere#715]
I am running troposphere from the latest commit on master. When trying to use ECS PlacementConstraint in a TaskDefinition I get the following error:

    TypeError:` <class 'troposphere.ecs.TaskDefinition'>: taskDefinition.PlacementConstraints is <class 'troposphere.ecs.PlacementConstraint'>, expected [<class 'troposphere.ecs.PlacementConstraint'>]

My TaskDefinition looks similar to:

    taskDefinition = t.add_resource(TaskDefinition(
        'taskDefinition',
        TaskRoleArn=GetAtt(role, 'Arn'),
        NetworkMode='bridge',
        PlacementConstraints=PlacementConstraint(Type='distinctInstance'),

        ContainerDefinitions=[
            ContainerDefinition(
                Name='service',
                Image=Ref(serviceImage),
                Essential=True,
                MemoryReservation=256,
                PortMappings=[
                    PortMapping(
                        ContainerPort=8080,
                        HostPort=80,
                        Protocol='tcp',
                    ),
                ],
            ),

**Comment by markpeek** [comment]
I implemented this today and noticed a discrepancy on whether this is a single PlacementConstraint or a list of PlacementConstraint. I implemented it as a list given the other usage in Service. Also, I have a discussion going with the CF team to verify. Try using:
```
PlacementConstraints=[PlacementConstraint(Type='distinctInstance')],
```

**Comment by marty-sullivan** [comment]
That works, seems obvious now. The CF docs do seem to indicate it is not a list so that's where I was confused.

**Comment by marty-sullivan** [comment]
Well, now CFN is not accepting the resulting template. It complains about 'distinctInstance' not being an accepted type for the constraint. Might have to do with my task definition in particular, but I'm not sure. Either way, I will just omit this option for now until I see a working example.

**Comment by markpeek** [comment]
There is a comment [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-placementconstraints-taskdefinitionplacementconstraint.html) that _"distinctInstance is not supported in task definitions"_. Which might imply it only works with [AWS::ECS::Service](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html).

**Comment by marty-sullivan** [comment]
Ah, thanks for the clarification. I will close this now.
