### ISSUE TITLE
lambdas should support tags

### ISSUE THREAD

**Issue by cp16net** [cloudtools/troposphere#716]
Looking at the latest documentation on lambdas, they now support tags applied to them. 
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

Should update the lambda part to support this like other objects.

**Comment by markpeek** [comment]
Already committed via #705. It should be in a new release soon but I'm still resolving some of the latest update doc discrepancies with AWS engineering.
