### ISSUE TITLE
Cloudformation parameter of type "number" expects basestring for value attributes

### ISSUE THREAD

**Issue by wilvk** [cloudtools/troposphere#717]
With the following code:

```
ASGMinSize = t.add_parameter(Parameter(
    "ASGMinSize",
    Default=1,
    MinValue=1,
    Type="Number",
    Description="Minimum Instances for Autoscaling Group.",
    MaxValue=2,
))
```

I am getting the error:

> TypeError: <class 'troposphere.Parameter'>: ASGMinSize.Default is <type 'int'>, expected <type 'basestring'>

This is easily fixed by quoting the fields such as:

```
ASGMinSize = t.add_parameter(Parameter(
    "ASGMinSize",
    Default="1",
    MinValue="1",
    Type="Number",
    Description="Minimum Instances for Autoscaling Group.",
    MaxValue="2",
))
```

As the former is how it was originally converted from cloudformation templates using /scripts/cfn2py and given a number field should be a numeric, it would make sense to allow a special type for the field `Default` and for `MinValue` and `MaxValue` to be of type integer.

**Comment by markpeek** [comment]
This looks like just a bug in Default that should be fixed. The validators for Min/Max Value/Length should allow for integer types to be specified. For reference the code is [here](https://github.com/cloudtools/troposphere/blob/master/troposphere/__init__.py#L578).

**Comment by wilvk** [comment]
Have created PR #718 for this.
