### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jwineinger** [cloudtools/troposphere#719]
Hi, could you make a new release and publish to pypi?

Release 1.9.3
@markpeek markpeek released this on Apr 13 · 13 commits to master since this release

thanks!

**Comment by markpeek** [comment]
There have been some documentation issues that I have been clarifying with the Cloud Formation team which has caused a release delay. I just tagged 3 remaining issues for the next (1.9.4) release.

**Comment by jwineinger** [comment]
Thanks!

**Comment by markpeek** [comment]
Sorry for the delay as new pieces were coming in. 1.9.4 was just released.
