### ISSUE TITLE
EMR: AutoScalingPolicy property missing from InstanceGroupConfigProperty

### ISSUE THREAD

**Issue by sairavi** [cloudtools/troposphere#726]
InstanceGroupConfigProperty is missing AutoScalingPolicy

**Comment by bmurtagh** [comment]
This is already included as part of boto3 (as well as CloudFormation, AWS CLI, etc., but hasn't been implemented within Troposphere.

https://boto3.readthedocs.io/en/latest/reference/services/emr.html#EMR.Client.put_auto_scaling_policy

Any assistance for implementing this is appreciated.
