### ISSUE TITLE
Resource does not support attribute type DNSName in Fn::GetAtt

### ISSUE THREAD

**Issue by mijndert** [cloudtools/troposphere#730]
I have a CloudFront distribution called 'distribution'. Now I want to create an ALIAS record in Route 53 to point to 'distribution'.

```
AliasTarget=route53.AliasTarget(
            GetAtt("distribution", "DNSName"),
        ),
```

When I try to execute the template in CloudFormation I get an error saying "Resource distribution does not support attribute type DNSName in Fn::GetAtt". 

According to this page the only supported attribute is DomainName. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution.html

But Troposphere still wants at least one attribute of DNSName for this resource type.

```ValueError: Resource DNSName required in type <unknown type>```

How do I point my ALIAS record to my CloudFront distribution?

**Comment by markpeek** [comment]
Untested but you might want to try:
```
AliasTarget=route53.AliasTarget(
    DNSName=GetAtt("distribution", "DomainName"),
    HostedZoneId="Z2FDTNDATAQYW2",
),
```
Note: I saw from the docs [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html) that HostedZoneId is required and that value is for CloudFront.

**Comment by mijndert** [comment]
Thanks @markpeek, this works for my use-case.
