### ISSUE TITLE
Error in Conditional

### ISSUE THREAD

**Issue by ismaelfernandezscmspain** [cloudtools/troposphere#734]
version:
troposphere (1.9.4)
boto (2.46.1)
boto3 (1.3.1)

I have this condtion:
elbs3logging = template.add_condition("Loggintos3", Not(Equals(Ref(elb_bucket_name, ""))))
that eval `elb_bucket_name` var:
elb_bucket_name = template.add_parameter(Parameter(
             "LoadBalancerBucketName",
             Type="String",
             Description="S3 Bucket for the ELB access logs"
         ))

and I am using it here:
loadbalancer = template.add_resource(elb.LoadBalancer(
             "LoadBalancer",
             AccessLoggingPolicy=If(elbs3logging,
                 elb.AccessLoggingPolicy(
                 EmitInterval=60,
                 Enabled=True,
                 S3BucketName=Ref(elb_bucket_name),
                 S3BucketPrefix="ELBLogs"),
                 Ref("AWS::NoValue")
                 ),

On my deployment I am getting:
`generate_cloudformation_template\n    elbs3logging = template.add_condition(\"Loggintos3\", Not(Equals(Ref(elb_bucket_name, \"\"))))\nTypeError: __init__() takes exactly 2 arguments (3 given)",`

**Comment by apmclean** [comment]
Check your close braces.  Ref requires a closing brace which you're missing.  Here's a working Not Equal from my code:
Not(Equals(Ref(PeerVpcId[x]), ""))

**Comment by phobologic** [comment]
Thanks @apmclean !  Closing this.
