### ISSUE TITLE
Null resource while adding dependent entities

### ISSUE THREAD

**Issue by darkpssngr** [cloudtools/troposphere#739]
I'm trying to create an ECS cluster using cloudformation template. However when I add the dependent entities like environment, host etc its also created as a dependent entity inside a null resource. Adding an example here. Not sure if it's a bug or if I'm coding it wrong.
Please help.
<pre>
{
    "Parameters": {
        "StackName": {
            "Description": "Name of the stack to be created",
            "Type": "String"
        }
    },
    "Resources": {
        "null": {
            "Environment": [
                {
                    "Name": "SPRING_PROFILE",
                    "Value": "local"
                }
            ],
            "Image": "arn:aws:ecr:<troposphere.Ref object at 0x104df9190>:515330135695:<troposphere.Join object at 0x104df0e90>",
            "LogConfiguration": {
                "LogDriver": "awslogs",
                "Options": {
                    "awslogs-group": {
                        "Ref": "StackName"
                    },
                    "awslogs-region": {
                        "Ref": "AWS::Region"
                    }
                }
            },
            "Memory": 500,
            "MountPoints": [
                {
                    "ContainerPath": "/billing/",
                    "SourceVolume": "billing_path"
                }
            ],
            "Name": {
                "Fn::Join": [
                    "",
                    [
                        {
                            "Ref": "StackName"
                        },
                        "-test-container"
                    ]
                ]
            }
        },
        "Repo": {
            "Properties": {
                "RepositoryName": {
                    "Fn::Join": [
                        "",
                        [
                            "freshpipe-",
                            {
                                "Ref": "StackName"
                            },
                            "/test"
                        ]
                    ]
                }
            },
            "Type": "AWS::ECR::Repository"
        },
        "ECSCluster": {
            "Properties": {
                "ClusterName": {
                    "Fn::Join": [
                        "",
                        [
                            "pipe-",
                            {
                                "Ref": "StackName"
                            }
                        ]
                    ]
                }
            },
            "Type": "AWS::ECS::Cluster"
        },
        "Service": {
            "Properties": {
                "Cluster": {
                    "Ref": "ECSCluster"
                },
                "DeploymentConfiguration": {
                    "MaximumPercent": 200,
                    "MinimumHealthyPercent": 0
                },
                "DesiredCount": 1,
                "ServiceName": {
                    "Fn::Join": [
                        "",
                        [
                            {
                                "Ref": "StackName"
                            },
                            "-test-service"
                        ]
                    ]
                },
                "TaskDefinition": {
                    "Ref": "TaskDefinition"
                }
            },
            "Type": "AWS::ECS::Service"
        },
        "TaskDefinition": {
            "Properties": {
                "ContainerDefinitions": [
                    {
                        "Environment": [
                            {
                                "Name": "SPRING_PROFILE",
                                "Value": "local"
                            }
                        ],
                        "Image": "arn:aws:ecr:<troposphere.Ref object at 0x104df9190>:515330135695:<troposphere.Join object at 0x104df0e90>",
                        "LogConfiguration": {
                            "LogDriver": "awslogs",
                            "Options": {
                                "awslogs-group": {
                                    "Ref": "StackName"
                                },
                                "awslogs-region": {
                                    "Ref": "AWS::Region"
                                }
                            }
                        },
                        "Memory": 500,
                        "MountPoints": [
                            {
                                "ContainerPath": "/billing/",
                                "SourceVolume": "billing_path"
                            }
                        ],
                        "Name": {
                            "Fn::Join": [
                                "",
                                [
                                    {
                                        "Ref": "StackName"
                                    },
                                    "-test-container"
                                ]
                            ]
                        }
                    }
                ],
                "Family": {
                    "Fn::Join": [
                        "",
                        [
                            {
                                "Ref": "StackName"
                            },
                            "-test-task"
                        ]
                    ]
                },
                "NetworkMode": "bridge",
                "Volumes": [
                    {
                        "Host": {
                            "SourcePath": "/billing/"
                        },
                        "Name": "billing_path"
                    }
                ]
            },
            "Type": "AWS::ECS::TaskDefinition"
        }
    }
}
</pre>

**Comment by markpeek** [comment]
Without seeing the python code it is hard to tell. Given the containerdefinitions show up in the taskdefinition and in the null resource, I might suspect you're reusing a variable name for one of the objects somewhere.

**Comment by markpeek** [comment]
@darkpssngr ping...any updates on this issue?

**Comment by markpeek** [comment]
No response...closing.
