### ISSUE TITLE
Cognito StringAttributeConstraints should be MinLength/MaxLength not MinValue/MaxValue

### ISSUE THREAD

**Issue by sdechgan** [cloudtools/troposphere#756]
There is bug with the definition of `cognito.StringAttributeConstraints`

with the following code:
```
class StringAttributeConstraints(AWSProperty):
    props = {
        'MaxValue': (basestring, False),
        'MinValue': (basestring, False),
    }
```

According to the AWS document
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-stringattributeconstraints.html

The properties should be:
- MaxLength
- MinLength

not 
- MaxValue
- MinValue

**Comment by markpeek** [comment]
Thanks for the issue. Should be fixed in master now.
