### ISSUE TITLE
Add support for getting attributes from BaseAWSObject

### ISSUE THREAD

**Issue by yaakov-github** [cloudtools/troposphere#760]
Currently the `__setattr__` function does this:
```elif name in self.attributes:
      if name == "DependsOn":
          self.resource[name] = depends_on_helper(value)
      else:
          self.resource[name] = value
```
but the `__getattr__` function doesn't have matching logic to retrieve attributes.  This makes it tricky to do things like dynamically update DependsOn.  Is this intentional for some reason?

**Comment by markpeek** [comment]
I'd say not intentional but more an oversight. Not sure how this would impact updates. I'm assuming you're trying to inspect/query it first? For example, this should work:
```
from troposphere.s3 import Bucket

b1 = Bucket("B1")
b2 = Bucket("B2", DependsOn=b1)
print b1.title, b2.resource["DependsOn"]
b3 = Bucket("B3")
b2.DependsOn = b3
print b1.title, b2.resource["DependsOn"]
```
and I'm assuming you would like to be able to use instead:
```
from troposphere.s3 import Bucket

b1 = Bucket("B1")
b2 = Bucket("B2", DependsOn=b1)
print b1.title, b2.DependsOn
b3 = Bucket("B3")
b2.DependsOn = b3
print b1.title, b2.DependsOn
```
