### ISSUE TITLE
Add support for AWS::CloudWatch::Dashboard

### ISSUE THREAD

**Issue by BPScott** [cloudtools/troposphere#763]
[AWS have added the ability to specify Cloudwatch Dashboards through CF templates](https://aws.amazon.com/blogs/aws/new-api-cloudformation-support-for-amazon-cloudwatch-dashboards). It'd be great to see this type supported in troposphere.

Documentation of the allowed properties: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-dashboard.html

**Comment by markpeek** [comment]
Thanks for the issue. Originally Dashboard wasn't documented which delayed its implementation. I just pushed the implementation to master.

**Comment by BPScott** [comment]
Wonderful stuff, thank you @markpeek
