### ISSUE TITLE
Parameter.NoEcho should be `boolean` type, not `bool`

### ISSUE THREAD

**Issue by ryan-ju** [cloudtools/troposphere#770]
This is a bug in `__init__.py`

**Comment by markpeek** [comment]
Do you mean validators.boolean? Did you run into this with a certain parameter that didn't get validated correctly?

**Comment by markpeek** [comment]
Ping...any clarification on this issue? Thanks.

**Comment by ryan-ju** [comment]
Sorry this is not a bug, my bad
