### ISSUE TITLE
Add all traffic to security resource

### ISSUE THREAD

**Issue by matoneski** [cloudtools/troposphere#771]
Hi, 

I want to know if it is possible to allow all traffic from and to each port using troposphere? 

`instanceSecurityGroup = t.add_resource(SecurityGroup(
    'InstanceSecurityGroup',
    GroupDescription='Enable SSH access via port 22',
    SecurityGroupIngress=[
        SecurityGroupRule(
            IpProtocol='tcp',
            FromPort='22',
            ToPort='22',
            CidrIp=Ref(sshlocation_param)),
        SecurityGroupRule(
            IpProtocol='tcp',
            FromPort='80',
            ToPort='80',
            CidrIp='0.0.0.0/0')],
    VpcId=Ref(VPC),
))`

Instead of the following, I want to enable it to all traffic? 

Cheers

**Comment by phobologic** [comment]
You want to open all ports?  If that's the case, just set `FromPort` to 1, and `ToPort` to 65535 (the highest port availabe).

**Comment by matoneski** [comment]
Just for testing atm, thanks for that.
