### ISSUE TITLE
Elasticache PreferredCacheClusterAZs issue

### ISSUE THREAD

**Issue by ntwaddell** [cloudtools/troposphere#772]
I upgraded to troposphere 1.9.4 and it broke this

    PreferredCacheClusterAZs=If(
        "ConditionName", [
            GetAtt(subneta, "AvailabilityZone"),
            GetAtt(subnetb, "AvailabilityZone"),
            GetAtt(subnetc, "AvailabilityZone")
        ], [
            GetAtt(subneta, "AvailabilityZone")
        ]
    ),

TypeError: <class 'troposphere.elasticache.ReplicationGroup'>: CluserName.PreferredCacheClusterAZs is <class 'troposphere.If'>, expected [<type 'basestring'>]

I've been messing around with a few different formats, but how can I do a condition, and still pass it a list of basestrings?

**Comment by markpeek** [comment]
I'm assuming you pulled master which isn't really 1.9.4. Thanks for the issue, I forgot about If being "special" in its return values.

**Comment by ntwaddell** [comment]
yeah from master.  Thanks @markpeek 👍
