### ISSUE TITLE
Fifo queue validator fails if name has Join in it

### ISSUE THREAD

**Issue by ntwaddell** [cloudtools/troposphere#773]
On the recent commit https://github.com/cloudtools/troposphere/commit/3a3004a183fd0d70e57b9c9d1b92763b2962d09e#diff-49966b9cf9e37556c8b76d380b9b47a5

I have a Join function to create my queue name.  Now it breaks 

 if not self.properties.get('QueueName', '').endswith('.fifo'):
AttributeError: 'Join' object has no attribute 'endswith'

**Comment by markpeek** [comment]
Thanks for the issue. Should be fixed now.

**Comment by ntwaddell** [comment]
fixed!  thanks @markpeek 👍
