### ISSUE TITLE
Example with Directory Service?

### ISSUE THREAD

**Issue by brandonshough** [cloudtools/troposphere#783]
Does troposphere support MS AD?

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-directoryservice-microsoftad.html

**Comment by markpeek** [comment]
I don't believe there are any examples but yes, it is implemented in troposphere [here](https://github.com/cloudtools/troposphere/blob/master/troposphere/directoryservice.py#L17).

**Comment by brandonshough** [comment]
Great, thanks!
