### ISSUE TITLE
Network Load Balancer Support

### ISSUE THREAD

**Issue by cwgem** [cloudtools/troposphere#805]
AWS just announced the availability of [Network Load Balancers](https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/). To support this the following Cloud Formation changes are required:

* ELB 2 resources now have a [Type attribute](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-type)
* ELB 2 resources now have a [SubnetMappings](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-subnetmappings) attribute, a primary function being attaching EIP's to the NLB
* TargetGroups now [accept IP's as targets](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-targettype)

#806 has a pull request for NLB support

**Comment by markpeek** [comment]
Fixed via merge of #806
