### ISSUE TITLE
Add Tags to AWS::EC2::NatGateway

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#826]
[AWS::EC2::NatGateway](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html)
Use the Tags property to specify resource tags for a NAT gateway.

**Comment by gkrizek** [comment]
@markpeek 

Are there plans to get the `Tags` field in EC2 classes inline with the other classes?

In `ec2.py` all Tags are: `'Tags': (list, False),`.

In most other files, Tags are `'Tags': (Tags, False),`

I realize this would be a breaking change to existing templates, just curious if there were plans.

**Comment by phobologic** [comment]
No plans, @gkrizek - if someone can come up with a reliable way that doesn't break previous templates, I think we'd be all for a PR :)  BTW, if you want to open an issue for that to track it that would be cool too.

**Comment by gkrizek** [comment]
@phobologic Good to know.

I'll create an issue for it. I might try to come up with something, but that could be a rather sizable PR so I'll see what time allows for. 

Thanks!

**Comment by gkrizek** [comment]
Issue created:
https://github.com/cloudtools/troposphere/issues/843
