### ISSUE TITLE
Use the PlatformArn property to specify a custom platform for Elastic Beanstalk.

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#828]
[AWS::ElasticBeanstalk::ConfigurationTemplate](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-beanstalk-configurationtemplate.html) and [AWS::ElasticBeanstalk::Environment](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment.html)
Use the PlatformArn property to specify a custom platform for Elastic Beanstalk.

**Comment by KrishanBhasin** [comment]
Is it possible to get a bit more detail on this issue? I'd like to pick it up :)

**Comment by markpeek** [comment]
@KrishanBhasin this should be pretty straightforward. Should just be adding the new property [here](https://github.com/cloudtools/troposphere/blob/master/troposphere/elasticbeanstalk.py#L100) for the Environment one. Same for the ConfigurationTemplate. Note: run "make test" to ensure it passes pycodestyle/pyflakes.
