### ISSUE TITLE
Add AccelerateConfiguration to AWS::S3::Bucket

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#832]
[AWS::S3::Bucket](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html)
Use the AccelerateConfiguration property to configure the transfer acceleration state for an Amazon S3 bucket.

**Comment by danielpops** [comment]
Seems straightforward enough, I'll take a look. Looks like there are only two supported values, either `Enabled` or `Suspended`.

**Comment by markpeek** [comment]
Closed via #833
