### ISSUE TITLE
AttributeError: AWS::EC2::NatGateway object does not support attribute Tags

### ISSUE THREAD

**Issue by jseiser** [cloudtools/troposphere#838]
Im attempting to create a nat gateway, the code works if I remove the Tags portion.  When adding the tags portion like the following, It throws an error.

```
            t.add_resource(
                ec2.NatGateway(
                    gateway_name,
                    AllocationId=GetAtt(eip_name, 'AllocationId'),
                    SubnetId=Ref(subnet_name),
                    Tags=Tags(
                        Customer=variables["Customer"],
                        Environment=variables["Environment"],
                        Name=Join("-", ["ngw", variables["Customer"], gateway_name, variables["Environment"]]),
                    ),
                )
            )
```

> Traceback (most recent call last):
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/bin/stacker", line 9, in <module>
>     args.run(args)
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/commands/stacker/diff.py", line 32, in run
>     action.execute()
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/actions/base.py", line 127, in execute
>     self.run(*args, **kwargs)
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/actions/diff.py", line 249, in run
>     plan.execute()
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/plan.py", line 267, in execute
>     if not self._single_run():
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/plan.py", line 227, in _single_run
>     status = step.run()
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/plan.py", line 74, in run
>     return self._run_func(self.stack, status=self.status)
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/actions/diff.py", line 214, in _diff_stack
>     new_template = stack.blueprint.rendered
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/blueprints/base.py", line 485, in rendered
>     self._version, self._rendered = self.render_template()
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/stacker/blueprints/base.py", line 459, in render_template
>     self.create_template()
>   File "./blueprints/vpc.py", line 386, in create_template
>     self.create_network()
>   File "./blueprints/vpc.py", line 220, in create_network
>     self.create_nat_instance(i, subnet_name)
>   File "./blueprints/vpc.py", line 318, in create_nat_instance
>     Name=Join("-", ["ngw", variables["Customer"], gateway_name, variables["Environment"]]),
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/troposphere/__init__.py", line 123, in __init__
>     self.__setattr__(k, v)
>   File "/home/justin/Documents/cloudformation/AWS-CloudFormation/projects/stacker/local/lib/python2.7/site-packages/troposphere/__init__.py", line 211, in __setattr__
>     (type_name, name))
> AttributeError: AWS::EC2::NatGateway object does not support attribute Tags
> 
> 

The cloudformation documentation makes it appear that this should work. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html

```
{
  "Type" : "AWS::EC2::NatGateway",
  "Properties" : {
    "AllocationId" : String,
    "SubnetId" : String,
    "Tags" : [ Resource Tag, ... ]
  }
}
```

**Comment by phobologic** [comment]
That was fixed in #835 and isn't yet released.  It was released in the CF spec late last week: https://github.com/cloudtools/troposphere/issues/826

You can always point at the github version/sha to get that feature if you need it before the release is done (probably in the next week or so.)
