### ISSUE TITLE
S3 Bucket constructor

### ISSUE THREAD

**Issue by Tonkonozhenko** [cloudtools/troposphere#841]
**Expected result:** troposphere.s3.Bucket constructor accepts `template` as a second parameter.
**Actual result:** troposphere.s3.Bucket constructor does not accept `template` as a second parameter.

Example of code that should work:
```python
template = Template()
Bucket(
    'PlaylistsFailoverS3Bucket',
    template,
    AccessControl=Private,
    BucketName="test-bucket",
)
```

**Comment by markpeek** [comment]
s3.Bucket() has a custom \_\_init\_\_.py which does not support template or validation parameters. This is likely due to it being a historical implementation prior to a more uniform way to handle validation. This needs to be refactored and fixed.

**Comment by Tonkonozhenko** [comment]
What about such fix: https://github.com/cloudtools/troposphere/compare/master...Tonkonozhenko:master ?

**Comment by markpeek** [comment]
The fix would be removing \_\_init\_\_(), moving the AccessControl validation logic into a validate() method, and validating (or adding) tests.
