### ISSUE TITLE
NatGateway in release doesn't support Tags

### ISSUE THREAD

**Issue by mjgorman** [cloudtools/troposphere#842]
Python3.6, Pip3, Troposphere 1.9.6

Master branch shows that NatGateway objects support the tags fields, the current 1.9.6 installed from pip however is missing that line in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/troposphere/ec2.py

**Comment by mjgorman** [comment]
Manually patching a tags prop in there works. Guessing something odd happened when packaged for pip?

**Comment by phobologic** [comment]
https://github.com/cloudtools/troposphere/pull/835

Only released in CF a little while ago, after the last release.  Will be in the latest release.
