### ISSUE TITLE
Example for datapipleline creation

### ISSUE THREAD

**Issue by kumar-shantanu** [cloudtools/troposphere#847]
Dear Team, 

We are trying to create cf for datapipeline and not able to do so. Can you please provide example code for the same. 

Thanks
Shantanu

**Comment by abi5090** [comment]
I am also facing some problem writing the code for creating a pipeline. Was able to get the setup working for iam policieis, roles, sns topics, events and lambda functions.

For pipeline, I see there are 3 different classes - Pipeline which contains PipelineObject, which in turn contains ObjectField. Pardon the vocab, am a newbie to python.

Essentially from what I understand is, I need to have an object of type ObjectField and add the fields to it. Then add this object to another object of type PipelineObject, finally adding that to the object of Pipeline type.  Does it make any sense? Or I am off on a tangent here?

Any sample code showing how to use these three objects/classes will be really helpful.

Also, it is possible to simply pass a json which has all the details to create the pipeline?

**Comment by markpeek** [comment]
I don't have the cycles right now for a full blown example. Here's a [partial snippet](https://gist.github.com/markpeek/ba167bd03a171e29b8f89dcccadf5d75) implementing the first par of the example from the [data pipeline docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-datapipeline-pipeline.html#w2ab2c21c10d268c13). Hopefully it is enough to get you started in the right direction.

**Comment by abi5090** [comment]
Thank you mark, We managed to get it working with the following bit of code (maynot be the cleanest, but worked for us).

`  pipelineobj = [
          PipelineObject(
             Fields=[
              ObjectField(
                Key="role",
                StringValue=pipeline_role
              ),
              ObjectField(
                Key="resourceRole",
                StringValue=pipeline_role
              ),
              ObjectField(
                Key="scheduleType",
                StringValue=SCHEDULE
              ),
              ObjectField(
                Key="failureAndRerunMode",
                StringValue=RERUNMODE
              ),
              ObjectField(
                Key="pipelineLogUri",
                StringValue=PIPELINELOG
              ),
              ObjectField(
                Key="type",
                StringValue="Default"
              ),
              ObjectField(
                Key="name",
                StringValue="Default"
              )
             ],
             Id="Default",
             Name="Default"
          ),
          PipelineObject(
             Fields=[
              ObjectField(
                Key="subnetId",
                StringValue=SUBNETID
              ),
               ObjectField(
                Key="role",
                StringValue=pipeline_role
              ),
              ObjectField(
                Key="resourceRole",
                StringValue=pipeline_role
              ),
              ObjectField(
                Key="emrManagedSlaveSecurityGroupId",
                StringValue=EMRSLAVESG
              ),
              ObjectField(
                Key="emrManagedMasterSecurityGroupId",
                StringValue=EMRMASTERSG
              ),
              ObjectField(
                Key="type",
                StringValue="EmrCluster"
              ),
              ObjectField(
                Key="coreInstanceType",
                StringValue=COREINSTANCETYPE
              ),
              ObjectField(
                Key="coreInstanceCount",
                StringValue=COREINSTANCECOUNT
              ),
              ObjectField(
                Key="masterInstanceType",
                StringValue=MASTERINSTANCETYPE
              ),
              ObjectField(
                Key="applications",
                StringValue=APPLICATIONS
              ),
              ObjectField(
                Key="releaseLabel",
                StringValue=RELEASELABEL
              ),
              ObjectField(
                Key="enableDebugging",
                StringValue=DEBUG
              ),
              ObjectField(
                Key="terminateAfter",
                StringValue=TERMINATEAFTER
              ),
              ObjectField(
                Key="region",
                StringValue=AWSREGION
              )
             ],
           Id="emrResource",
           Name=" ".join([NAME,ENVIRONMENT,"resource"])
           ),
          PipelineObject(
             Fields=[
              ObjectField(
                Key="type",
                StringValue="EmrActivity"
              ),
              ObjectField(
                Key="runsOn",
                RefValue="emrResource"
              ),
              ObjectField(
                Key="step",
                StringValue=STEP1
              ),
              ObjectField(
                Key="step",
                StringValue=STEP2
              ),
              ObjectField(
                Key="step",
                StringValue=STEP3
              )
             ],
           Id="emrActivity",
           Name=" ".join([NAME,ENVIRONMENT,"activity"])
          )
  ]
  pipeline = template.add_resource(Pipeline(
     "datapipeline",
     Activate="False",
     Name=pipeline_name,
     Description=pipeline_description,
     PipelineObjects=pipelineobj,
     DependsOn=["datapipelinerole","datapipelineinstanceprofile"]
  ))

`
The variables in CAPS are fixed and read off a file or input, while the ones in smaller case are allocated dynamically when the script runs.

I am trying to make it more modular and cleaner. Any suggestions would be welcome!

**Comment by markpeek** [comment]
I just made a comment on the mailing list that might make the above cleaner/easier to read using a list comprehension. Something like this (untested):
```
def create_object_fields(fields):
    return [ObjectField(Key=k, StringValue=s) for k, s in fields]

pipelineobj = [
        PipelineObject(
            Fields=create_object_fields((
                ('role', pipline_role),
                ("role", pipeline_role),
                ("resourceRole", pipeline_role),
                ("scheduleType", SCHEDULE),
                ("failureAndRerunMode", RERUNMODE),
                ("pipelineLogUri", PIPELINELOG),
                ("type", "Default"),
                ("name", "Default"),
            Id="Default",
            Name="Default"
            )),
        ),
]
```

**Comment by markpeek** [comment]
Closing since no further comments.
