### ISSUE TITLE
Add new AWS::SSM resources

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#850]
[AWS::SSM::MaintenanceWindow](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindow.html)
Use the AWS::SSM::MaintenanceWindow resource to create an Amazon EC2 Systems Manager Maintenance Window.

[AWS::SSM::MaintenanceWindowTarget](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindowtarget.html)
Use the AWS::SSM::MaintenanceWindowTarget resource to register a target with a Maintenance Window.

[AWS::SSM::MaintenanceWindowTask](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindowtask.html)
Use the AWS::SSM::MaintenanceWindowTask resource to define a Maintenance Window task.

[AWS::SSM::PatchBaseline](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-patchbaseline.html)
Use the AWS::SSM::PatchBaseline resource to define a Systems Manager patch baseline.

**Comment by codevbus** [comment]
I can grab some.

**Comment by codevbus** [comment]
See #851 

Assuming that looks good/is valid, I can send another PR for the remaining 3.

**Comment by markpeek** [comment]
Looked great and merged. Feel free to PR the remaining 3.

**Comment by Laxenade** [comment]
I can add one or two if no one is working on it.

**Comment by codevbus** [comment]
@Laxenade I've changes for the additional 3 completed, just working on polishing up the unit tests. I'll be submitting my PR this afternoon.

**Comment by markpeek** [comment]
Fixed via #851 and #854
