### ISSUE TITLE
AWS::Serverless::Function FunctionName unsupported

### ISSUE THREAD

**Issue by mateogianolio** [cloudtools/troposphere#856]
[The document explaining the AWS SAM 2016-10-31 transform](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction) states that `FunctionName` is a valid attribute name for `AWS::Serverless::Function`, but this attribute is missing from `troposphere/serverless.py`. Is there a reason for this or is it just a typo?

**Affected code**
https://github.com/cloudtools/troposphere/blob/264242bf01633176afa73537224fe96234643caa/troposphere/serverless.py#L55-L74

**Comment by markpeek** [comment]
Thanks. Fixed via commit 59da20f1141552836acc39212b06f5641baf7d2e.

@Laxenade I normalized Tags with this commit as well so you may want to look at the change.
