### ISSUE TITLE
ApplicationOutput/Output cardinality

### ISSUE THREAD

**Issue by mjvm** [cloudtools/troposphere#864]
I'm trying to create an ApplicationOutput[0] with a list of Outputs and the creation fails with the message: `Property validation failure: [Value of property {/Output} does not match type {Object}]`.

Reading the official documentation it seems that the Output property should be an array of Output objects but the examples show that an Output object should be used.

Changing troposphere code (#863) to accept an Output object instead of an array of Output object seems to fix the issue. 

Did anyone run into this issue before? 

[0] http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisanalytics-applicationoutput.html

**Comment by markpeek** [comment]
Fixed via #863
