### ISSUE TITLE
AWS Glue Support

### ISSUE THREAD

**Issue by cwgem** [cloudtools/troposphere#870]
This is a tracking bug for [recently added AWS Glue support to CloudFormation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)

* AWS::Glue::Classifier - Use the AWS::Glue::Classifier resource to create an AWS Glue classifier.
* AWS::Glue::Connection - Use the AWS::Glue::Connection resource to specify an AWS Glue connection to a data source.
* AWS::Glue::Crawler - Use the AWS::Glue::Crawler resource to specify an AWS Glue crawler.
* AWS::Glue::Database - Use the AWS::Glue::Database resource to create an AWS Glue database.
* AWS::Glue::DevEndpoint - Use the AWS::Glue::DevEndpoint resource to specify a development endpoint for remotely debugging ETL scripts.
* AWS::Glue::Job - Use the AWS::Glue::Job resource to specify an AWS Glue job in the data catalog.
* AWS::Glue::Partition - Use the AWS::Glue::Partition resource to create an AWS Glue partition, which represents a slice of table data.
* AWS::Glue::Table - Use the AWS::Glue::Table resource to create an AWS Glue table.
* AWS::Glue::Trigger - Use the AWS::Glue::Trigger resource to specify triggers that run AWS Glue jobs.

**Comment by markpeek** [comment]
Added via #872
