### ISSUE TITLE
awslambda.Function does not support Cloudformation Package CLI command

### ISSUE THREAD

**Issue by marty-sullivan** [cloudtools/troposphere#871]
As the title suggests, troposphere.awslambda.Function resource does not support a String argument for the Code parameter for supplying a local path. This is for the `aws cloudformation package` command in the CLI. It is likely that other resources are also missing this support as outlined in the CLI documentation below:

http://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html

The error thrown is:

TypeError: <class 'troposphere.awslambda.Function'>: MyFunction.Code is <type 'str'>, expected <class 'troposphere.awslambda.Code'>

**Comment by marty-sullivan** [comment]
Not totally familiar with the inner workings of Troposphere and AWSObject, so not sure if it is possible to allow two parameter types in a resource. However, in my own code as a temp workaround, I created my own PackageFunction Resource that looks like the following. This seems to work for now, but would be nice if Troposphere added this support.

```
class PackageFunction(AWSObject):
    resource_type = "AWS::Lambda::Function"

    props = {
        'Code': (basestring, True),
        'Description': (basestring, False),
        'DeadLetterConfig': (DeadLetterConfig, False),
        'Environment': (Environment, False),
        'FunctionName': (basestring, False),
        'Handler': (basestring, True),
        'KmsKeyArn': (basestring, False),
        'MemorySize': (validate_memory_size, False),
        'Role': (basestring, True),
        'Runtime': (basestring, True),
        'Tags': (Tags, False),
        'Timeout': (positive_integer, False),
        'TracingConfig': (TracingConfig, False),
        'VpcConfig': (VPCConfig, False),
    }
```

**Comment by markpeek** [comment]
I don't believe that will do what you want it to do. The package command appears to take your code, uploads it to S3, and then rewrites your template to use that uploaded code. To do this you would need to use something like boto3 to upload your code and then use the Code property to specify the S3 location.

**Comment by marty-sullivan** [comment]
Yes, I am running `aws cloudformation package`  externally to Troposphere after generating the template json.

**Comment by markpeek** [comment]
I need to think about how best to handle this issue as adding basestring would reduce the verification of Code. For example, the fix would look like this (allowing Code and basestring):
```
'Code': ((Code, basestring), True),
```
Note: you could easily override this in your code by adding a workaround like this:
```
from troposphere.awslambda import Function

# Allow Code to also be a basestring for "aws cloudformation package"
Function.props['Code'] = ((Code, basestring), True)
```

**Comment by marty-sullivan** [comment]
That makes sense; it seems like the `package` functionality is a cli-only helper function that is external to the Cloudformation spec anyway. 

Personally, I can live with the one-liner you've provided since that's elegant enough. I just didn't want to have to go through the trouble of coding the Zip packaging and S3 artifact creation on my own. The `package` command works very well and takes code versioning into account automatically.

**Comment by markpeek** [comment]
Closing per @marty-sullivan and will revisit if there is a need from the community.
