### ISSUE TITLE
Wrong format of Tags attribute in AWS::Serverless::Function

### ISSUE THREAD

**Issue by mateogianolio** [cloudtools/troposphere#873]
[The document explaining the AWS SAM 2016-10-31 transform](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction) states that `Tags` should resolve to a "Map of string to string" (`{ 'abc': '123' }`), but the current implementation of `Tags` returns a list of key-value pairs (`[{ Key: 'abc', Value: '123' }]`).

This causes an error when deploying (invalid resource) and when manually trying to supply a map of string to string it causes a validation error because the attribute type is set to `Tags` in `troposphere/serverless.py`.

Related issue where `Tags` was added: #856.

**Comment by markpeek** [comment]
Thanks! Fixed.
