### ISSUE TITLE
Security Group Rule descriptions

### ISSUE THREAD

**Issue by mentalblock** [cloudtools/troposphere#874]
Any chance we can get support for the security group rule descriptions?

https://aws.amazon.com/blogs/aws/new-descriptions-for-security-group-rules/

Thanks.

**Comment by markpeek** [comment]
This does not appear to be implemented in CloudFormation yet.

**Comment by mentalblock** [comment]
Sorry. I was definitely premature in opening this issue. I am closing this and will probably reopen this after AWS implements this in Cloudformation. Thanks.
