### ISSUE TITLE
Update CloudFront resource

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#883]
[AWS::CloudFront::Distribution](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution.html)

Use the `Tags` property to specify an arbitrary set of tags (key--value pairs) to associate with a CloudFront distribution.

In the [`CacheBehavior`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cachebehavior.html) and [`DefaultCacheBehavior`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-defaultcachebehavior.html) property types, use the `LambdaFunctionAssociations` property to specify Lambda function associations for an CloudFront distribution.

In the [`CustomOriginConfig`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-customorigin.html) property type, use the `OriginKeepaliveTimeout` property to specify a custom keep-alive timeout, and use the `OriginReadTimeout` property to specify a custom origin read timeout.

In the [`DistributionConfig`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distributionconfig.html) property type, use the `IPV6Enabled`property to specify whether CloudFront responds to IPv6 DNS requests with an IPv6 address for your distribution.

**Comment by Juberstine** [comment]
👍 for OriginReadTimeout support.

**Comment by markpeek** [comment]
Added via 35a2ba3124efff80807ff9974b70b7e01edeff9e, dc0e90fa0bdc71b26b222f93dcfd203c37dc964a, 692fc19a930d7582af0dbcb6f463bf2f4091dba0, 8d818a2b3ba109fc1352b3c721d4b21074c0d1ea, 7e5278caff9f518aa286d79572b3c7a40d5faf63
