### ISSUE TITLE
Update KMS::Key

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#889]
[AWS::KMS::Key](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html)

Use the `Tags` property to specify an arbitrary set of tags (key--value pairs) to associate with a custom master key (CMS).

**Comment by qassim** [comment]
Raised PR https://github.com/cloudtools/troposphere/pull/900

**Comment by markpeek** [comment]
Fixed via #900
