### ISSUE TITLE
Update OpsWorks::Layer

### ISSUE THREAD

**Issue by markpeek** [cloudtools/troposphere#890]
[AWS::OpsWorks::Layer](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-layer.html) and [AWS::OpsWorks::Stack](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworks-stack.html)

Use the `Tags` property to specify an arbitrary set of tags (key--value pairs) to associate with an AWS OpsWorks layer or stack.

**Comment by markpeek** [comment]
Added via 7a03dc126a8c40641432bd630d8b2832f517493a

**Comment by wesleywh** [comment]
@markpeek I still get the following error when trying to use `Tags=Tags(...)` in an `AWS::Opsworks::Layer`. 
```
AttributeError: AWS::OpsWorks::Layer object does not support attribute Tags
```
**Troposphere Version 2.1.2**
