### ISSUE TITLE
Inter-Region Peering Connection Support

### ISSUE THREAD

**Issue by mattdonnelly** [cloudtools/troposphere#935]
Amazon announced that there's now support for inter-region peering: https://aws.amazon.com/about-aws/whats-new/2017/11/announcing-support-for-inter-region-vpc-peering/ Are there any plans to add support for this?

Thanks!

**Comment by markpeek** [comment]
We will support it soon after the CloudFormation team implements and releases it. You can follow the release history [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).

**Comment by mattdonnelly** [comment]
Ah, great to hear! Wasnt aware you can follow the release history. I’ll keep an eye on it
