### ISSUE TITLE
Max memory of lambda function doubled

### ISSUE THREAD

**Issue by bellaxie** [cloudtools/troposphere#937]
Hi there,

The max memory of lambda function has doubled, could you update the accepted value, it is now throwing this error:
ValueError: Lambda Function memory size must be one of:
 128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536

Thanks.

**Comment by markpeek** [comment]
Fixed via #936
