### ISSUE TITLE
troposphere/constants missing elasticsearch m4, c4, and r4 instance types

### ISSUE THREAD

**Issue by dmunney** [cloudtools/troposphere#942]
I have an updated branch, ready to push and subsequently review, which will add m4, c4, and r4 instance types to the instance types constants.

**Comment by markpeek** [comment]
Cool. Please create the PR and I can get that into the next release.

**Comment by dmunney** [comment]
Currently, I do not have sufficient permissions to push a branch, unless I am missing something.

**Comment by markpeek** [comment]
Fixed via #948
