### ISSUE TITLE
Integer TTL Issue with route53.RecordSet

### ISSUE THREAD

**Issue by cdodd** [cloudtools/troposphere#95]
If you pass an integer for the TTL parameter to the route53.RecordSet class, the TTL will be output as an integer in the CF template. This TTL will then be ignored when the record is created as CF expects the parameter to be a string.

It would be nice and potentially save some confusion if this parameter could be explicitly converted to a string before the template is generated.

**Comment by markpeek** [comment]
Response timeout, closing.
