### ISSUE TITLE
CodeBuild not supporting BitBucket

### ISSUE THREAD

**Issue by loghen41** [cloudtools/troposphere#951]
This is most likely an enhancement.

as of Aug 2017, Code Build now supports Bitbucket as a source type: 
https://aws.amazon.com/about-aws/whats-new/2017/08/aws-codebuild-now-supports-atlassian-bitbucket-cloud-as-a-source-type/

An update is needed to allow for that new source type to be pulled in, and confirmed that aws can properly authenticate against the new source type.

Example:

```        BitBucketBuildStep = template.add_resource(Project(
            "BitBucketBuildStep",
            Artifacts=Artifacts(
                Type="NO_ARTIFACTS",
            ),
            Environment=Environment(
                ComputeType="BUILD_GENERAL1_SMALL",
                PrivilegedMode=True,
                Image=Sub("MyDockerImage"),
                Type="LINUX_CONTAINER",
                EnvironmentVariables=[]
            ),
            Name="bitbucket-build-step",
            ServiceRole="MyServiceRole",
            Source=Source(
                BuildSpec='''My Build Spec''',
                Type="BITBUCKET",
                Location="http://bitbucket.org/myrepo",
                Auth=SourceAuth(
                    Type="OAUTH"
                )
            ),
            Description="My Description"
        ))
```
This example block of code gets the following error:
```
Source Type: must be one of CODECOMMIT,CODEPIPELINE,GITHUB,S3
```

CodeBuild valid_types needs to be updated, and confirmed it work work with current OAUTH capabilities.

**Comment by PatMyron** [comment]
fixed by https://github.com/cloudtools/troposphere/pull/1160

https://github.com/cloudtools/troposphere/blob/a28753d7532a5177b85ee0838de2f78bb128d6d0/troposphere/codebuild.py#L182
