### ISSUE TITLE
Add Vpc support for CodeBuild projects

### ISSUE THREAD

**Issue by marianogg9** [cloudtools/troposphere#962]
CodeBuild project now integrates Vpc options (vpcId, subnet and SG). Please, add these properties to AWS::CodeBuild::Project resource type.

[CodeBuild's VPC support](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-vpcconfig)

Thanks!

**Comment by seddarj** [comment]
@marianogg9 It's already here https://github.com/cloudtools/troposphere/blob/master/troposphere/codebuild.py#L150.

It was added on December 2nd and it's available in release 2.1.2 from what I can tell.

**Comment by phobologic** [comment]
@seddarj is correct - thanks @seddarj - closing.
