### ISSUE TITLE
Is there way to attach existing IAM Policy to IAM role using troposphere template?

### ISSUE THREAD

**Issue by ReenaAcharya** [cloudtools/troposphere#964]
Hi,

I am trying to attach existing policy to IAM role but somehow I didn't find any code\statement to do so. Is it possible to do such stuff?

Regards,
Reena Acharya

**Comment by phobologic** [comment]
Hey @ReenaAcharya - unfortunately Cloudformation does not provide a way to do so.  Your best bet is likely to create the policy in Cloudformation along side the Role itself.  The good news is that with something like troposphere you can re-use policies by re-using the python code used to create the policy.  Let me know if you need any other help :)

**Comment by YiannisH** [comment]
Hello, is this still true?

I have the same issue, i am trying to assign an existing role to an ec2 instance created using troposphere and cnf.

**Comment by markpeek** [comment]
@YiannisH the original issue is about attaching a policy to an existing role which still isn't supported (to the best of my knowledge). What you are asking, using an existing role with an ec2 instance is different and is supported. 

I'm going off the top of my head without testing this, but you should just need to create (using the name as the role) and attach an InstanceProfile to the EC2 Instance. There is an [example](https://github.com/cloudtools/troposphere/blob/master/examples/IAM_Roles_and_InstanceProfiles.py) that shows how to create the InstanceProfile, just use the "name" and, don't use the Ref or create the role. Something like:
```
cfninstanceprofile = t.add_resource(InstanceProfile(
    "CFNInstanceProfile",
    Roles=["myexistingrole"]
))
```
If that doesn't work I'd suggest opening a new issue for more discussion.
