### ISSUE TITLE
Add support for healthCheckGracePeriodSeconds for ECS services.

### ISSUE THREAD

**Issue by mik373** [cloudtools/troposphere#969]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html

healthCheckGracePeriodSeconds
The period of time, in seconds, that the Amazon ECS service scheduler should ignore unhealthy Elastic Load Balancing target health checks after a task has first started. This is only valid if your service is configured to use a load balancer. If your service's tasks take a while to start and respond to health checks, you can specify a health check grace period of up to 1,800 seconds during which the ECS service scheduler ignores the health check status. This grace period can prevent the ECS service scheduler from marking tasks as unhealthy and stopping them before they have time to come up.

**Comment by phobologic** [comment]
#966 was created for this originally, but it is not yet released in Cloudformation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html

This will get added as soon as it's part of the Cloudformation templating language.  Thanks!

**Comment by phobologic** [comment]
Looks like it's been added, and we have a PR #971 :)
