### ISSUE TITLE
PlacementGroup Parameter

### ISSUE THREAD

**Issue by DeepSix** [cloudtools/troposphere#974]
I am having this issue when adding a placement group. 

I add a placement group using: 

newpg = trop_ec2.PlacementGroup("TestPlacementGroup")
newpg.Strategy = "cluster"
template.add_parameter(newpg)

The resulting template has this included: 
"Parameters": {
    "TestPlacementGroup": {
        "Properties": {
            "Strategy": "cluster"
        },
        "Type": "AWS::EC2::PlacementGroup"
    }
},

When I use boto3's create_stack() I get: 
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Invalid template parameter property 'Properties'

The troposphere output seems to match what would be created in the Cloudformation Designer's json.   So I'm at a loss as to what I 'm doign wrong here.

**Comment by markpeek** [comment]
Likely you want to use ```add_resource()``` instead of ```add_parameter()```.

**Comment by DeepSix** [comment]
That's it.   

Here's the working sample: 
`
# Converted from EC2InstanceSample.template located at:
# http://aws.amazon.com/cloudformation/aws-cloudformation-templates/

from troposphere import Base64, FindInMap, GetAtt
from troposphere import Parameter, Output, Ref, Template
import troposphere.ec2 as ec2


template = Template()

keyname_param = template.add_parameter(Parameter(
    "KeyName",
    Description="Name of an existing EC2 KeyPair to enable SSH "
                "access to the instance",
    Type="String",
))

template.add_mapping('RegionMap', {
    "us-east-1": {"AMI": "ami-7f418316"},
    "us-west-1": {"AMI": "ami-951945d0"},
    "us-west-2": {"AMI": "ami-16fd7026"},
    "eu-west-1": {"AMI": "ami-24506250"},
    "sa-east-1": {"AMI": "ami-3e3be423"},
    "ap-southeast-1": {"AMI": "ami-74dda626"},
    "ap-northeast-1": {"AMI": "ami-dcfa4edd"}
})

ec2_placementgroup = template.add_resource(ec2.PlacementGroup(
    "PlacementGroup",
	Strategy="cluster"
))

ec2_instance1 = template.add_resource(ec2.Instance(
    "Ec2Instance1",
    ImageId=FindInMap("RegionMap", Ref("AWS::Region"), "AMI"),
    InstanceType="t1.micro",
	PlacementGroupName="PlacementGroup",
    KeyName=Ref(keyname_param),
    SecurityGroups=["default"],
    UserData=Base64("80")
))

ec2_instance2 = template.add_resource(ec2.Instance(
    "Ec2Instance2",
    ImageId=FindInMap("RegionMap", Ref("AWS::Region"), "AMI"),
    InstanceType="t1.micro",
	PlacementGroupName="PlacementGroup",
    KeyName=Ref(keyname_param),
    SecurityGroups=["default"],
    UserData=Base64("80")
))

print(template.to_json())
`
