### ISSUE TITLE
Feature request: support for multi line strings given to Fn::Sub

### ISSUE THREAD

**Issue by et304383** [cloudtools/troposphere#976]
I'm passing a multi line string to user data like this:

```
x = """
This is
some
user data
"""

....
UserData(Base64(Sub(x)))
```

I'm getting output like this:

```
UserData: !Base64
  Fn::Sub: "\nThis is\nsome\nuser data\n"
```

I kinda expected this:

```
UserData:
  Base64:
    Fn::Sub: |
      This is
      some
      user data
```

I suspect this is partially related to the json/yaml processors and probably not something you can fix, but I thought I'd ask anyway.

**Comment by phobologic** [comment]
It's actually due to how python interprets your code:

```
>>> x = """
... This is
... some
... user data
... """
>>>
>>>
>>> print x

This is
some
user data

>>> x
'\nThis is\nsome\nuser data\n'
>>>
```

You're literally putting new lines in the variable, which is how python interprets it.  The python syntax you want to use is something like:

```
>>> x = ("This is "
... "some "
... "user data"
... )
>>> print x
This is some user data
>>> x
'This is some user data'
```

Hope that helps!

**Comment by et304383** [comment]
Umm, I want the new lines.  

I thought that was demonstrated in my desired output.

**Comment by phobologic** [comment]
@et304383 oh, sorry, misunderstood

**Comment by phobologic** [comment]
Actually, it looks like we might already support this - have you tried `long_form` in `to_yaml`?:

```
>>> t = Template()
>>> t.add_resource(WaitCondition("MyWaitCondition", Timeout=30, Handle="""My
... special multiline
... Handle
... """))
<troposphere.cloudformation.WaitCondition object at 0x100c0c190>
>>> print t.to_yaml()
Resources:
  MyWaitCondition:
    Properties:
      Handle: "My\nspecial multiline\nHandle\n"
      Timeout: 30
    Type: AWS::CloudFormation::WaitCondition
>>> print t.to_yaml(long_form=True)
Resources:
  MyWaitCondition:
    Properties:
      Handle: |
        My
        special multiline
        Handle
      Timeout: 30
    Type: AWS::CloudFormation::WaitCondition
```

**Comment by phobologic** [comment]
It appears to work with `Sub` as well:

```
>>> t = Template()
>>> t.add_resource(WaitCondition("MyWaitCondition", Timeout=30, Handle=Sub("""My
... special multiline
... Handle
... """)))
<troposphere.cloudformation.WaitCondition object at 0x100c2a610>
>>> print t.to_yaml()
Resources:
  MyWaitCondition:
    Properties:
      Handle: !Sub "My\nspecial multiline\nHandle\n"
      Timeout: 30
    Type: AWS::CloudFormation::WaitCondition

>>> print t.to_yaml(long_form=True)
Resources:
  MyWaitCondition:
    Properties:
      Handle: !Sub |
        My
        special multiline
        Handle
      Timeout: 30
    Type: AWS::CloudFormation::WaitCondition
```

**Comment by phobologic** [comment]
I'm going to go ahead and close this, as I believe `long_form=True` does what is being requested.  @et304383 let me know if  it doesn't, thanks!

**Comment by et304383** [comment]
Yup the long form flag is what I needed.  Thanks a bunch!

**Comment by phobologic** [comment]
Awesome!  Glad to help (eventually! :))

**Comment by christianbeland** [comment]
Is this still supported through long_form? i just tested this and having the same result as in the original post.

Following:
`
x = """
TEST1
TEST2
TEST3
"""
f.Code = Code(ZipFile=Sub(x))
`

with
` 
with open(local_file_name, 'w') as f:
            #yaml.dump(stack.template.to_dict(), f)
            f.write(stack.template.to_yaml(long_form=True))
`

Produces:
` 
Fn::Sub: "\n            TEST1\n            TEST2\n            TEST3\n  \
            \          "
`

**Comment by markpeek** [comment]
Good question. Been awhile since I looked at it. From the [yaml tests](https://github.com/cloudtools/troposphere/blob/master/tests/test_yaml.py#L41) it looks like that is enabled with the clean_up flag. Give that a try with your test case.

**Comment by christianbeland** [comment]
Yes it worked with the following:
clean_up=True
and 
X = """
TEST1
TEST2
TEST3"""

My original test with 
x = """
TEST1
TEST2
TEST3
"""
won't work. It seems ending the string with  /n"""  causes some sort of issue.
Anyways, it is good enough for me. Thanks a lot!!

**Comment by christianbeland** [comment]
Also, clean_up=True and long_form=True may produce unsupported/invalid template.

The long form clean up removes quote on string and may produce some invalid values and cause CloudFormation to fail with the following:

"Template error: every value of the context object of every Fn::Sub object must be a string or a function that returns a string"

**Comment by christianbeland** [comment]
it replaces valid template input

      Value:
        Fn::Join:
          - ","
          - - Fn::If:
                - HasZoneA
                - Ref: PublicSubnetA
                - Ref: "AWS::NoValue"
            - Fn::If:
                - HasZoneB
                - Ref: PublicSubnetB
                - Ref: "AWS::NoValue"
            - Fn::If:
                - HasZoneC
                - Ref: PublicSubnetC
                - Ref: "AWS::NoValue"

by

Value: !Sub
- ${Param1},${Param2},${Param3}
- Param1: !If
    - HasZoneA
    - !Ref 'PublicSubnetA'
    - !Ref 'AWS::NoValue'
  Param2: !If
    - HasZoneB
    - !Ref 'PublicSubnetB'
    - !Ref 'AWS::NoValue'
  Param3: !If
    - HasZoneC
    - !Ref 'PublicSubnetC'
    - !Ref 'AWS::NoValue'

and then fails

**Comment by shatil** [comment]
`long_form=True` doesn't work like described earlier in this threat for `troposphere==2.4.5`. In fact, after bisecting, I see that it last worked on `2.3.0`. It's broken from `2.3.1` on.

I guess I'm finally getting around to version pinning, lol.
