### ISSUE TITLE
DependsOn doesn't play well with lists of dependencies

### ISSUE THREAD

**Issue by pdex** [cloudtools/troposphere#982]
```python
DependsOn=[Vpc, RouteTable]
```

successfully creates a template. But cloudformation will fail when you try to use it.

> Template format error: Every DependsOn value must be a string.

work around: 
```python
DependsOn=[Vpc.title, RouteTable.title]
```
or
```python
from troposphere import depends_on_helper
DependsOn=map(depends_on_helper, [Vpc, RouteTable])
```

`depends_on_helper` should probably be updated to handle lists.

**Comment by markpeek** [comment]
Thanks! I just pushed a commit to handle it.

**Comment by pdex** [comment]
Thanks for your prompt commit!
