### ISSUE TITLE
CreationPolicy is a permitted parameter of WaitCondition

### ISSUE THREAD

**Issue by kadrach** [cloudtools/troposphere#986]
This appears to be valid CloudFormation:
https://github.com/awslabs/aws-batch-helpers/blob/master/gpu-example/create-ami.yaml#L23

Doing this in troposphere, it complains about a missing resource handle on the WaitCondition, and indeed the CloudFormation documentation says it is [required](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html). Is the [dependsOn](https://github.com/awslabs/aws-batch-helpers/blob/master/gpu-example/create-ami.yaml#L67) clause somehow implicitly creating a WaitConditionHandle? How can I do this in troposphere?

**Comment by markpeek** [comment]
I can't say why the create-ami.yaml would work in CloudFormation. Something AWS support might be able to discuss.

As you noted, the CF documentation states a WaitConditionHandle is a required property for WaitCondition and troposphere enforces it. The easy fix is to add a handle and just ref it into your WaitCondition. There is an example [here](https://github.com/cloudtools/troposphere/blob/master/examples/WaitObject.py).

**Comment by markpeek** [comment]
Oh interesting...thanks for following up. I did find this [reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-waitcondition.html) to use a CreationPolicy instead of wait conditions for some resources.

I did a quick PR #988 for you to check out if you need the override in the required fields.

**Comment by kadrach** [comment]
Thank you @markpeek, works as expected :)
