### ISSUE TITLE
New RDS engine type "aurora-mysql"

### ISSUE THREAD

**Issue by ryan-ju** [cloudtools/troposphere#990]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/AuroraMySQL.Updates.20180206.html

The latest AWS update introduced a new engine type `aurora-mysql`.

**Comment by markpeek** [comment]
Thanks for the issue. I just pushed an update to include it. Not sure if CloudFormation will allow it or not.

**Comment by ryan-ju** [comment]
Thanks @markpeek , that was super fast
