### ISSUE TITLE
VPC Peering Connection is missing support for Inter-Region

### ISSUE THREAD

**Issue by brandonshough** [cloudtools/troposphere#991]
I'm trying to orchestrate connectivity between VPCs using Inter-Region VPC Peering Connections.  It looks like the VPCPeeringConnection class does not support this yet.

https://github.com/cloudtools/troposphere/blob/bef6d6ba6eca19f44dbd073df823b4198f4e549e/troposphere/ec2.py#L643

**Comment by brandonshough** [comment]
https://aws.amazon.com/about-aws/whats-new/2017/11/announcing-support-for-inter-region-vpc-peering/

**Comment by brandonshough** [comment]
Looking a bit further I guess AWS doesn't even support it yet themselves with Cloudformation. 😢

**Comment by markpeek** [comment]
Yes, new features sometimes takes awhile to make it into CloudFormation.

**Comment by andreimahu** [comment]
CF now supports [peer region](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html#cfn-ec2-vpcpeeringconnection-peerregion)

**Comment by markpeek** [comment]
Thanks, yes, this was added via #1123.
