### ISSUE TITLE
ApiGateway::DomainName CertificateArn requirement prevents deployment

### ISSUE THREAD

**Issue by ibejohn818** [cloudtools/troposphere#997]
Issue: ApiGateway::DomainName requires CertificateArn.
The requirement ApiGateway:DomainName:CertificateArn  needs to be removed in-order to create an ApiGateway:DomainName w/ssl for an ApiGateway in REGION mode

Use-case:
API Gateway as a CloudFront origin.

In-order to implement this use-case, you need to deploy the following
API Gateway – REGION Deployment
ACM – generated in same region as the API gateway for the custom domain
AMC – Generated in us-east-1 For Cloudfront
ApyGateway:Domain w/RegionalCertificateArn
ApiGateway:BasePathMapping 

I’ve implemented the fix, ran tests and created a PR

https://github.com/cloudtools/troposphere/pull/996

Thanks!

-JH

**Comment by markpeek** [comment]
Fixed via #996
